project:
  type: website
  output-dir: _site
  render:
    - index.qmd
    - analyses/2026-05-lfp/index.qmd
    - analyses/2026-05-EA-boundaries/index.qmd
    - analyses/2026-05-car-rms/index.qmd

website:
  title: "Analysis Hub"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: analyses/
        text: Analyses
    right:
      - icon: github
        href: https://github.com/oliche
  page-footer:
    center: "Olivier Winter"

execute:
  freeze: auto

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    code-fold: true
    code-tools: true
    highlight-style: github