{
  "hash": "4928ff3f918f393fa027d17e7fc4473c",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"lfpack v04: Compressing Neuropixels LFP\"\ndescription: \"A denoise, SVD and wavelet-packet codec that shrinks brain-wide Neuropixels LFP to 0.8–3.1 % of its float32 size, with format 2, a shared spatial basis and three α tiers, validated on behaviour and brain-region decoding.\"\ndate: \"2026-06-09\"\ndate-modified: \"2026-10-02\"\nauthor: \"Olivier Winter\"\ncategories: [electrophysiology, LFP, compression, Neuropixels, decoding]\n---\n\n## Summary\n\nlfpack decimates Neuropixels LFP to 250 Hz, denoises it with Cadzow, and compresses each 8 s chunk with an SVD\n(spatial) followed by wavelet-packet thresholding of the temporal rows. The v04 archive (v03 deprecated) ships three\ntiers that differ only in the wavelet threshold α. All use file format 2 and a shared spatial basis (m = 32, ε = 100).\n\n| v04 tier | α | 1/CR (11 probes) | 1/CR (archive) | SNR (dB) | Ephys Atlas (1099 PIDs) | BWM | wheel R² | feedback bal. acc. | Region CV accuracy |\n|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|\n| small | 14 | 0.82 % | 0.57 % | 14.4 | 11.2 GB | 7.7 GB | 0.134 | 0.627 | 0.518 |\n| default | 7 | 1.55 % | 1.10 % | 18.5 | 21.5 GB | 14.9 GB | 0.136 | 0.625 | 0.538 |\n| fine | 2.5 | 3.09 % | 2.36 % | **23.4** | 46.1 GB | 31.9 GB | **0.139** | **0.641** | **0.544** |\n| *v03 mild (format 1, per-chunk U)* | *14* | *2.14 %* | *1.75 %* | *14.4* | *34.2 GB* | *23.3 GB* | *0.134* | *0.626* | *0.513* |\n| **uncompressed (float32, 250 Hz)** | — | **100 %** | **100 %** | — | **1955.7 GB** | — | **0.139** | **0.642** | **0.551** |\n\n1/CR = file / uncompressed float32 at 250 Hz, on summed file sizes over the 11 benchmark insertions or over the 1099\narchive PIDs (longer recordings compress better). SNR, wheel R² and feedback accuracy: mean over the 11 insertions; region: 5-fold PID-grouped held-out accuracy of the TS3 classifier on the 1054 training insertions, mean over 3 model seeds (the 3222 eval units are too few to rank tiers, see the Results). Bold: best performance among the compressed tiers (SNR, wheel R², feedback, TS3) and the uncompressed reference. Wheel R², choice and feedback accuracy at\n`small` are within the between-insertion spread of the uncompressed signal. Region decoding keeps improving down to\nα = 2.5, so `fine` is the tier for atlas-scale work.\n\n## Why compress LFP\n\nOver the 1099 histology-resolved insertions of the ephys atlas (including the Brain Wide Map, BWM), the decimated\n250 Hz float32 LFP alone is 1955.7 GB, too large to move around or to read at random for analyses that need a few\nseconds from many probes. The downstream uses are:\n\n- **Brain-region classification** from LF and CSD features of every channel (ephys atlas, TS3 of the brain-wide\n  benchmark).\n- **Behaviour decoding** (wheel speed, choice, feedback) from LFP band power.\n- **Lagged encoding models** of the LFP from task variables.\n\nThe v04 `small` archive makes the whole cohort fit on a laptop disk (11.2 GB) and still supports these analyses. The\nquestion this page answers is how far the file can shrink before the science changes.\n\n## Methods\n\n### Pre-processing and Cadzow denoising\n\nFor each insertion the LF band is (1) checked for bad channels (anomalous variance, flagged and excluded),\n(2) high-passed (3rd-order Butterworth, zero-phase, 0.5 Hz in production), common-average referenced and decimated ×10\nto 250 Hz float32, then (3) denoised with **Cadzow F-X filtering**: per frequency bin ≤ 100 Hz, a rank-r (≤ 5, adaptive\nby singular-value gap 2.0) SVD of the block-Toeplitz trajectory matrix of the channel vector, with outlier channels\n(median + 2 MAD) imputed from the model and the SVD repeated; 3 s snippets, nw = 64. Cadzow removes spatially\nincoherent noise before compression, so the codec spends its bytes on signal. The Cadzow step (@fig-cadzow; all insertions in the collapsible below) is unchanged since v03,\nand **every benchmark below runs on the Cadzow-denoised signal**, so residuals reflect compression loss only.\n\n![Cadzow denoising for insertion e8f9fba4. Three 3 s snippets (rows): original / denoised (adaptive rank) / difference (same colour scale).](figures/2026-06-06_cadzow_e8f9fba4-d151-4b00-bee7-447f0f3e752c.png){#fig-cadzow}\n\n::: {.callout-note collapse=\"true\" appearance=\"minimal\"}\n## Cadzow denoising for the 11 benchmark insertions\n\n::: {.panel-tabset}\n\n### 1a276285\n\n![Cadzow denoising, insertion 1a276285.](figures/2026-06-06_cadzow_1a276285-8b0e-4cc9-9f0a-a3a002978724.png){#fig-cadzow-1a276285}\n\n### 1e104bf4\n\n![Cadzow denoising, insertion 1e104bf4.](figures/2026-06-06_cadzow_1e104bf4-7a24-4624-a5b2-c2c8289c0de7.png){#fig-cadzow-1e104bf4}\n\n### 6638cfb3\n\n![Cadzow denoising, insertion 6638cfb3.](figures/2026-06-06_cadzow_6638cfb3-3831-4fc2-9327-194b76cf22e1.png){#fig-cadzow-6638cfb3}\n\n### 749cb2b7\n\n![Cadzow denoising, insertion 749cb2b7.](figures/2026-06-06_cadzow_749cb2b7-e57e-4453-a794-f6230e4d0226.png){#fig-cadzow-749cb2b7}\n\n### d7ec0892\n\n![Cadzow denoising, insertion d7ec0892.](figures/2026-06-06_cadzow_d7ec0892-0a6c-4f4f-9d8f-72083692af5c.png){#fig-cadzow-d7ec0892}\n\n### da8dfec1\n\n![Cadzow denoising, insertion da8dfec1.](figures/2026-06-06_cadzow_da8dfec1-d265-44e8-84ce-6ae9c109b8bd.png){#fig-cadzow-da8dfec1}\n\n### dab512bd\n\n![Cadzow denoising, insertion dab512bd.](figures/2026-06-06_cadzow_dab512bd-a02d-4c1f-8dbc-9155a163efc0.png){#fig-cadzow-dab512bd}\n\n### dc7e9403\n\n![Cadzow denoising, insertion dc7e9403.](figures/2026-06-06_cadzow_dc7e9403-19f7-409f-9240-05ee57cb7aea.png){#fig-cadzow-dc7e9403}\n\n### e8f9fba4\n\n![Cadzow denoising, insertion e8f9fba4.](figures/2026-06-06_cadzow_e8f9fba4-d151-4b00-bee7-447f0f3e752c.png){#fig-cadzow-e8f9fba4}\n\n### eebcaf65\n\n![Cadzow denoising, insertion eebcaf65.](figures/2026-06-06_cadzow_eebcaf65-7fa4-4118-869d-a084e84530e2.png){#fig-cadzow-eebcaf65}\n\n### fe380793\n\n![Cadzow denoising, insertion fe380793.](figures/2026-06-06_cadzow_fe380793-8035-414e-b000-09bfe5ece92a.png){#fig-cadzow-fe380793}\n\n\n\n:::\n:::\n\n### Codec\n\nEach 8 s chunk $X_j$ (384 channels × 2048 samples, plus 128 guard samples each side) is factorised as\n\n$$X_j \\approx U_r\\,\\mathrm{diag}(s_r)\\,\\hat V_r^\\top, \\qquad r = \\#\\{k : s_k > \\varepsilon\\,\\sigma_0\\}, \\qquad\n\\tau_k = \\alpha\\,\\sigma_0 / s_k$$\n\nwhere $\\sigma_0$ is the median of the lower half of the singular values, ε sets the rank (≈ 17 at ε = 100) and α the\nhard threshold on the db4 level-5 wavelet-packet coefficients of each temporal row. Every discarded coefficient\ntherefore costs less than α σ₀ of reconstruction error, whatever its component. The dominant row always keeps its 64\nlargest coefficients, so a low-SNR chunk never reconstructs to zero. The two stages are independent in their\ndefinition (ε sets the rank from the raw spectrum, α the temporal detail kept within it), but not in effect: τ is\nnormalised by $s_k$, so a given α lands differently for a different ε. A walk-through of every array is in the\n**lfpack Matrix Anatomy** page (<https://claude.ai/artifact/3KqmXv3z7tsrbWSrMXTsU1>).\n\n### Bracketing ε and α\n\nε and α were bracketed on the 11 benchmark insertions before any tier was chosen. The singular-value spectra give the\nε that selects a given rank (ε ≈ 155 for rank 16, ≈ 47 for rank 32), and the α sweep gives the wavelet-stage\ncompression for each SVD-stage ratio. The curves are tight across insertions, so one (ε, α) generalises across\nrecordings (@fig-eps-rank, @fig-alpha-sweep, @fig-wp-aggregate). When α/ε exceeds the largest wavelet coefficient of a weak component, that component is zeroed entirely:\nthe wavelet stage then overrides the SVD rank.\n\n![Left: for each insertion, $\\varepsilon(r) = s_r / \\sigma_0$, the ε that selects exactly rank r, vs rank. Right: singular values (µV) with the per-insertion noise floor σ₀ (dashed). Top axis: SVD-stage compression ratio.](figures/2026-06-10_epsilon_vs_rank.png){#fig-eps-rank}\n\n![α vs wavelet-stage compression ratio for each SVD-stage ratio (db4, level 5). Thin lines: insertions; heavy line: median.](figures/2026-06-12_svd_adaptive_wp_alpha_sweep.png){#fig-alpha-sweep}\n\n![Adaptive SVD+WP aggregate quality. Left: median RMSE (µV) vs total CR; right: median SNR (dB) vs total CR. One curve per SVD-stage CR; α labelled at each point.](figures/2026-06-12_adaptive_wp_aggregate.png){#fig-wp-aggregate}\n\nThe bracket was then closed on decoding rather than on RMSE: a 42-cell (ε, α) grid (ε 50–450, α 14–96) decoded for\nbehaviour showed α is the lever that moves decoding while ε alone buys neither size nor a reliable decoding cost (see\nthe appendix). That is why v04 fixes ε = 100 and varies only α.\n\n### File format 2\n\nFormat 2 (lfpack branch `feat/container-v2`) stores all chunks of a scale in four flat datasets (`chunk_table`,\n`u_values`, `vh_deltas`, `vh_values`) with offsets from the chunk table, so a random read still touches one or two\n64 kB storage blocks. Indices are uint16 deltas, and the ~9 % of kept wavelet coefficients whose synthesis function is\nzero over the written samples are dropped, which is exactly lossless. Old files stay readable; `lfpack.upgrade_h5`\nconverts them. Per 8 s chunk, mild tier, 1a276285 (1.4 h, 607 chunks):\n\n| Layout | HDF5 overhead | spatial U | temporal Vh | total |\n|---|---:|---:|---:|---:|\n| Format 1: one HDF5 group per chunk, int32 indices | 9.5 kB | 22.7 kB | 31.7 kB | 63.8 kB |\n| Format 2 | — | 21.6 kB | 25.1 kB | 46.7 kB |\n| Format 2 + shared basis m = 48 | — | 1.7 kB | 25.1 kB | 26.8 kB |\n\n### Shared spatial basis\n\nIn format 2 the per-chunk U matrices are nearly half of the file, while the spatial subspace of a recording barely\nmoves (cos² 0.98 between neighbouring chunks, 0.95 at 40 min apart). The codec runs per chunk unchanged; only the\nspatial factor is replaced:\n\n$$C_j = B^\\top U_j \\;(m \\times r,\\ \\text{float16, float32 per-column scale folded into } s), \\qquad U_j \\approx B\\,C_j$$\n\n$B$ (384 × m, float32, once per recording) holds the top-m eigenvectors of $\\sum_j U_j s_j^2 U_j^\\top / \\lVert U_j s_j\n\\rVert^2$, with $U_j$ truncated at the chunk's rank so every chunk weighs the same. The temporal rows and thresholds do\nnot depend on $B$, so an encoder can write them as it goes and keep only $U_j s_j$ in memory (~26 kB per chunk) until\n$B$ is computed at the end. Re-decomposing each chunk inside $B$ instead gives the same result (bytes 0.003 %, SNR\n0.001 dB, wheel R² 0.0001).\n\n### Evaluation\n\n- **Fidelity.** SNR = 10·log₁₀ Σx² / Σe², pooled over all written samples of a recording (worst decile: 10th\n  percentile of per-chunk SNR).\n- **Behaviour decoding (11 insertions).** Band-power envelope features (log Hilbert amplitude, delta / theta / beta /\n  gamma, 96 channels after 4:1 spatial binning), identical for every tier, from the Cadzow checkpoint or its\n  in-memory reconstruction. |wheel velocity|: RidgeCV on 50 ms bins, 5-fold chronological CV, R². Choice\n  ([−0.2, 0) s around first movement) and feedback ([0, 0.2) s around feedback): standardised LogisticRegressionCV,\n  5-fold stratified CV, balanced accuracy. The null is a per-fold shuffle, held identical across tiers, which is what\n  a relative comparison needs.\n- **Region decoding, ephys atlas (1099 insertions, 407 616 channels).** 33 LF and CSD features per channel\n  (`raw_lf`, `raw_lf_csd`) from ~8 snippets per insertion (8.79 s windows, 600 s spacing), 5-fold PID-grouped\n  XGBoost on Cosmos labels (`VINTAGE = \"2026-08_lfp-decoders\"`). Snippets are either naive (`all`) or\n  **saturation-avoided** (no overlap with an ADC-saturated interval).\n- **Region decoding, TS3 of the brain-wide benchmark.** The same classifier, trained on the 1054 non-eval insertions\n  and applied to each of the 3222 eval units through its nearest LFP channel by depth; scored with\n  `ibl_bwb_eval.scoring.ts3`. The comparison across tiers is paired: same insertions, same saturation-avoided snippet\n  times (saturation comes from the raw ADC signal and the Cadzow checkpoints are shared), same 5-fold split, same\n  ground truth. Only the archive changes. Mean ± s.e.m. over 3 model seeds (43 / 44 / 45).\n\n## Results\n\n### Size against fidelity and decoding\n\nEvery point of the sweep was decoded with the behaviour pipeline on the in-memory reconstruction: α ∈ {2.5, 3.5, 5, 7,\n10, 14}; m = 48 at ε ∈ {50, 70, 100}; m ∈ {32, 24, 16} and int8 C (m = 48, 24) at ε = 100; per-chunk U at ε = 100.\nCode: `shared_basis_sweep.py`, `pareto_sweep.py`, `plot_pareto.py`; results `2026-09-26_pareto_*.csv`.\n\n![File size vs wheel-R² change against the mild tier (top) and SNR (bottom), mean ± s.e.m. over 11 insertions (error bars on the per-chunk-U and m = 48, ε = 100 references only). Left: rank threshold ε at m = 48; right: basis size and C precision at ε = 100. Dotted: uncompressed; star: mild tier (format 2, per-chunk U, α = 14).](figures/2026-09-26_pareto_size-vs-decoding.png){#fig-pareto}\n\n| ε = 100 | α | 1/CR | size / mild | SNR (dB) | worst-decile SNR | Δ wheel R² mean | median |\n|---|---:|---:|---:|---:|---:|---:|---:|\n| per-chunk U (mild) | 14 | 1.59 % | 1.00 | 14.4 | 13.3 | 0 | 0 |\n| per-chunk U | 7 | 2.33 % | 1.46 | 18.5 | 17.3 | +0.0025 | +0.0015 |\n| per-chunk U | 2.5 | 3.87 % | 2.43 | 23.5 | 22.2 | +0.0047 | +0.0031 |\n| shared m = 32 | 14 | 0.82 % | 0.51 | 14.4 | 13.3 | −0.0002 | −0.0001 |\n| shared m = 32 | 10 | 1.13 % | 0.71 | 16.4 | 15.2 | +0.0016 | +0.0007 |\n| shared m = 32 | 7 | 1.55 % | 0.97 | 18.5 | 17.3 | +0.0022 | +0.0017 |\n| shared m = 32 | 5 | 2.02 % | 1.27 | 20.4 | 19.2 | +0.0032 | +0.0017 |\n| shared m = 32 | 3.5 | 2.57 % | 1.61 | 22.2 | 20.9 | +0.0040 | +0.0026 |\n| shared m = 32 | 2.5 | 3.09 % | 1.94 | 23.4 | 22.1 | +0.0048 | +0.0030 |\n| uncompressed | — | 100 % | — | — | — | +0.0053 | +0.0027 |\n\n- **Only α moves decoding.** At equal α the shared basis and per-chunk U decode identically (median paired difference\n  0.00001); the basis makes each α 20–50 % cheaper, more at high α.\n- **More rank does not pay:** ε = 70 matches ε = 100 and ε = 50 is slightly worse per byte.\n- **The spatial part is exhausted at m ≈ 24–32** (1–4 % of the file); m = 24–48 decode alike, m = 16 loses up to\n  1.6 dB SNR.\n- **int8 C is a trap:** −1 to −5 % bytes and < 0.12 dB SNR, but wheel R² drops on 83 % of probe-α pairs (up to\n  −0.011 on dab512bd). SNR is a poor proxy for decoding; C stays in float16.\n- **The mean gap is carried by two insertions** (e8f9fba4 +0.031, eebcaf65 +0.014 uncompressed vs mild). Per\n  insertion, lowering α moves R² monotonically towards its own uncompressed value; the median insertion reaches it at\n  α ≈ 3.5.\n- **dab512bd is the exception:** worst at intermediate α (−0.013 at α = 5–7) and the most sensitive to any spatial\n  approximation; unexplained.\n\nThe three tiers sit on this curve at α = 14, 7 and 2.5 (@fig-pareto, @fig-tiers):\n\n![The three v04 tiers (shared basis m = 32, ε = 100) against the mild baseline (format 2, per-chunk U, α = 14). Left: wheel-R² change against the mild tier; right: reconstruction SNR; mean ± s.e.m. over 11 insertions, dotted: uncompressed. Open star: v03 mild as shipped, in format 1 (size estimated as format 2 / 0.71, same decoding).](figures/2026-09-27_pareto_v04-tiers.png){#fig-tiers}\n\n### Reconstruction of each insertion\n\nEach Cadzow-denoised checkpoint was re-encoded (@fig-ins-1a276285 to @fig-ins-fe380793, one tab per insertion) with the v04 codec at α = 2.5, 7 and 14 (real format-2 files, not the\nin-memory reconstructions of the sweep) and a 3 s window is shown mid-recording as LFP, residual and CSD next to the\noriginal. The residual is displayed with a 5× tighter colour scale than the LFP. SNR and size are for the whole\nrecording. The CSD (second spatial difference between channels two rows apart) is the most demanding view: `small`\nsmooths fine spatial structure that `fine` keeps.\n\n::: {#tbl-v04-insertions .cell tbl-cap='Whole-recording SNR (dB) and file size (MB) of each benchmark insertion at the three v04 tiers (shared basis m = 32, ε = 100).' execution_count=2}\n\n::: {.cell-output .cell-output-display execution_count=2}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>fine SNR</th>\n      <th>default SNR</th>\n      <th>small SNR</th>\n      <th>fine MB</th>\n      <th>default MB</th>\n      <th>small MB</th>\n    </tr>\n    <tr>\n      <th>pid</th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>1a276285</th>\n      <td>25.6</td>\n      <td>20.4</td>\n      <td>15.9</td>\n      <td>53.9</td>\n      <td>29.3</td>\n      <td>16.0</td>\n    </tr>\n    <tr>\n      <th>1e104bf4</th>\n      <td>25.4</td>\n      <td>20.1</td>\n      <td>15.5</td>\n      <td>54.5</td>\n      <td>30.3</td>\n      <td>17.1</td>\n    </tr>\n    <tr>\n      <th>6638cfb3</th>\n      <td>24.9</td>\n      <td>19.6</td>\n      <td>15.5</td>\n      <td>38.3</td>\n      <td>18.6</td>\n      <td>9.5</td>\n    </tr>\n    <tr>\n      <th>749cb2b7</th>\n      <td>26.2</td>\n      <td>21.4</td>\n      <td>17.4</td>\n      <td>57.1</td>\n      <td>29.6</td>\n      <td>17.0</td>\n    </tr>\n    <tr>\n      <th>d7ec0892</th>\n      <td>21.1</td>\n      <td>16.3</td>\n      <td>11.9</td>\n      <td>72.2</td>\n      <td>37.5</td>\n      <td>19.0</td>\n    </tr>\n    <tr>\n      <th>da8dfec1</th>\n      <td>19.4</td>\n      <td>14.7</td>\n      <td>10.9</td>\n      <td>61.2</td>\n      <td>27.9</td>\n      <td>12.9</td>\n    </tr>\n    <tr>\n      <th>dab512bd</th>\n      <td>25.9</td>\n      <td>20.8</td>\n      <td>16.8</td>\n      <td>34.4</td>\n      <td>17.0</td>\n      <td>9.7</td>\n    </tr>\n    <tr>\n      <th>dc7e9403</th>\n      <td>23.3</td>\n      <td>18.3</td>\n      <td>14.3</td>\n      <td>75.6</td>\n      <td>37.0</td>\n      <td>19.4</td>\n    </tr>\n    <tr>\n      <th>e8f9fba4</th>\n      <td>19.9</td>\n      <td>15.2</td>\n      <td>11.3</td>\n      <td>68.9</td>\n      <td>33.0</td>\n      <td>16.5</td>\n    </tr>\n    <tr>\n      <th>eebcaf65</th>\n      <td>20.8</td>\n      <td>16.6</td>\n      <td>13.3</td>\n      <td>43.5</td>\n      <td>19.2</td>\n      <td>9.5</td>\n    </tr>\n    <tr>\n      <th>fe380793</th>\n      <td>25.0</td>\n      <td>19.8</td>\n      <td>15.5</td>\n      <td>72.8</td>\n      <td>38.0</td>\n      <td>20.6</td>\n    </tr>\n    <tr>\n      <th>mean</th>\n      <td>23.4</td>\n      <td>18.5</td>\n      <td>14.4</td>\n      <td>57.5</td>\n      <td>28.8</td>\n      <td>15.2</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n::: {.panel-tabset}\n\n### 1a276285\n\n![Insertion 1a276285: original, fine (α = 2.5), default (α = 7) and small (α = 14). Rows: LFP, residual (original − reconstruction, colour scale ÷ 5), CSD.](figures/2026-10-02_v04_insertion_1a276285.png){#fig-ins-1a276285 .lightbox}\n\n### 1e104bf4\n\n![Insertion 1e104bf4: original, fine (α = 2.5), default (α = 7) and small (α = 14). Rows: LFP, residual (original − reconstruction, colour scale ÷ 5), CSD.](figures/2026-10-02_v04_insertion_1e104bf4.png){#fig-ins-1e104bf4 .lightbox}\n\n### 6638cfb3\n\n![Insertion 6638cfb3: original, fine (α = 2.5), default (α = 7) and small (α = 14). Rows: LFP, residual (original − reconstruction, colour scale ÷ 5), CSD.](figures/2026-10-02_v04_insertion_6638cfb3.png){#fig-ins-6638cfb3 .lightbox}\n\n### 749cb2b7\n\n![Insertion 749cb2b7: original, fine (α = 2.5), default (α = 7) and small (α = 14). Rows: LFP, residual (original − reconstruction, colour scale ÷ 5), CSD.](figures/2026-10-02_v04_insertion_749cb2b7.png){#fig-ins-749cb2b7 .lightbox}\n\n### d7ec0892\n\n![Insertion d7ec0892: original, fine (α = 2.5), default (α = 7) and small (α = 14). Rows: LFP, residual (original − reconstruction, colour scale ÷ 5), CSD.](figures/2026-10-02_v04_insertion_d7ec0892.png){#fig-ins-d7ec0892 .lightbox}\n\n### da8dfec1\n\n![Insertion da8dfec1: original, fine (α = 2.5), default (α = 7) and small (α = 14). Rows: LFP, residual (original − reconstruction, colour scale ÷ 5), CSD.](figures/2026-10-02_v04_insertion_da8dfec1.png){#fig-ins-da8dfec1 .lightbox}\n\n### dab512bd\n\n![Insertion dab512bd: original, fine (α = 2.5), default (α = 7) and small (α = 14). Rows: LFP, residual (original − reconstruction, colour scale ÷ 5), CSD.](figures/2026-10-02_v04_insertion_dab512bd.png){#fig-ins-dab512bd .lightbox}\n\n### dc7e9403\n\n![Insertion dc7e9403: original, fine (α = 2.5), default (α = 7) and small (α = 14). Rows: LFP, residual (original − reconstruction, colour scale ÷ 5), CSD.](figures/2026-10-02_v04_insertion_dc7e9403.png){#fig-ins-dc7e9403 .lightbox}\n\n### e8f9fba4\n\n![Insertion e8f9fba4: original, fine (α = 2.5), default (α = 7) and small (α = 14). Rows: LFP, residual (original − reconstruction, colour scale ÷ 5), CSD.](figures/2026-10-02_v04_insertion_e8f9fba4.png){#fig-ins-e8f9fba4 .lightbox}\n\n### eebcaf65\n\n![Insertion eebcaf65: original, fine (α = 2.5), default (α = 7) and small (α = 14). Rows: LFP, residual (original − reconstruction, colour scale ÷ 5), CSD.](figures/2026-10-02_v04_insertion_eebcaf65.png){#fig-ins-eebcaf65 .lightbox}\n\n### fe380793\n\n![Insertion fe380793: original, fine (α = 2.5), default (α = 7) and small (α = 14). Rows: LFP, residual (original − reconstruction, colour scale ÷ 5), CSD.](figures/2026-10-02_v04_insertion_fe380793.png){#fig-ins-fe380793 .lightbox}\n\n\n\n:::\n\n### Behaviour decoding on single probes\n\nWheel speed, choice and feedback were decoded on the 11 insertions for the uncompressed signal, the three v03 tiers\n(the 42-cell grid of the appendix: `aggressive` ε = 450 / α = 96, `default` ε = 150 / α = 28, `mild` ε = 100 / α = 14,\nformat 1) and the three v04 tiers (@fig-decoding).\n\n::: {#tbl-decoding-tiers .cell tbl-cap='Behaviour decoding on 11 insertions, mean ± s.e.m. 1/CR: summed file size / uncompressed float32 at 250 Hz; file / v03 mild: summed file sizes. Chance is 0.5 for choice and feedback.' execution_count=4}\n\n::: {.cell-output .cell-output-display execution_count=4}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>1/CR</th>\n      <th>file / v03 mild</th>\n      <th>wheel R²</th>\n      <th>choice</th>\n      <th>feedback</th>\n    </tr>\n    <tr>\n      <th>tier</th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>uncompressed</th>\n      <td>100.00%</td>\n      <td>46.81</td>\n      <td>0.139 ± 0.029</td>\n      <td>0.564 ± 0.024</td>\n      <td>0.642 ± 0.040</td>\n    </tr>\n    <tr>\n      <th>v03 aggressive</th>\n      <td>0.48%</td>\n      <td>0.23</td>\n      <td>0.104 ± 0.022</td>\n      <td>0.552 ± 0.023</td>\n      <td>0.557 ± 0.025</td>\n    </tr>\n    <tr>\n      <th>v03 default</th>\n      <td>1.19%</td>\n      <td>0.56</td>\n      <td>0.127 ± 0.026</td>\n      <td>0.563 ± 0.024</td>\n      <td>0.597 ± 0.033</td>\n    </tr>\n    <tr>\n      <th>v03 mild</th>\n      <td>2.14%</td>\n      <td>1.00</td>\n      <td>0.134 ± 0.027</td>\n      <td>0.556 ± 0.023</td>\n      <td>0.626 ± 0.040</td>\n    </tr>\n    <tr>\n      <th>v04 small</th>\n      <td>0.82%</td>\n      <td>0.38</td>\n      <td>0.134 ± 0.027</td>\n      <td>0.557 ± 0.023</td>\n      <td>0.627 ± 0.040</td>\n    </tr>\n    <tr>\n      <th>v04 default</th>\n      <td>1.55%</td>\n      <td>0.73</td>\n      <td>0.136 ± 0.028</td>\n      <td>0.562 ± 0.024</td>\n      <td>0.625 ± 0.039</td>\n    </tr>\n    <tr>\n      <th>v04 fine</th>\n      <td>3.09%</td>\n      <td>1.45</td>\n      <td>0.139 ± 0.029</td>\n      <td>0.562 ± 0.025</td>\n      <td>0.641 ± 0.038</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n![Behaviour decoding per tier. Grey: the 11 insertions; heavy markers: mean ± s.e.m. (blue: uncompressed and v03 tiers, orange: v04 tiers). Dotted: chance.](figures/2026-10-02_decoding_tiers.png){#fig-decoding .lightbox}\n\n- **v04 `small` matches v03 mild at 0.38× its size on these insertions (0.33× on the full archive)**: wheel R² 0.1336 vs 0.1337, feedback 0.627 vs 0.626.\n- **Lowering α recovers the uncompressed score**, feedback first: 0.627 → 0.625 → 0.641 (α = 14 → 7 → 2.5) against\n  0.642 uncompressed. Wheel R² goes 0.1336 → 0.1360 → 0.1385 against 0.1390. Choice is flat within noise at every tier.\n- **The v03 tiers rank as before:** `aggressive` loses the most (feedback 0.557, wheel R² 0.104), because feedback is\n  decoded from a brief post-event window, exactly the fast phasic structure the wavelet threshold removes first.\n- Per-insertion feedback accuracy varies widely (SD ≈ 0.11 between insertions), which swamps the tier effect in raw\n  values; the lines in the figure are paired within insertion.\n\n### Region decoding\n\n**Ephys atlas, v03 tiers (1099 insertions).** Held-out Cosmos accuracy decreases monotonically with compression\n(13 classes, `snippet_mode = \"all\"`): uncompressed 0.468 > mild 0.435 (−3.3 pp) > default 0.420 (−4.8 pp) > aggressive\n0.389 (−7.9 pp). This mirrors the behaviour ranking on a different task, decoder and a ~100× larger cohort (@fig-region-v03).\n\n::: {#6b078a6d .cell execution_count=5}\n\n::: {.cell-output .cell-output-display execution_count=5}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>lfp_source</th>\n      <th>snippet_mode</th>\n      <th>accuracy</th>\n      <th>n_pids</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>uncompressed</td>\n      <td>all</td>\n      <td>0.468500</td>\n      <td>1099</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>uncompressed</td>\n      <td>saturation-avoided</td>\n      <td>0.470953</td>\n      <td>1099</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>mild</td>\n      <td>all</td>\n      <td>0.434706</td>\n      <td>1099</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>default</td>\n      <td>all</td>\n      <td>0.420096</td>\n      <td>1099</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>default</td>\n      <td>saturation-avoided</td>\n      <td>0.416753</td>\n      <td>1099</td>\n    </tr>\n    <tr>\n      <th>5</th>\n      <td>aggressive</td>\n      <td>all</td>\n      <td>0.389008</td>\n      <td>1099</td>\n    </tr>\n    <tr>\n      <th>6</th>\n      <td>aggressive</td>\n      <td>saturation-avoided</td>\n      <td>0.391597</td>\n      <td>1099</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n![Mean held-out Cosmos accuracy across 1099 insertions, `snippet_mode = \"all\"`, per v03 tier.](figures/2026-09-05_lfp-decoders_compression-impact.png){#fig-region-v03 .lightbox}\n\nAvoiding ADC-saturated snippets does not change region decoding beyond fold-to-fold spread (default −0.3 pp,\naggressive +0.3 pp, uncompressed +0.2 pp), so saturation handling does not trade off against the tier (@fig-saturation).\n\n![Effect of saturation avoidance, mean ± SD across 5 folds, dots: folds. `mild` was run only with naive snippets.](figures/2026-09-05_lfp-decoders_saturation-impact.png){#fig-saturation .lightbox}\n\n**TS3 Cosmos benchmark, v04 tiers.** `small` decodes regions as well as v03 mild at 0.33× its size, and lowering α\nkeeps improving region decoding, unlike behaviour decoding, which saturates at `default`. The uncompressed signal\nsets the ceiling: 0.621 accuracy, 0.551 CV accuracy. Of the v03 tiers only mild was scored on TS3, rescored from its existing channel predictions on the current eval build (3222 units, up from 3209,\nso its 2026-09-04 single-run score of 0.584 / 0.416 is not directly comparable). The uncompressed features were\nextracted on Popeye from the Cadzow checkpoints (`2026-08_lfp-decoders`, same saturation-avoided grid; 2 insertions\ndiffer by a few snippets) and trained locally with the same recipe, seeds, folds and channel table as the other tiers.\n\n::: {#tbl-ts3-v04 .cell tbl-cap='TS3 Cosmos region classification per lfpack tier: mean ± s.e.m. over 3 model seeds (43/44/45), 3222 eval units. CV accuracy (ranking metric): 5-fold PID-grouped held-out accuracy on the 1054 training PIDs (~330k channels). Eval: 3222 TS3 eval units, a small set. 1/CR: file / uncompressed float32 at 250 Hz (1955.7 GB over 1099 PIDs).' execution_count=6}\n\n::: {.cell-output .cell-output-display execution_count=6}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>α</th>\n      <th>file (GB)</th>\n      <th>1/CR</th>\n      <th>file / v03 mild</th>\n      <th>CV accuracy</th>\n      <th>eval accuracy</th>\n      <th>eval macro F1</th>\n    </tr>\n    <tr>\n      <th>tier</th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>v03-mild</th>\n      <td>14</td>\n      <td>34.2</td>\n      <td>1.75%</td>\n      <td>1.00</td>\n      <td>0.513 ± 0.000</td>\n      <td>0.572 ± 0.004</td>\n      <td>0.438 ± 0.008</td>\n    </tr>\n    <tr>\n      <th>v04-small</th>\n      <td>14</td>\n      <td>11.2</td>\n      <td>0.57%</td>\n      <td>0.33</td>\n      <td>0.518 ± 0.000</td>\n      <td>0.576 ± 0.003</td>\n      <td>0.444 ± 0.003</td>\n    </tr>\n    <tr>\n      <th>v04-default</th>\n      <td>7</td>\n      <td>21.5</td>\n      <td>1.10%</td>\n      <td>0.63</td>\n      <td>0.538 ± 0.001</td>\n      <td>0.580 ± 0.001</td>\n      <td>0.513 ± 0.005</td>\n    </tr>\n    <tr>\n      <th>v04-fine</th>\n      <td>2.5</td>\n      <td>46.1</td>\n      <td>2.36%</td>\n      <td>1.35</td>\n      <td>0.544 ± 0.001</td>\n      <td>0.593 ± 0.006</td>\n      <td>0.489 ± 0.006</td>\n    </tr>\n    <tr>\n      <th>uncompressed</th>\n      <td>—</td>\n      <td>1955.7</td>\n      <td>100.00%</td>\n      <td>57.18</td>\n      <td>0.551 ± 0.001</td>\n      <td>0.621 ± 0.005</td>\n      <td>0.476 ± 0.003</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n::: {#tbl-ts3-v04-classes .cell tbl-cap='Per-class F1 (mean over 3 seeds) for the classes whose F1 moves by more than 0.05 across tiers (MB, 0.69–0.71, is left out). n: eval units per class.' execution_count=7}\n\n::: {.cell-output .cell-output-display execution_count=7}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th>tier</th>\n      <th>n</th>\n      <th>v03-mild</th>\n      <th>v04-small</th>\n      <th>v04-default</th>\n      <th>v04-fine</th>\n      <th>uncompressed</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>CB</th>\n      <td>162</td>\n      <td>0.303</td>\n      <td>0.331</td>\n      <td>0.570</td>\n      <td>0.660</td>\n      <td>0.634</td>\n    </tr>\n    <tr>\n      <th>CNU</th>\n      <td>187</td>\n      <td>0.415</td>\n      <td>0.411</td>\n      <td>0.465</td>\n      <td>0.501</td>\n      <td>0.601</td>\n    </tr>\n    <tr>\n      <th>CTXsp</th>\n      <td>48</td>\n      <td>0.071</td>\n      <td>0.037</td>\n      <td>0.202</td>\n      <td>0.108</td>\n      <td>0.021</td>\n    </tr>\n    <tr>\n      <th>HB</th>\n      <td>218</td>\n      <td>0.503</td>\n      <td>0.496</td>\n      <td>0.519</td>\n      <td>0.578</td>\n      <td>0.424</td>\n    </tr>\n    <tr>\n      <th>HPF</th>\n      <td>323</td>\n      <td>0.591</td>\n      <td>0.592</td>\n      <td>0.533</td>\n      <td>0.510</td>\n      <td>0.633</td>\n    </tr>\n    <tr>\n      <th>HY</th>\n      <td>54</td>\n      <td>0.271</td>\n      <td>0.315</td>\n      <td>0.568</td>\n      <td>0.159</td>\n      <td>0.000</td>\n    </tr>\n    <tr>\n      <th>Isocortex</th>\n      <td>578</td>\n      <td>0.594</td>\n      <td>0.592</td>\n      <td>0.613</td>\n      <td>0.688</td>\n      <td>0.661</td>\n    </tr>\n    <tr>\n      <th>OLF</th>\n      <td>265</td>\n      <td>0.247</td>\n      <td>0.276</td>\n      <td>0.340</td>\n      <td>0.404</td>\n      <td>0.404</td>\n    </tr>\n    <tr>\n      <th>TH</th>\n      <td>690</td>\n      <td>0.691</td>\n      <td>0.695</td>\n      <td>0.623</td>\n      <td>0.577</td>\n      <td>0.722</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n- **Equal α, smaller file: no loss.** v04 `small` against v03 mild (both α = 14; format 2 and a shared basis instead of\n  format 1 and per-chunk U): accuracy 0.576 vs 0.572, macro F1 0.444 vs 0.438, CV accuracy 0.518 vs 0.513. Every\n  per-class F1 agrees within noise. Region decoding, like behaviour decoding, depends on α and not on the codec\n  layout.\n- **Lower α helps region decoding.** CV accuracy rises monotonically, 0.518 → 0.538 → 0.544 (α = 14 → 7 → 2.5), and so\n  does eval accuracy, 0.576 → 0.580 → 0.593. Isocortex, CB, OLF and HB gain the most; TH and HPF lose 0.1 F1, so lower\n  α also shifts which regions get predicted.\n- **Eval macro F1 peaks at `default`** (0.513 vs `fine`'s 0.489), almost entirely from HY (0.57 vs 0.16, 54 units) and\n  CTXsp (48 units). With classes that small, from 29 sessions, macro F1 is noisy; CV accuracy (330k channels) is the\n  more reliable ranking.\n- **Distance to uncompressed.** Eval accuracy 0.572 (v03 mild) → 0.593 (`fine`) → 0.621 (uncompressed); CV accuracy\n  0.513 → 0.544 → 0.551. `fine` closes 82 % of the mild-to-uncompressed gap on CV accuracy (the more reliable\n  measure) and 43 % on eval accuracy, so some region information is still lost at α = 2.5 on the TS3 units.\n\n## Discussion\n\n- **Usefulness.** `small` (0.82 % of float32, 11.2 GB for 1099 insertions) decodes behaviour and brain region as\n  well as v03 mild, which was 3× larger. `fine` (3.1 %, 46.1 GB) recovers the uncompressed behaviour scores and, for\n  regions, most of the CV accuracy (0.544 vs 0.551 uncompressed), though not the TS3 eval accuracy (0.593 vs 0.621). `default` sits between and is the safe general-purpose tier.\n- **Why α.** Format 2 and the shared basis are lossless or neutral for decoding; ε beyond 70 buys nothing; the wavelet\n  threshold α is the one parameter that moves what a downstream analysis sees, and region decoding is more sensitive\n  to it than behaviour decoding.\n- **SNR is a poor proxy.** int8 coefficients cost < 0.12 dB yet hurt wheel decoding on most probes; `aggressive` v03\n  looked acceptable by RMSE and cost feedback and region accuracy.\n- **Limits.** Behaviour decoding is on 11 insertions with large between-insertion spread, and dab512bd behaves\n  unlike the rest. TS3 differences between compressed tiers are 1–2 pp on 3222 units and 3 seeds; the 330k-channel CV ranking is\n  the more reliable one. The sweep decodes in-memory reconstructions of the benchmark checkpoints (2 Hz highpass),\n  whereas the production archives use a 0.5 Hz corner; the insertion galleries re-encode the same checkpoints with the\n  real format-2 codec for that reason.\n\n## Appendix\n\n### v03 tier search on behaviour decoding (retired tiers)\n\nThe v03 tiers were chosen on a 42-cell grid, ε ∈ {50, 100, 150, 250, 300, 350, 450} × α ∈ {14, 28, 40, 55, 75, 96},\ndecoded on the same 11 insertions (14.8 h of LFP). Findings: α alone reliably costs feedback accuracy (paired Wilcoxon,\nα 28 → 96 at ε = 150: 10/11 insertions, p = 0.005); ε alone buys no compression and its apparent decoding cost is not\ndistinguishable from between-insertion noise (150 → 450: 6/11, p = 0.17); real compression appears only when both are\npushed (ε = 450, α = 96 nearly halves the file, 0.211 → 0.098 GB, and costs the most). The aggressive tier was retired\nand default / mild were kept until v04 (@fig-grid-heatmaps to @fig-recap).\n\n::: {.callout-note collapse=\"true\" appearance=\"minimal\"}\n## Grid heatmaps, Pareto and size by ε\n\n![Mean decode metrics and realized CR over the full (ε, α) grid. Uncompressed is a literal (ε = 0, α = 0) corner cell. Mild, default and aggressive cells are outlined (green / red / orange).](figures/2026-09-05_grid_heatmaps.png){#fig-grid-heatmaps .lightbox}\n\n![Decoding metrics grouped by ε (hue = α) as each insertion's own delta from its default (150, 28) cell.](figures/2026-09-01_grid_boxplots_by_epsilon.png){#fig-grid-boxplots .lightbox}\n\n![Total compressed size grouped by ε (hue = α), log scale, with the uncompressed total (20.4 GB) for scale.](figures/2026-09-01_grid_barplot_size_by_epsilon.png){#fig-grid-size .lightbox}\n\n![Realized CR vs retained decode fraction (chance-corrected for choice and feedback), one panel per target. Mild (green plus), default (red star) and aggressive (orange X) are labelled.](figures/2026-09-05_grid_pareto.png){#fig-grid-pareto .lightbox}\n\n![Diagonal sweep (ε and α scaled together, default → aggressive): wheel R², choice / feedback accuracy and total file size.](figures/2026-08-31_diagonal_sweep_decoding_summary.png){#fig-diagonal .lightbox}\n\n![Median channel-averaged PSD along the diagonal sweep; the high-frequency roll-off tracks decoding cost.](figures/2026-08-31_diagonal_sweep_psd.png){#fig-diagonal-psd .lightbox}\n\n![Per-insertion wheel R² (uncompressed, mild, default, aggressive) against the shuffled null.](figures/2026-09-05_lfp-compression-decoding_r2-by-pid.png){#fig-r2-by-pid .lightbox}\n\n![Choice and feedback balanced accuracy per tier. Dashed: chance.](figures/2026-09-05_lfp-compression-decoding_categorical_boxplot.png){#fig-categorical .lightbox}\n\n![Numeric recap of the v03 region decoding: accuracy mean / SD / min / max across folds per source × snippet mode.](figures/2026-09-05_lfp-decoders_recap-table.png){#fig-recap .lightbox}\n:::\n\n::: {.callout-note collapse=\"true\" appearance=\"minimal\"}\n## ε × α reconstruction gallery (dab512bd, v03 grid)\n\n![SVD-ε × WP-α reconstruction gallery for dab512bd. Rows: ε ∈ {150, 300, 450, 750}; columns: α ∈ {0, 12, 24, 32, 48, 64, 96}. Each cell labels rank, CR, RMSE and SNR.](figures/2026-06-12_adaptive_wp_gallery_dab512bd-a02d-4c1f-8dbc-9155a163efc0.png){#fig-gallery .lightbox}\n\n![Residual gallery (original − reconstruction), same layout and colour scale. Residuals stay spatially incoherent up to ε = 750, α = 96.](figures/2026-06-12_adaptive_wp_gallery_dab512bd-a02d-4c1f-8dbc-9155a163efc0_residual.png){#fig-gallery-resid .lightbox}\n\n![CSD of the same reconstructions (colour scale: 99th percentile of the original CSD). CSD is more sensitive to spatial smearing than the LFP.](figures/2026-06-12_adaptive_wp_gallery_csd_dab512bd-a02d-4c1f-8dbc-9155a163efc0.png){#fig-gallery-csd .lightbox}\n:::\n\n::: {.callout-note collapse=\"true\" appearance=\"minimal\"}\n## Transform methods and gap-based rank (discarded)\n\nSVD, wavelet packets, DCT, DCT-δ, STFT and SVD+WP were compared on the 11 insertions; SVD and SVD+WP dominate at every\nCR.\n\n![Initial aggregate benchmark (11 insertions) including all transform methods.](figures/2026-06-06_compression_aggregate.png){#fig-transforms .lightbox}\n\nA rank criterion on the largest singular-value ratio $s_i / s_{i+1}$ was discarded: after Cadzow the ratio at rank 1 is\nonly 1.3–2.4, with no clean signal / noise gap, so it barely tracks compression.\n\n![Gap ratio $s_k / s_{k+1}$ at each rank for the 11 insertions; reference lines at 2, 5, 10.](figures/2026-06-10_gap_vs_rank.png){#fig-gap .lightbox}\n:::\n\n### Code\n\n- Codec and sweeps: `shared_basis_sweep.py`, `pareto_sweep.py`, `plot_pareto.py`, `compression_benchmark.py`,\n  `svd_adaptive_wp.py` in `oliche-quarto/analyses/2026-06-lfp-compression-svd/`; this page's new figures:\n  `plot_v04_insertions.py`, `plot_decoding_tiers.py`.\n- v03 behaviour decoding: dated `2026-08-31_LFP_compression_*.py` / `2026-09-05_LFP_compression_*add_mild.py` under\n  `~/Documents/ibldevtools/olivier/`.\n- Region decoding on the atlas: `sdsc-slurms/2026-08_lfp-decoders/` (`extract.py`, `aggregate.py`,\n  `train_classifier.py`, `report.py`); archive annotations from `sdsc-slurms/2026-06-lfpack/attach_ibl_metadata.py`.\n- TS3: `~/Documents/ibldevtools/olivier/2026-09-04_ts3-lfp-baseline/` (`LFPACK_TIER` in `paths.py`; `score_tiers.py`\n  writes `2026-10-02_ts3_all_tiers_region_decoding.csv`; the uncompressed tier is `LFPACK_TIER=uncompressed`, fed by\n  the Popeye features). v04 archives are built with\n  `sdsc-slurms/2026-06-lfpack/compress.py`.\n\n",
    "supporting": [
      "index_files/figure-html"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}