<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Olivier Winter">
<meta name="dcterms.date" content="2026-08-31">
<meta name="description" content="Does lossy LFP compression degrade downstream decoding of behaviour, and what should we ship instead of the current aggressive tier? Wheel speed, choice and feedback decoded across 11 benchmark recordings under three compression sweeps.">

<title>LFP Compression: Decoding-Aware Tuning – Analysis Hub</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-acf12a64177840b8d86f2d4f01b2e9fb.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-997f3bee8414e4416227c4bdeef383f8.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="../../site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="../../site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="../../site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Analysis Hub</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Analyses</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/oliche"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#overview" id="toc-overview" class="nav-link active" data-scroll-target="#overview">Overview</a></li>
  <li><a href="#method" id="toc-method" class="nav-link" data-scroll-target="#method">Method</a></li>
  <li><a href="#does-compression-hurt-decoding" id="toc-does-compression-hurt-decoding" class="nav-link" data-scroll-target="#does-compression-hurt-decoding">Does compression hurt decoding?</a></li>
  <li><a href="#searching-for-an-intermediate-tier" id="toc-searching-for-an-intermediate-tier" class="nav-link" data-scroll-target="#searching-for-an-intermediate-tier">Searching for an intermediate tier</a></li>
  <li><a href="#full-2d-grid" id="toc-full-2d-grid" class="nav-link" data-scroll-target="#full-2d-grid">Full 2D grid</a></li>
  <li><a href="#recommendation" id="toc-recommendation" class="nav-link" data-scroll-target="#recommendation">Recommendation</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">LFP Compression: Decoding-Aware Tuning</h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
  <div class="quarto-categories">
    <div class="quarto-category">electrophysiology</div>
    <div class="quarto-category">LFP</div>
    <div class="quarto-category">compression</div>
    <div class="quarto-category">Neuropixels</div>
    <div class="quarto-category">decoding</div>
  </div>
  </div>

<div>
  <div class="description">
    Does lossy LFP compression degrade downstream decoding of behaviour, and what should we ship instead of the current aggressive tier? Wheel speed, choice and feedback decoded across 11 benchmark recordings under three compression sweeps.
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Olivier Winter </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">August 31, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="overview" class="level2">
<h2 class="anchored" data-anchor-id="overview">Overview</h2>
<p>The <a href="../../analyses/2026-06-lfp-compression-svd/index.html">SVD/WP compression benchmark</a> calibrates ε and α against <strong>RMSE and SNR</strong> — a spatial/amplitude fidelity proxy that says nothing about whether the <em>information</em> downstream analyses use survives compression. This page checks that directly, by decoding wheel speed, choice and feedback from LFP band-power envelopes across the 11 benchmark recordings, then uses the result to search for a better operating point than the current two-tier design.</p>
<p><strong>lfpack’s codec is two independent stages, applied in sequence</strong> (<code>compress()</code> in <code>packages/lfpack/src/lfpack/_core.py</code>):</p>
<ol type="1">
<li><strong>SVD stage — ε only.</strong> Rank <code>r = #{k : sv[k] &gt; ε·σ₀}</code> is fixed from the raw singular-value spectrum before α is used at all. ε alone decides how many spatial components survive.</li>
<li><strong>WP (wavelet-packet) stage — α only.</strong> Each of the <code>r</code> surviving components is wavelet-packet compressed with threshold <code>τ_k = α·σ₀/sv[k]</code>. α alone decides how much fine temporal/high-frequency detail survives <em>within</em> those components.</li>
</ol>
<p>They’re not fully independent in effect, though: <code>τ_k</code> is normalized by <code>sv[k]</code>, and which singular values survive to be thresholded is exactly what ε controls — so a given α lands differently depending on ε’s choice of surviving components. This turns out to matter a lot below.</p>
<p><strong>Bottom line:</strong> the shipped aggressive tier (ε=450, α=96) measurably hurts decoding — feedback especially — with no warning from RMSE. Neither parameter is a usable lever on its own: α alone reliably costs decoding fidelity (confirmed with a paired test below) without buying real compression, and ε alone buys no compression either, nor — once properly tested — does it reliably cost decoding at all. Real compression only appears when both are pushed together, and a full 42-cell (ε, α) grid (mild through aggressive) now maps that trade-off directly. <strong>Recommendation: retire the aggressive tier; keep default (ε=150, α=28) as standard; ε=450, α=28 is the best non-dominated upgrade if more compression is required.</strong></p>
</section>
<section id="method" class="level2">
<h2 class="anchored" data-anchor-id="method">Method</h2>
<p>Band-power envelope features (log Hilbert amplitude, delta/theta/beta/gamma, 96 channels after 4:1 spatial binning), computed identically for every compression tier from the same Cadzow-denoised checkpoint (<code>lf_resampled_car_cadzow.npy</code>), decoded with:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Target</th>
<th>Feature window</th>
<th>Decoder</th>
<th>Metric</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>|wheel velocity|</td>
<td>continuous, 50 ms bins</td>
<td>RidgeCV, 5-fold chronological CV</td>
<td>R²</td>
</tr>
<tr class="even">
<td>choice</td>
<td>[-0.2, 0) s rel. <code>firstMovement_times</code></td>
<td>Standardized LogisticRegressionCV, 5-fold stratified CV</td>
<td>balanced accuracy</td>
</tr>
<tr class="odd">
<td>feedback</td>
<td>[0, 0.2) s rel. <code>feedback_times</code></td>
<td>same</td>
<td>balanced accuracy</td>
</tr>
</tbody>
</table>
<p>Null: a simple per-fold label/target shuffle — not a pseudo-session control, so it understates single-recording significance, but it’s held identical across tiers, which is what matters for a <em>relative</em> compression-effect comparison. Sample times (t0 is <code>nan</code> on these benchmark files) are reconstructed via <code>SpikeSortingLoader.timesprobe2times</code>.</p>
</section>
<section id="does-compression-hurt-decoding" class="level2">
<h2 class="anchored" data-anchor-id="does-compression-hurt-decoding">Does compression hurt decoding?</h2>
<div id="4ca9f9b7" class="cell" data-execution_count="1">
<div class="cell-output cell-output-display" data-execution_count="1">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th colspan="2" data-quarto-table-cell-role="th" data-halign="left">r2_wheel</th>
<th colspan="2" data-quarto-table-cell-role="th" data-halign="left">balanced_accuracy_choice</th>
<th colspan="2" data-quarto-table-cell-role="th" data-halign="left">balanced_accuracy_feedback</th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">mean</th>
<th data-quarto-table-cell-role="th">median</th>
<th data-quarto-table-cell-role="th">mean</th>
<th data-quarto-table-cell-role="th">median</th>
<th data-quarto-table-cell-role="th">mean</th>
<th data-quarto-table-cell-role="th">median</th>
</tr>
<tr class="header">
<th data-quarto-table-cell-role="th">tier</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">uncompressed</th>
<td>0.139</td>
<td>0.134</td>
<td>0.564</td>
<td>0.546</td>
<td>0.642</td>
<td>0.568</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">alpha28 (default)</th>
<td>0.127</td>
<td>0.133</td>
<td>0.563</td>
<td>0.533</td>
<td>0.597</td>
<td>0.542</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">aggressive (eps450, alpha96, shipped)</th>
<td>0.104</td>
<td>0.084</td>
<td>0.552</td>
<td>0.509</td>
<td>0.557</td>
<td>0.508</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="figures/2026-08-31_lfp-compression-decoding_r2-by-pid.png" class="lightbox" data-gallery="quarto-lightbox-gallery-1" title="Wheel-speed decoding R² per recording, vs shuffled null (black ticks)."><img src="figures/2026-08-31_lfp-compression-decoding_r2-by-pid.png" class="img-fluid figure-img" alt="Wheel-speed decoding R² per recording, vs shuffled null (black ticks)."></a></p>
<figcaption>Wheel-speed decoding R² per recording, vs shuffled null (black ticks).</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="figures/2026-08-31_lfp-compression-decoding_categorical_boxplot.png" class="lightbox" data-gallery="quarto-lightbox-gallery-2" title="Choice / feedback balanced accuracy per recording, one box per tier. Dashed line = chance."><img src="figures/2026-08-31_lfp-compression-decoding_categorical_boxplot.png" class="img-fluid figure-img" alt="Choice / feedback balanced accuracy per recording, one box per tier. Dashed line = chance."></a></p>
<figcaption>Choice / feedback balanced accuracy per recording, one box per tier. Dashed line = chance.</figcaption>
</figure>
</div>
<p>Default tracks uncompressed closely on every target. Aggressive erodes all three, feedback most severely (mean 0.642 → 0.557), because it’s decoded from a brief post-event window — exactly the fast, phasic structure the WP stage’s per-coefficient threshold removes first (small-magnitude coefficients are discarded before large ones, and fine time-scale structure is where LFP wavelet coefficients tend to be smallest). Wheel speed, a slower band-power average, is the least affected.</p>
</section>
<section id="searching-for-an-intermediate-tier" class="level2">
<h2 class="anchored" data-anchor-id="searching-for-an-intermediate-tier">Searching for an intermediate tier</h2>
<p>Sweeping <strong>ε alone</strong> (α=28 fixed, ε ∈ 150–450) or <strong>α alone</strong> (ε=150 fixed, α ∈ 28–96) both left total file size across the 11 recordings essentially flat (0.242 GB → ~0.21 GB either way, an ~13% reduction). But their effect on decoding fidelity is <em>not</em> symmetric, and the raw per- recording numbers are easy to misread here: feedback balanced accuracy varies enormously between recordings (SD ≈0.11 at a single grid cell — some recordings decode feedback near chance, others above 0.8), which swamps both parameters’ effects unless it’s controlled for. A paired per-recording test (same 11 recordings, before vs.&nbsp;after moving one parameter) shows they’re not equivalent: moving <strong>α</strong> from 28→96 (ε=150 fixed) drops feedback balanced accuracy in <strong>10/11 recordings</strong> (Wilcoxon p=0.005) — a real, consistent effect. Moving <strong>ε</strong> from 150→450 (α=28 fixed) only drops it in 6/11 (p=0.17) — <strong>not distinguishable from between-recording noise</strong>, and driven almost entirely by two strong-feedback-decoding recordings rather than a general effect. So: α alone reliably costs decoding fidelity without buying compression; ε alone buys no compression either, but its apparent decoding cost mostly isn’t real. Yet at ε=450, moving α from 28→96 — the shipped aggressive tier vs.&nbsp;the same ε at default’s α — <em>nearly halves</em> the file size (0.211 GB → 0.098 GB): the ε/α interaction described above, in action. Real compression only appears when both are pushed together.</p>
<div id="ef30ed5b" class="cell" data-execution_count="2">
<div class="cell-output cell-output-display" data-execution_count="2">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">r2_wheel</th>
<th data-quarto-table-cell-role="th">balanced_accuracy_choice</th>
<th data-quarto-table-cell-role="th">balanced_accuracy_feedback</th>
<th data-quarto-table-cell-role="th">cr_realized</th>
<th data-quarto-table-cell-role="th">total_GB</th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">tier</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">uncompressed</th>
<td>0.139</td>
<td>0.564</td>
<td>0.642</td>
<td>1.000</td>
<td>20.402</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">alpha28 (default)</th>
<td>0.127</td>
<td>0.563</td>
<td>0.597</td>
<td>86.679</td>
<td>0.242</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">eps250/alpha50</th>
<td>0.117</td>
<td>0.552</td>
<td>0.575</td>
<td>103.736</td>
<td>0.201</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">eps350/alpha75</th>
<td>0.109</td>
<td>0.549</td>
<td>0.558</td>
<td>128.251</td>
<td>0.163</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">aggressive (eps450, alpha96, shipped)</th>
<td>0.104</td>
<td>0.552</td>
<td>0.557</td>
<td>217.478</td>
<td>0.098</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="figures/2026-08-31_diagonal_sweep_decoding_summary.png" class="lightbox" data-gallery="quarto-lightbox-gallery-3" title="Diagonal sweep (ε and α scaled together, default → shipped aggressive): wheel R², choice/feedback balanced accuracy, and total file size (realized CR labelled), 11 recordings."><img src="figures/2026-08-31_diagonal_sweep_decoding_summary.png" class="img-fluid figure-img" alt="Diagonal sweep (ε and α scaled together, default → shipped aggressive): wheel R², choice/feedback balanced accuracy, and total file size (realized CR labelled), 11 recordings."></a></p>
<figcaption>Diagonal sweep (ε and α scaled together, default → shipped aggressive): wheel R², choice/feedback balanced accuracy, and total file size (realized CR labelled), 11 recordings.</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="figures/2026-08-31_diagonal_sweep_psd.png" class="lightbox" data-gallery="quarto-lightbox-gallery-4" title="Median channel-averaged PSD, diagonal sweep — cleanly ordered by compression level; the high-frequency roll-off tracks decoding cost directly."><img src="figures/2026-08-31_diagonal_sweep_psd.png" class="img-fluid figure-img" alt="Median channel-averaged PSD, diagonal sweep — cleanly ordered by compression level; the high-frequency roll-off tracks decoding cost directly."></a></p>
<figcaption>Median channel-averaged PSD, diagonal sweep — cleanly ordered by compression level; the high-frequency roll-off tracks decoding cost directly.</figcaption>
</figure>
</div>
<p>Realized CR climbs steadily (87×→104×→128×→217×) as feedback retention falls in step (0.688→0.530→0.410→0.402) — <strong>no free knee</strong>: every step away from default costs real fidelity immediately. <code>eps350/alpha75</code> is dominated by the shipped aggressive tier (almost the same feedback cost, barely half the compression) — not worth using. This diagonal only sampled the line between two points, though — the full grid below covers the surface.</p>
</section>
<section id="full-2d-grid" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="full-2d-grid">Full 2D grid</h2>
<p>ε ∈ {50, 100, 150, 250, 300, 350, 450} × α ∈ {14, 28, 40, 55, 75, 96} — 42 cells (milder than default through the shipped aggressive point), all three decode targets, across the same 11 benchmark recordings used throughout this page — 14.8 h of LFP in total.</p>
<div id="555bc1e3" class="cell" data-execution_count="3">
<div class="cell-output cell-output-display" data-execution_count="3">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">r2_wheel</th>
<th data-quarto-table-cell-role="th">balanced_accuracy_choice</th>
<th data-quarto-table-cell-role="th">balanced_accuracy_feedback</th>
<th data-quarto-table-cell-role="th">cr_realized</th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">epsilon</th>
<th data-quarto-table-cell-role="th">alpha</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th rowspan="6" data-quarto-table-cell-role="th" data-valign="top">50.0</th>
<th data-quarto-table-cell-role="th">14.0</th>
<td>0.134</td>
<td>0.557</td>
<td>0.628</td>
<td>38.476</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">28.0</th>
<td>0.127</td>
<td>0.563</td>
<td>0.595</td>
<td>47.945</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">40.0</th>
<td>0.122</td>
<td>0.559</td>
<td>0.584</td>
<td>51.625</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">55.0</th>
<td>0.116</td>
<td>0.553</td>
<td>0.569</td>
<td>54.057</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">75.0</th>
<td>0.110</td>
<td>0.549</td>
<td>0.559</td>
<td>56.123</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">96.0</th>
<td>0.104</td>
<td>0.552</td>
<td>0.555</td>
<td>57.458</td>
</tr>
<tr class="odd">
<th rowspan="6" data-quarto-table-cell-role="th" data-valign="top">100.0</th>
<th data-quarto-table-cell-role="th">14.0</th>
<td>0.134</td>
<td>0.556</td>
<td>0.626</td>
<td>48.228</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">28.0</th>
<td>0.127</td>
<td>0.562</td>
<td>0.595</td>
<td>64.020</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">40.0</th>
<td>0.122</td>
<td>0.559</td>
<td>0.584</td>
<td>70.683</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">55.0</th>
<td>0.116</td>
<td>0.553</td>
<td>0.569</td>
<td>75.292</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">75.0</th>
<td>0.110</td>
<td>0.549</td>
<td>0.559</td>
<td>79.255</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">96.0</th>
<td>0.104</td>
<td>0.552</td>
<td>0.555</td>
<td>81.882</td>
</tr>
<tr class="odd">
<th rowspan="6" data-quarto-table-cell-role="th" data-valign="top">150.0</th>
<th data-quarto-table-cell-role="th">14.0</th>
<td>0.133</td>
<td>0.558</td>
<td>0.623</td>
<td>53.483</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">28.0</th>
<td>0.127</td>
<td>0.563</td>
<td>0.597</td>
<td>86.679</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">40.0</th>
<td>0.122</td>
<td>0.560</td>
<td>0.584</td>
<td>82.420</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">55.0</th>
<td>0.116</td>
<td>0.553</td>
<td>0.569</td>
<td>88.756</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">75.0</th>
<td>0.110</td>
<td>0.549</td>
<td>0.559</td>
<td>94.279</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">96.0</th>
<td>0.104</td>
<td>0.552</td>
<td>0.555</td>
<td>97.974</td>
</tr>
<tr class="odd">
<th rowspan="6" data-quarto-table-cell-role="th" data-valign="top">250.0</th>
<th data-quarto-table-cell-role="th">14.0</th>
<td>0.131</td>
<td>0.554</td>
<td>0.615</td>
<td>59.972</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">28.0</th>
<td>0.125</td>
<td>0.559</td>
<td>0.589</td>
<td>85.213</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">40.0</th>
<td>0.121</td>
<td>0.559</td>
<td>0.581</td>
<td>97.263</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">55.0</th>
<td>0.115</td>
<td>0.552</td>
<td>0.568</td>
<td>106.184</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">75.0</th>
<td>0.109</td>
<td>0.550</td>
<td>0.557</td>
<td>114.185</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">96.0</th>
<td>0.104</td>
<td>0.552</td>
<td>0.554</td>
<td>119.582</td>
</tr>
<tr class="odd">
<th rowspan="6" data-quarto-table-cell-role="th" data-valign="top">300.0</th>
<th data-quarto-table-cell-role="th">14.0</th>
<td>0.131</td>
<td>0.555</td>
<td>0.611</td>
<td>62.484</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">28.0</th>
<td>0.124</td>
<td>0.563</td>
<td>0.591</td>
<td>89.387</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">40.0</th>
<td>0.120</td>
<td>0.560</td>
<td>0.582</td>
<td>102.596</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">55.0</th>
<td>0.115</td>
<td>0.554</td>
<td>0.569</td>
<td>112.573</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">75.0</th>
<td>0.109</td>
<td>0.549</td>
<td>0.560</td>
<td>121.583</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">96.0</th>
<td>0.104</td>
<td>0.552</td>
<td>0.556</td>
<td>127.672</td>
</tr>
<tr class="odd">
<th rowspan="6" data-quarto-table-cell-role="th" data-valign="top">350.0</th>
<th data-quarto-table-cell-role="th">14.0</th>
<td>0.130</td>
<td>0.557</td>
<td>0.596</td>
<td>64.939</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">28.0</th>
<td>0.124</td>
<td>0.557</td>
<td>0.586</td>
<td>93.133</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">40.0</th>
<td>0.120</td>
<td>0.562</td>
<td>0.580</td>
<td>107.362</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">55.0</th>
<td>0.114</td>
<td>0.552</td>
<td>0.569</td>
<td>118.304</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">75.0</th>
<td>0.109</td>
<td>0.549</td>
<td>0.558</td>
<td>128.251</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">96.0</th>
<td>0.104</td>
<td>0.551</td>
<td>0.555</td>
<td>134.987</td>
</tr>
<tr class="odd">
<th rowspan="6" data-quarto-table-cell-role="th" data-valign="top">450.0</th>
<th data-quarto-table-cell-role="th">14.0</th>
<td>0.127</td>
<td>0.556</td>
<td>0.594</td>
<td>69.960</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">28.0</th>
<td>0.122</td>
<td>0.555</td>
<td>0.585</td>
<td>99.948</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">40.0</th>
<td>0.119</td>
<td>0.561</td>
<td>0.578</td>
<td>115.902</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">55.0</th>
<td>0.114</td>
<td>0.548</td>
<td>0.568</td>
<td>128.589</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">75.0</th>
<td>0.109</td>
<td>0.549</td>
<td>0.559</td>
<td>140.247</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">96.0</th>
<td>0.104</td>
<td>0.552</td>
<td>0.557</td>
<td>217.478</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="figures/2026-09-01_grid_heatmaps.png" class="lightbox" data-gallery="quarto-lightbox-gallery-5" title="Mean decode metrics and realized CR over the full (ε, α) grid. Uncompressed is added as a literal (ε=0, α=0) corner cell; the rest of that extra row/column is left blank. Default and aggressive cells are outlined (red / orange)."><img src="figures/2026-09-01_grid_heatmaps.png" class="img-fluid figure-img" alt="Mean decode metrics and realized CR over the full (ε, α) grid. Uncompressed is added as a literal (ε=0, α=0) corner cell; the rest of that extra row/column is left blank. Default and aggressive cells are outlined (red / orange)."></a></p>
<figcaption>Mean decode metrics and realized CR over the full (ε, α) grid. Uncompressed is added as a literal (ε=0, α=0) corner cell; the rest of that extra row/column is left blank. Default and aggressive cells are outlined (red / orange).</figcaption>
</figure>
</div>
<p>The heatmaps make the asymmetry from the previous section visible directly: wheel and feedback both shift clearly moving <em>across</em> alpha (columns) but barely at all moving <em>down</em> epsilon (rows) — until the (450, 96) corner, which stands out as a clear outlier in the CR panel (217× vs.&nbsp;140× and 135× in its immediate neighbors), the interaction in action. The corner cells also show plainly how close default’s decode metrics already sit to uncompressed (0.127 vs.&nbsp;0.139 wheel R², 0.597 vs.&nbsp;0.642 feedback), and how far realized CR has to climb from uncompressed’s 1×.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="figures/2026-09-01_grid_boxplots_by_epsilon.png" class="lightbox" data-gallery="quarto-lightbox-gallery-6" title="Decoding metrics grouped by epsilon (hue = alpha), plotted as each recording’s own delta from its default (150,28) cell — this removes the ~0.11 SD between-recording offset that hides the effect in raw values. Uncompressed (blue dash-dot line) is each recording’s own delta between its uncompressed and default scores, since it doesn’t sit at any (ε, α) x-position."><img src="figures/2026-09-01_grid_boxplots_by_epsilon.png" class="img-fluid figure-img" alt="Decoding metrics grouped by epsilon (hue = alpha), plotted as each recording’s own delta from its default (150,28) cell — this removes the ~0.11 SD between-recording offset that hides the effect in raw values. Uncompressed (blue dash-dot line) is each recording’s own delta between its uncompressed and default scores, since it doesn’t sit at any (ε, α) x-position."></a></p>
<figcaption>Decoding metrics grouped by epsilon (hue = alpha), plotted as each recording’s own delta from its default (150,28) cell — this removes the ~0.11 SD between-recording offset that hides the effect in raw values. Uncompressed (blue dash-dot line) is each recording’s own delta between its uncompressed and default scores, since it doesn’t sit at any (ε, α) x-position.</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="figures/2026-09-01_grid_barplot_size_by_epsilon.png" class="lightbox" data-gallery="quarto-lightbox-gallery-7" title="Total compressed size grouped by epsilon (hue = alpha), log scale, with the uncompressed total (20.4 GB, blue dash-dot line) for scale — every tested tier is at least ~40× smaller — and a secondary axis converting size directly to realized CR. The (450,96) bar is visibly shorter than its neighbors, again the interaction."><img src="figures/2026-09-01_grid_barplot_size_by_epsilon.png" class="img-fluid figure-img" alt="Total compressed size grouped by epsilon (hue = alpha), log scale, with the uncompressed total (20.4 GB, blue dash-dot line) for scale — every tested tier is at least ~40× smaller — and a secondary axis converting size directly to realized CR. The (450,96) bar is visibly shorter than its neighbors, again the interaction."></a></p>
<figcaption>Total compressed size grouped by epsilon (hue = alpha), log scale, with the uncompressed total (20.4 GB, blue dash-dot line) for scale — every tested tier is at least ~40× smaller — and a secondary axis converting size directly to realized CR. The (450,96) bar is visibly shorter than its neighbors, again the interaction.</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="figures/2026-09-01_grid_barplot_size_by_epsilon_linear.png" class="lightbox" data-gallery="quarto-lightbox-gallery-8" title="Same, linear scale (bars stay honestly zero-based; the uncompressed line is dropped here since at 20.4 GB it would flatten every bar to an invisible sliver) — makes the actual size differences between adjacent cells easier to judge than the log version above."><img src="figures/2026-09-01_grid_barplot_size_by_epsilon_linear.png" class="img-fluid figure-img" alt="Same, linear scale (bars stay honestly zero-based; the uncompressed line is dropped here since at 20.4 GB it would flatten every bar to an invisible sliver) — makes the actual size differences between adjacent cells easier to judge than the log version above."></a></p>
<figcaption>Same, linear scale (bars stay honestly zero-based; the uncompressed line is dropped here since at 20.4 GB it would flatten every bar to an invisible sliver) — makes the actual size differences between adjacent cells easier to judge than the log version above.</figcaption>
</figure>
</div>
<p><strong>Retained fraction</strong> (below) is how much of the uncompressed decode a tier keeps: for wheel, <code>R²(tier) / R²(uncompressed)</code>; for choice/feedback, <code>(balanced_accuracy(tier) - 0.5) / (balanced_accuracy(uncompressed) - 0.5)</code> — chance-corrected, since balanced accuracy’s floor is 0.5, not 0. 1.0 means indistinguishable from uncompressed.</p>
<div class="page-columns page-full">
<div class="quarto-figure quarto-figure-center page-columns page-full">
<figure class="figure page-columns page-full">
<p class="page-columns page-full"><a href="figures/2026-09-01_grid_pareto.png" class="lightbox page-columns page-full" data-gallery="quarto-lightbox-gallery-9" title="Pareto: realized CR vs.&nbsp;retained decode fraction, one panel per target (marker size = alpha, colour = epsilon). Default (red star) sits on the frontier for wheel and near it for feedback."><img src="figures/2026-09-01_grid_pareto.png" class="img-fluid figure-img column-page" alt="Pareto: realized CR vs.&nbsp;retained decode fraction, one panel per target (marker size = alpha, colour = epsilon). Default (red star) sits on the frontier for wheel and near it for feedback."></a></p>
<figcaption>Pareto: realized CR vs.&nbsp;retained decode fraction, one panel per target (marker size = alpha, colour = epsilon). Default (red star) sits on the frontier for wheel and near it for feedback.</figcaption>
</figure>
</div>
</div>
<p><strong>The true Pareto frontier</strong> (cells where no other cell has both higher realized CR and higher retained feedback) contains 16 of the 42 cells, and default (150, 28) is on it — nothing dominates it. Stepping along the frontier past default is a real, gradual trade the whole way: (300, 28) barely improves CR (89× vs.&nbsp;87×) for a real feedback cost (retained fraction 0.640 vs.&nbsp;0.688); (350, 28) and (450, 28) are close together and both meaningfully better value — (450, 28) reaches 100× for retained fraction 0.603, a small further cost over (350, 28)’s 93×/0.605 for real extra compression. Past that, the frontier only continues by also raising α, which is where the interaction — and the larger feedback cost — kicks in.</p>
</section>
<section id="recommendation" class="level2">
<h2 class="anchored" data-anchor-id="recommendation">Recommendation</h2>
<ul>
<li><strong>Keep default (ε=150, α=28)</strong> as the standard cohort-wide tier — it’s Pareto-efficient, and every tested alternative trades away real feedback fidelity.</li>
<li><strong>If more compression is required, use ε=450, α=28</strong> — 100× realized CR (0.211 GB vs. default’s 0.242 GB across the 11 recordings, both tiny next to uncompressed’s 20.4 GB), R² 0.122 vs.&nbsp;default’s 0.127, feedback balanced accuracy 0.585 vs.&nbsp;default’s 0.597. That feedback gap is not statistically distinguishable from between-recording noise (paired Wilcoxon p=0.17) — the best-value, lowest-risk upgrade found on the whole grid.</li>
<li><strong>Retire the aggressive tier (ε=450, α=96).</strong> Nothing between ε=450/α=28 and aggressive is worth shipping — the frontier only gets there by also raising α, which is where the real, significant decoding cost (p=0.005) lives.</li>
<li><strong>Worth knowing:</strong> the α=14 row (any ε) gives noticeably <em>better</em> feedback retention than default (up to 0.90) at a real storage cost (38–70× vs.&nbsp;default’s 87×) — an option if a future use case needs to beat default’s fidelity rather than just approach it.</li>
<li><strong>Build command</strong> (per-recording, ≈10–60 s from the existing Cadzow checkpoint, no re-download needed): <code>lfpack.compress_to_h5(cadzow_npy, out_h5, recording=pid, epsilon=450.0, alpha=28.0, fs=250.0, ...)</code>.</li>
</ul>


<!-- -->

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "LFP Compression: Decoding-Aware Tuning"</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="an">description:</span><span class="co"> "Does lossy LFP compression degrade downstream decoding of behaviour, and what should we ship instead of the current aggressive tier? Wheel speed, choice and feedback decoded across 11 benchmark recordings under three compression sweeps."</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> "2026-08-31"</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> "Olivier Winter"</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="an">categories:</span><span class="co"> [electrophysiology, LFP, compression, Neuropixels, decoding]</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">## Overview</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>The <span class="co">[</span><span class="ot">SVD/WP compression benchmark</span><span class="co">](index.qmd)</span> calibrates ε and α against **RMSE and SNR** — a</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>spatial/amplitude fidelity proxy that says nothing about whether the *information* downstream</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>analyses use survives compression. This page checks that directly, by decoding wheel speed,</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>choice and feedback from LFP band-power envelopes across the 11 benchmark recordings, then uses</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>the result to search for a better operating point than the current two-tier design.</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>**lfpack's codec is two independent stages, applied in sequence** (<span class="in">`compress()`</span> in</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a><span class="in">`packages/lfpack/src/lfpack/_core.py`</span>):</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>**SVD stage — ε only.** Rank <span class="in">`r = #{k : sv[k] &gt; ε·σ₀}`</span> is fixed from the raw singular-value</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>   spectrum before α is used at all. ε alone decides how many spatial components survive.</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>**WP (wavelet-packet) stage — α only.** Each of the <span class="in">`r`</span> surviving components is</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>   wavelet-packet compressed with threshold <span class="in">`τ_k = α·σ₀/sv[k]`</span>. α alone decides how much fine</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>   temporal/high-frequency detail survives *within* those components.</span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>They're not fully independent in effect, though: <span class="in">`τ_k`</span> is normalized by <span class="in">`sv[k]`</span>, and which</span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>singular values survive to be thresholded is exactly what ε controls — so a given α lands</span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>differently depending on ε's choice of surviving components. This turns out to matter a lot</span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a>below.</span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a>**Bottom line:** the shipped aggressive tier (ε=450, α=96) measurably hurts decoding — feedback</span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a>especially — with no warning from RMSE. Neither parameter is a usable lever on its own: α alone</span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a>reliably costs decoding fidelity (confirmed with a paired test below) without buying real</span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a>compression, and ε alone buys no compression either, nor — once properly tested — does it</span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a>reliably cost decoding at all. Real compression only appears when both are pushed together,</span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a>and a full 42-cell (ε, α) grid (mild through aggressive) now maps that trade-off directly.</span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a>**Recommendation: retire the aggressive tier; keep default (ε=150, α=28) as standard; ε=450,</span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a>α=28 is the best non-dominated upgrade if more compression is required.**</span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a><span class="fu">## Method</span></span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a>Band-power envelope features (log Hilbert amplitude, delta/theta/beta/gamma, 96 channels after</span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a>4:1 spatial binning), computed identically for every compression tier from the same</span>
<span id="cb1-44"><a href="#cb1-44" aria-hidden="true" tabindex="-1"></a>Cadzow-denoised checkpoint (<span class="in">`lf_resampled_car_cadzow.npy`</span>), decoded with:</span>
<span id="cb1-45"><a href="#cb1-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-46"><a href="#cb1-46" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Target <span class="pp">|</span> Feature window <span class="pp">|</span> Decoder <span class="pp">|</span> Metric <span class="pp">|</span></span>
<span id="cb1-47"><a href="#cb1-47" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---|---|---|</span></span>
<span id="cb1-48"><a href="#cb1-48" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="sc">\|</span>wheel velocity<span class="sc">\|</span> <span class="pp">|</span> continuous, 50 ms bins <span class="pp">|</span> RidgeCV, 5-fold chronological CV <span class="pp">|</span> R² <span class="pp">|</span></span>
<span id="cb1-49"><a href="#cb1-49" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> choice <span class="pp">|</span> [-0.2, 0) s rel. <span class="in">`firstMovement_times`</span> <span class="pp">|</span> Standardized LogisticRegressionCV, 5-fold stratified CV <span class="pp">|</span> balanced accuracy <span class="pp">|</span></span>
<span id="cb1-50"><a href="#cb1-50" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> feedback <span class="pp">|</span> [0, 0.2) s rel. <span class="in">`feedback_times`</span> <span class="pp">|</span> same <span class="pp">|</span> balanced accuracy <span class="pp">|</span></span>
<span id="cb1-51"><a href="#cb1-51" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-52"><a href="#cb1-52" aria-hidden="true" tabindex="-1"></a>Null: a simple per-fold label/target shuffle — not a pseudo-session control, so it understates</span>
<span id="cb1-53"><a href="#cb1-53" aria-hidden="true" tabindex="-1"></a>single-recording significance, but it's held identical across tiers, which is what matters for</span>
<span id="cb1-54"><a href="#cb1-54" aria-hidden="true" tabindex="-1"></a>a *relative* compression-effect comparison. Sample times (t0 is <span class="in">`nan`</span> on these benchmark files)</span>
<span id="cb1-55"><a href="#cb1-55" aria-hidden="true" tabindex="-1"></a>are reconstructed via <span class="in">`SpikeSortingLoader.timesprobe2times`</span>.</span>
<span id="cb1-56"><a href="#cb1-56" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-57"><a href="#cb1-57" aria-hidden="true" tabindex="-1"></a><span class="fu">## Does compression hurt decoding?</span></span>
<span id="cb1-58"><a href="#cb1-58" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-61"><a href="#cb1-61" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb1-62"><a href="#cb1-62" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb1-63"><a href="#cb1-63" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-64"><a href="#cb1-64" aria-hidden="true" tabindex="-1"></a>m <span class="op">=</span> pd.read_csv(<span class="st">"2026-08-31_compression_tuning_metrics.csv"</span>)</span>
<span id="cb1-65"><a href="#cb1-65" aria-hidden="true" tabindex="-1"></a>base_order <span class="op">=</span> [<span class="st">"uncompressed"</span>, <span class="st">"alpha28 (default)"</span>, <span class="st">"aggressive (eps450, alpha96, shipped)"</span>]</span>
<span id="cb1-66"><a href="#cb1-66" aria-hidden="true" tabindex="-1"></a>m.groupby(<span class="st">"tier"</span>)[[<span class="st">"r2_wheel"</span>, <span class="st">"balanced_accuracy_choice"</span>, <span class="st">"balanced_accuracy_feedback"</span>]].agg([<span class="st">"mean"</span>, <span class="st">"median"</span>]).loc[base_order].<span class="bu">round</span>(<span class="dv">3</span>)</span>
<span id="cb1-67"><a href="#cb1-67" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-68"><a href="#cb1-68" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-69"><a href="#cb1-69" aria-hidden="true" tabindex="-1"></a><span class="al">![Wheel-speed decoding R² per recording, vs shuffled null (black ticks).](figures/2026-08-31_lfp-compression-decoding_r2-by-pid.png)</span>{.lightbox}</span>
<span id="cb1-70"><a href="#cb1-70" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-71"><a href="#cb1-71" aria-hidden="true" tabindex="-1"></a><span class="al">![Choice / feedback balanced accuracy per recording, one box per tier. Dashed line = chance.](figures/2026-08-31_lfp-compression-decoding_categorical_boxplot.png)</span>{.lightbox}</span>
<span id="cb1-72"><a href="#cb1-72" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-73"><a href="#cb1-73" aria-hidden="true" tabindex="-1"></a>Default tracks uncompressed closely on every target. Aggressive erodes all three, feedback most</span>
<span id="cb1-74"><a href="#cb1-74" aria-hidden="true" tabindex="-1"></a>severely (mean 0.642 → 0.557), because it's decoded from a brief post-event window — exactly</span>
<span id="cb1-75"><a href="#cb1-75" aria-hidden="true" tabindex="-1"></a>the fast, phasic structure the WP stage's per-coefficient threshold removes first (small-magnitude</span>
<span id="cb1-76"><a href="#cb1-76" aria-hidden="true" tabindex="-1"></a>coefficients are discarded before large ones, and fine time-scale structure is where LFP</span>
<span id="cb1-77"><a href="#cb1-77" aria-hidden="true" tabindex="-1"></a>wavelet coefficients tend to be smallest). Wheel speed, a slower band-power average, is the</span>
<span id="cb1-78"><a href="#cb1-78" aria-hidden="true" tabindex="-1"></a>least affected.</span>
<span id="cb1-79"><a href="#cb1-79" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-80"><a href="#cb1-80" aria-hidden="true" tabindex="-1"></a><span class="fu">## Searching for an intermediate tier</span></span>
<span id="cb1-81"><a href="#cb1-81" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-82"><a href="#cb1-82" aria-hidden="true" tabindex="-1"></a>Sweeping **ε alone** (α=28 fixed, ε ∈ 150–450) or **α alone** (ε=150 fixed, α ∈ 28–96) both left</span>
<span id="cb1-83"><a href="#cb1-83" aria-hidden="true" tabindex="-1"></a>total file size across the 11 recordings essentially flat (0.242 GB → ~0.21 GB either way, an</span>
<span id="cb1-84"><a href="#cb1-84" aria-hidden="true" tabindex="-1"></a>~13% reduction). But their effect on decoding fidelity is *not* symmetric, and the raw per-</span>
<span id="cb1-85"><a href="#cb1-85" aria-hidden="true" tabindex="-1"></a>recording numbers are easy to misread here: feedback balanced accuracy varies enormously</span>
<span id="cb1-86"><a href="#cb1-86" aria-hidden="true" tabindex="-1"></a>between recordings (SD ≈0.11 at a single grid cell — some recordings decode feedback near</span>
<span id="cb1-87"><a href="#cb1-87" aria-hidden="true" tabindex="-1"></a>chance, others above 0.8), which swamps both parameters' effects unless it's controlled for. A</span>
<span id="cb1-88"><a href="#cb1-88" aria-hidden="true" tabindex="-1"></a>paired per-recording test (same 11 recordings, before vs. after moving one parameter) shows</span>
<span id="cb1-89"><a href="#cb1-89" aria-hidden="true" tabindex="-1"></a>they're not equivalent: moving **α** from 28→96 (ε=150 fixed) drops feedback balanced accuracy</span>
<span id="cb1-90"><a href="#cb1-90" aria-hidden="true" tabindex="-1"></a>in **10/11 recordings** (Wilcoxon p=0.005) — a real, consistent effect. Moving **ε** from</span>
<span id="cb1-91"><a href="#cb1-91" aria-hidden="true" tabindex="-1"></a>150→450 (α=28 fixed) only drops it in 6/11 (p=0.17) — **not distinguishable from</span>
<span id="cb1-92"><a href="#cb1-92" aria-hidden="true" tabindex="-1"></a>between-recording noise**, and driven almost entirely by two strong-feedback-decoding</span>
<span id="cb1-93"><a href="#cb1-93" aria-hidden="true" tabindex="-1"></a>recordings rather than a general effect. So: α alone reliably costs decoding fidelity without</span>
<span id="cb1-94"><a href="#cb1-94" aria-hidden="true" tabindex="-1"></a>buying compression; ε alone buys no compression either, but its apparent decoding cost mostly</span>
<span id="cb1-95"><a href="#cb1-95" aria-hidden="true" tabindex="-1"></a>isn't real. Yet at ε=450, moving α from 28→96 — the shipped aggressive tier vs. the same ε at</span>
<span id="cb1-96"><a href="#cb1-96" aria-hidden="true" tabindex="-1"></a>default's α — *nearly halves* the file size (0.211 GB → 0.098 GB): the ε/α interaction</span>
<span id="cb1-97"><a href="#cb1-97" aria-hidden="true" tabindex="-1"></a>described above, in action. Real compression only appears when both are pushed together.</span>
<span id="cb1-98"><a href="#cb1-98" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-101"><a href="#cb1-101" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb1-102"><a href="#cb1-102" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb1-103"><a href="#cb1-103" aria-hidden="true" tabindex="-1"></a>diag_order <span class="op">=</span> [<span class="st">"uncompressed"</span>, <span class="st">"alpha28 (default)"</span>, <span class="st">"eps250/alpha50"</span>, <span class="st">"eps350/alpha75"</span>,</span>
<span id="cb1-104"><a href="#cb1-104" aria-hidden="true" tabindex="-1"></a>              <span class="st">"aggressive (eps450, alpha96, shipped)"</span>]</span>
<span id="cb1-105"><a href="#cb1-105" aria-hidden="true" tabindex="-1"></a>tbl <span class="op">=</span> m.groupby(<span class="st">"tier"</span>)[[<span class="st">"r2_wheel"</span>, <span class="st">"balanced_accuracy_choice"</span>, <span class="st">"balanced_accuracy_feedback"</span>, <span class="st">"cr_realized"</span>]].mean().loc[diag_order]</span>
<span id="cb1-106"><a href="#cb1-106" aria-hidden="true" tabindex="-1"></a>tbl[<span class="st">"total_GB"</span>] <span class="op">=</span> m.groupby(<span class="st">"tier"</span>)[<span class="st">"file_bytes"</span>].<span class="bu">sum</span>().loc[diag_order] <span class="op">/</span> <span class="fl">1e9</span></span>
<span id="cb1-107"><a href="#cb1-107" aria-hidden="true" tabindex="-1"></a>tbl.<span class="bu">round</span>(<span class="dv">3</span>)</span>
<span id="cb1-108"><a href="#cb1-108" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-109"><a href="#cb1-109" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-110"><a href="#cb1-110" aria-hidden="true" tabindex="-1"></a><span class="al">![Diagonal sweep (ε and α scaled together, default → shipped aggressive): wheel R², choice/feedback balanced accuracy, and total file size (realized CR labelled), 11 recordings.](figures/2026-08-31_diagonal_sweep_decoding_summary.png)</span>{.lightbox}</span>
<span id="cb1-111"><a href="#cb1-111" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-112"><a href="#cb1-112" aria-hidden="true" tabindex="-1"></a><span class="al">![Median channel-averaged PSD, diagonal sweep — cleanly ordered by compression level; the high-frequency roll-off tracks decoding cost directly.](figures/2026-08-31_diagonal_sweep_psd.png)</span>{.lightbox}</span>
<span id="cb1-113"><a href="#cb1-113" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-114"><a href="#cb1-114" aria-hidden="true" tabindex="-1"></a>Realized CR climbs steadily (87×→104×→128×→217×) as feedback retention falls in step</span>
<span id="cb1-115"><a href="#cb1-115" aria-hidden="true" tabindex="-1"></a>(0.688→0.530→0.410→0.402) — **no free knee**: every step away from default costs real fidelity</span>
<span id="cb1-116"><a href="#cb1-116" aria-hidden="true" tabindex="-1"></a>immediately. <span class="in">`eps350/alpha75`</span> is dominated by the shipped aggressive tier (almost the same</span>
<span id="cb1-117"><a href="#cb1-117" aria-hidden="true" tabindex="-1"></a>feedback cost, barely half the compression) — not worth using. This diagonal only sampled the</span>
<span id="cb1-118"><a href="#cb1-118" aria-hidden="true" tabindex="-1"></a>line between two points, though — the full grid below covers the surface.</span>
<span id="cb1-119"><a href="#cb1-119" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-120"><a href="#cb1-120" aria-hidden="true" tabindex="-1"></a><span class="fu">## Full 2D grid</span></span>
<span id="cb1-121"><a href="#cb1-121" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-122"><a href="#cb1-122" aria-hidden="true" tabindex="-1"></a>ε ∈ {50, 100, 150, 250, 300, 350, 450} × α ∈ {14, 28, 40, 55, 75, 96} — 42 cells (milder than</span>
<span id="cb1-123"><a href="#cb1-123" aria-hidden="true" tabindex="-1"></a>default through the shipped aggressive point), all three decode targets, across the same 11</span>
<span id="cb1-124"><a href="#cb1-124" aria-hidden="true" tabindex="-1"></a>benchmark recordings used throughout this page — 14.8 h of LFP in total.</span>
<span id="cb1-125"><a href="#cb1-125" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-128"><a href="#cb1-128" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb1-129"><a href="#cb1-129" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb1-130"><a href="#cb1-130" aria-hidden="true" tabindex="-1"></a>g <span class="op">=</span> pd.read_csv(<span class="st">"2026-09-01_full_grid_metrics.csv"</span>)</span>
<span id="cb1-131"><a href="#cb1-131" aria-hidden="true" tabindex="-1"></a>grid <span class="op">=</span> g.dropna(subset<span class="op">=</span>[<span class="st">"epsilon"</span>])</span>
<span id="cb1-132"><a href="#cb1-132" aria-hidden="true" tabindex="-1"></a>grid.groupby([<span class="st">"epsilon"</span>, <span class="st">"alpha"</span>])[[<span class="st">"r2_wheel"</span>, <span class="st">"balanced_accuracy_choice"</span>,</span>
<span id="cb1-133"><a href="#cb1-133" aria-hidden="true" tabindex="-1"></a>                                     <span class="st">"balanced_accuracy_feedback"</span>, <span class="st">"cr_realized"</span>]].mean().<span class="bu">round</span>(<span class="dv">3</span>)</span>
<span id="cb1-134"><a href="#cb1-134" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-135"><a href="#cb1-135" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-136"><a href="#cb1-136" aria-hidden="true" tabindex="-1"></a><span class="al">![Mean decode metrics and realized CR over the full (ε, α) grid. Uncompressed is added as a literal (ε=0, α=0) corner cell; the rest of that extra row/column is left blank. Default and aggressive cells are outlined (red / orange).](figures/2026-09-01_grid_heatmaps.png)</span>{.lightbox}</span>
<span id="cb1-137"><a href="#cb1-137" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-138"><a href="#cb1-138" aria-hidden="true" tabindex="-1"></a>The heatmaps make the asymmetry from the previous section visible directly: wheel and feedback</span>
<span id="cb1-139"><a href="#cb1-139" aria-hidden="true" tabindex="-1"></a>both shift clearly moving *across* alpha (columns) but barely at all moving *down* epsilon</span>
<span id="cb1-140"><a href="#cb1-140" aria-hidden="true" tabindex="-1"></a>(rows) — until the (450, 96) corner, which stands out as a clear outlier in the CR panel (217×</span>
<span id="cb1-141"><a href="#cb1-141" aria-hidden="true" tabindex="-1"></a>vs. 140× and 135× in its immediate neighbors), the interaction in action. The corner cells also</span>
<span id="cb1-142"><a href="#cb1-142" aria-hidden="true" tabindex="-1"></a>show plainly how close default's decode metrics already sit to uncompressed (0.127 vs. 0.139</span>
<span id="cb1-143"><a href="#cb1-143" aria-hidden="true" tabindex="-1"></a>wheel R², 0.597 vs. 0.642 feedback), and how far realized CR has to climb from uncompressed's 1×.</span>
<span id="cb1-144"><a href="#cb1-144" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-145"><a href="#cb1-145" aria-hidden="true" tabindex="-1"></a><span class="al">![Decoding metrics grouped by epsilon (hue = alpha), plotted as each recording's own delta from its default (150,28) cell — this removes the ~0.11 SD between-recording offset that hides the effect in raw values. Uncompressed (blue dash-dot line) is each recording's own delta between its uncompressed and default scores, since it doesn't sit at any (ε, α) x-position.](figures/2026-09-01_grid_boxplots_by_epsilon.png)</span>{.lightbox}</span>
<span id="cb1-146"><a href="#cb1-146" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-147"><a href="#cb1-147" aria-hidden="true" tabindex="-1"></a><span class="al">![Total compressed size grouped by epsilon (hue = alpha), log scale, with the uncompressed total (20.4 GB, blue dash-dot line) for scale — every tested tier is at least ~40× smaller — and a secondary axis converting size directly to realized CR. The (450,96) bar is visibly shorter than its neighbors, again the interaction.](figures/2026-09-01_grid_barplot_size_by_epsilon.png)</span>{.lightbox}</span>
<span id="cb1-148"><a href="#cb1-148" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-149"><a href="#cb1-149" aria-hidden="true" tabindex="-1"></a><span class="al">![Same, linear scale (bars stay honestly zero-based; the uncompressed line is dropped here since at 20.4 GB it would flatten every bar to an invisible sliver) — makes the actual size differences between adjacent cells easier to judge than the log version above.](figures/2026-09-01_grid_barplot_size_by_epsilon_linear.png)</span>{.lightbox}</span>
<span id="cb1-150"><a href="#cb1-150" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-151"><a href="#cb1-151" aria-hidden="true" tabindex="-1"></a>**Retained fraction** (below) is how much of the uncompressed decode a tier keeps: for wheel,</span>
<span id="cb1-152"><a href="#cb1-152" aria-hidden="true" tabindex="-1"></a><span class="in">`R²(tier) / R²(uncompressed)`</span>; for choice/feedback, `(balanced_accuracy(tier) - 0.5) /</span>
<span id="cb1-153"><a href="#cb1-153" aria-hidden="true" tabindex="-1"></a>(balanced_accuracy(uncompressed) - 0.5)` — chance-corrected, since balanced accuracy's floor is</span>
<span id="cb1-154"><a href="#cb1-154" aria-hidden="true" tabindex="-1"></a>0.5, not 0. 1.0 means indistinguishable from uncompressed.</span>
<span id="cb1-155"><a href="#cb1-155" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-156"><a href="#cb1-156" aria-hidden="true" tabindex="-1"></a>::: {.column-page}</span>
<span id="cb1-157"><a href="#cb1-157" aria-hidden="true" tabindex="-1"></a><span class="al">![Pareto: realized CR vs. retained decode fraction, one panel per target (marker size = alpha, colour = epsilon). Default (red star) sits on the frontier for wheel and near it for feedback.](figures/2026-09-01_grid_pareto.png)</span>{.lightbox}</span>
<span id="cb1-158"><a href="#cb1-158" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-159"><a href="#cb1-159" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-160"><a href="#cb1-160" aria-hidden="true" tabindex="-1"></a>**The true Pareto frontier** (cells where no other cell has both higher realized CR and higher</span>
<span id="cb1-161"><a href="#cb1-161" aria-hidden="true" tabindex="-1"></a>retained feedback) contains 16 of the 42 cells, and default (150, 28) is on it — nothing</span>
<span id="cb1-162"><a href="#cb1-162" aria-hidden="true" tabindex="-1"></a>dominates it. Stepping along the frontier past default is a real, gradual trade the whole way:</span>
<span id="cb1-163"><a href="#cb1-163" aria-hidden="true" tabindex="-1"></a>(300, 28) barely improves CR (89× vs. 87×) for a real feedback cost (retained fraction</span>
<span id="cb1-164"><a href="#cb1-164" aria-hidden="true" tabindex="-1"></a>0.640 vs. 0.688); (350, 28) and (450, 28) are close together and both meaningfully better value</span>
<span id="cb1-165"><a href="#cb1-165" aria-hidden="true" tabindex="-1"></a>— (450, 28) reaches 100× for retained fraction 0.603, a small further cost over (350, 28)'s</span>
<span id="cb1-166"><a href="#cb1-166" aria-hidden="true" tabindex="-1"></a>93×/0.605 for real extra compression. Past that, the frontier only continues by also raising α,</span>
<span id="cb1-167"><a href="#cb1-167" aria-hidden="true" tabindex="-1"></a>which is where the interaction — and the larger feedback cost — kicks in.</span>
<span id="cb1-168"><a href="#cb1-168" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-169"><a href="#cb1-169" aria-hidden="true" tabindex="-1"></a><span class="fu">## Recommendation</span></span>
<span id="cb1-170"><a href="#cb1-170" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-171"><a href="#cb1-171" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Keep default (ε=150, α=28)** as the standard cohort-wide tier — it's Pareto-efficient, and</span>
<span id="cb1-172"><a href="#cb1-172" aria-hidden="true" tabindex="-1"></a>  every tested alternative trades away real feedback fidelity.</span>
<span id="cb1-173"><a href="#cb1-173" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**If more compression is required, use ε=450, α=28** — 100× realized CR (0.211 GB vs.</span>
<span id="cb1-174"><a href="#cb1-174" aria-hidden="true" tabindex="-1"></a>  default's 0.242 GB across the 11 recordings, both tiny next to uncompressed's 20.4 GB), R²</span>
<span id="cb1-175"><a href="#cb1-175" aria-hidden="true" tabindex="-1"></a>  0.122 vs. default's 0.127, feedback balanced accuracy 0.585 vs. default's 0.597. That</span>
<span id="cb1-176"><a href="#cb1-176" aria-hidden="true" tabindex="-1"></a>  feedback gap is not statistically distinguishable from between-recording noise (paired</span>
<span id="cb1-177"><a href="#cb1-177" aria-hidden="true" tabindex="-1"></a>  Wilcoxon p=0.17) — the best-value, lowest-risk upgrade found on the whole grid.</span>
<span id="cb1-178"><a href="#cb1-178" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Retire the aggressive tier (ε=450, α=96).** Nothing between ε=450/α=28 and aggressive is</span>
<span id="cb1-179"><a href="#cb1-179" aria-hidden="true" tabindex="-1"></a>  worth shipping — the frontier only gets there by also raising α, which is where the real,</span>
<span id="cb1-180"><a href="#cb1-180" aria-hidden="true" tabindex="-1"></a>  significant decoding cost (p=0.005) lives.</span>
<span id="cb1-181"><a href="#cb1-181" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Worth knowing:** the α=14 row (any ε) gives noticeably *better* feedback retention than</span>
<span id="cb1-182"><a href="#cb1-182" aria-hidden="true" tabindex="-1"></a>  default (up to 0.90) at a real storage cost (38–70× vs. default's 87×) — an option if a</span>
<span id="cb1-183"><a href="#cb1-183" aria-hidden="true" tabindex="-1"></a>  future use case needs to beat default's fidelity rather than just approach it.</span>
<span id="cb1-184"><a href="#cb1-184" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Build command** (per-recording, ≈10–60 s from the existing Cadzow checkpoint, no</span>
<span id="cb1-185"><a href="#cb1-185" aria-hidden="true" tabindex="-1"></a>  re-download needed): `lfpack.compress_to_h5(cadzow_npy, out_h5, recording=pid, epsilon=450.0,</span>
<span id="cb1-186"><a href="#cb1-186" aria-hidden="true" tabindex="-1"></a>  alpha=28.0, fs=250.0, ...)`.</span>
</code></pre></div><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>Olivier Winter</p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>
<script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","descPosition":"bottom","loop":false,"openEffect":"zoom","selector":".lightbox"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script>




</body></html>