<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Olivier Winter">
<meta name="dcterms.date" content="2026-08-31">
<meta name="description" content="Does lossy LFP compression degrade downstream decoding of behaviour? Wheel speed, choice and feedback decoded from band-power envelopes across 11 benchmark recordings, uncompressed vs default vs aggressive SVD+WP compression.">

<title>LFP Compression: Functional Validation via Neural Decoding – Analysis Hub</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-acf12a64177840b8d86f2d4f01b2e9fb.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-997f3bee8414e4416227c4bdeef383f8.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="../../site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="../../site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="../../site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Analysis Hub</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Analyses</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/oliche"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#overview" id="toc-overview" class="nav-link active" data-scroll-target="#overview">Overview</a></li>
  <li><a href="#method" id="toc-method" class="nav-link" data-scroll-target="#method">Method</a></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results">Results</a>
  <ul class="collapse">
  <li><a href="#continuous-target-wheel-speed" id="toc-continuous-target-wheel-speed" class="nav-link" data-scroll-target="#continuous-target-wheel-speed">Continuous target: wheel speed</a></li>
  <li><a href="#categorical-targets-choice-and-feedback" id="toc-categorical-targets-choice-and-feedback" class="nav-link" data-scroll-target="#categorical-targets-choice-and-feedback">Categorical targets: choice and feedback</a></li>
  </ul></li>
  <li><a href="#interpretation" id="toc-interpretation" class="nav-link" data-scroll-target="#interpretation">Interpretation</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a></li>
  <li><a href="#next-steps" id="toc-next-steps" class="nav-link" data-scroll-target="#next-steps">Next steps</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">LFP Compression: Functional Validation via Neural Decoding</h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
  <div class="quarto-categories">
    <div class="quarto-category">electrophysiology</div>
    <div class="quarto-category">LFP</div>
    <div class="quarto-category">compression</div>
    <div class="quarto-category">Neuropixels</div>
    <div class="quarto-category">decoding</div>
  </div>
  </div>

<div>
  <div class="description">
    Does lossy LFP compression degrade downstream decoding of behaviour? Wheel speed, choice and feedback decoded from band-power envelopes across 11 benchmark recordings, uncompressed vs default vs aggressive SVD+WP compression.
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Olivier Winter </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">August 31, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="overview" class="level2">
<h2 class="anchored" data-anchor-id="overview">Overview</h2>
<p>The <a href="../../analyses/2026-06-lfp-compression-svd/index.html">SVD/WP compression benchmark</a> calibrates ε/α against <strong>RMSE and SNR</strong> — a spatial/amplitude fidelity proxy. That proxy says nothing about whether the <em>information</em> downstream analyses actually use survives compression. This page checks that directly: for each of the same 11 benchmark PIDs, wheel speed, choice and feedback are decoded from LFP band-power envelopes under three variants of the same recording —</p>
<ul>
<li><strong>uncompressed</strong> — <code>lf_resampled_car_cadzow.npy</code> (250 Hz, CAR + Cadzow-denoised, no lossy step)</li>
<li><strong>default</strong> — ε=150, α=28 (CR ≈ 80–130×), the <a href="bwm_release_qc.qmd">shipped BWM release</a> default pass</li>
<li><strong>aggressive</strong> — ε=450, α=96 (CR ≈ 200–430×), the shipped BWM release aggressive pass</li>
</ul>
<p><strong>Bottom line: the default pass tracks the uncompressed baseline closely on every target; the aggressive pass measurably erodes decoding, most severely for feedback.</strong> RMSE/CR alone would not have surfaced this — see <a href="#interpretation">Interpretation</a>.</p>
</section>
<section id="method" class="level2">
<h2 class="anchored" data-anchor-id="method">Method</h2>
<p><strong>Features.</strong> Same pipeline as the pynapple LFP decoding walkthrough (<code>ibldevtools/olivier/2026-08-28_LFP_decoding_pynapple.py</code>): LFP is spatially binned 384→96 channels (sum of 4 adjacent electrodes, matching <code>lfpack</code>’s <code>bin_channels=4</code>), then band-pass filtered (4th-order Butterworth) and Hilbert-enveloped in four bands (delta 1–4 Hz, theta 4–8 Hz, beta 15–30 Hz, gamma 30–90 Hz), log-transformed, and stacked into a 384-dim feature vector (96 channels × 4 bands) per timepoint. Saturated spans are excluded via <code>LFPackReader.saturation_times()</code>.</p>
<p>Sample times for the uncompressed/default/aggressive variants (which predate <code>lfpack</code>’s sync-metadata write, so <code>t0</code> is <code>nan</code>) are reconstructed from the raw probe clock via <code>SpikeSortingLoader.timesprobe2times</code>, using that decimated sample <code>j</code> corresponds to raw LF sample <code>j × Q</code> (Q=10) at 2500 Hz.</p>
<p><strong>Targets and decoders.</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Target</th>
<th>Feature window</th>
<th>Decoder</th>
<th>CV</th>
<th>Metric</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>|wheel velocity|</td>
<td>continuous, 50 ms bins</td>
<td>RidgeCV (α ∈ logspace(-2,4,20))</td>
<td>5-fold chronological</td>
<td>R²</td>
</tr>
<tr class="even">
<td>choice</td>
<td>[-0.2, 0) s rel. <code>firstMovement_times</code>, nogo excluded</td>
<td>Standardized LogisticRegressionCV</td>
<td>5-fold stratified</td>
<td>balanced accuracy</td>
</tr>
<tr class="odd">
<td>feedback</td>
<td>[0, 0.2) s rel. <code>feedback_times</code></td>
<td>Standardized LogisticRegressionCV</td>
<td>5-fold stratified</td>
<td>balanced accuracy</td>
</tr>
</tbody>
</table>
<p><strong>Null.</strong> A simple per-fold label/target shuffle (20 shuffles for the categorical targets). This is <em>not</em> a pseudo-session control — it doesn’t preserve trial-to-trial autocorrelation, so it under-states significance for any single recording. That’s an acceptable trade-off here: the question is the <em>relative</em> effect of compression on the same decode, not whether any one recording’s decode is itself significant, and the null is held identical across all three variants of a given recording/target.</p>
</section>
<section id="results" class="level2">
<h2 class="anchored" data-anchor-id="results">Results</h2>
<section id="continuous-target-wheel-speed" class="level3">
<h3 class="anchored" data-anchor-id="continuous-target-wheel-speed">Continuous target: wheel speed</h3>
<div id="42e8ba56" class="cell" data-execution_count="1">
<div class="cell-output cell-output-display" data-execution_count="1">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">variant</th>
<th data-quarto-table-cell-role="th">uncompressed</th>
<th data-quarto-table-cell-role="th">default</th>
<th data-quarto-table-cell-role="th">aggressive</th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">pid</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">1a276285-8b0e-4cc9-9f0a-a3a002978724</th>
<td>0.134</td>
<td>0.133</td>
<td>0.115</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1e104bf4-7a24-4624-a5b2-c2c8289c0de7</th>
<td>0.054</td>
<td>0.040</td>
<td>0.030</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">6638cfb3-3831-4fc2-9327-194b76cf22e1</th>
<td>0.024</td>
<td>0.043</td>
<td>0.006</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">749cb2b7-e57e-4453-a794-f6230e4d0226</th>
<td>0.054</td>
<td>0.063</td>
<td>0.077</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">d7ec0892-0a6c-4f4f-9d8f-72083692af5c</th>
<td>0.315</td>
<td>0.305</td>
<td>0.236</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">da8dfec1-d265-44e8-84ce-6ae9c109b8bd</th>
<td>0.039</td>
<td>0.031</td>
<td>0.024</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">dab512bd-a02d-4c1f-8dbc-9155a163efc0</th>
<td>0.157</td>
<td>0.169</td>
<td>0.165</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">dc7e9403-19f7-409f-9240-05ee57cb7aea</th>
<td>0.110</td>
<td>0.085</td>
<td>0.063</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">e8f9fba4-d151-4b00-bee7-447f0f3e752c</th>
<td>0.190</td>
<td>0.133</td>
<td>0.084</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">eebcaf65-7fa4-4118-869d-a084e84530e2</th>
<td>0.266</td>
<td>0.220</td>
<td>0.184</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">fe380793-8035-414e-b000-09bfe5ece92a</th>
<td>0.185</td>
<td>0.172</td>
<td>0.162</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Median R² drops only slightly from uncompressed (0.134) through default (0.133) to aggressive (0.084) — the default pass is functionally indistinguishable from uncompressed for this target, and even aggressive stays well above the shuffled null (always negative) in every recording.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="figures/2026-08-31_lfp-compression-decoding_r2-by-pid.png" class="lightbox" data-gallery="quarto-lightbox-gallery-1" title="Wheel-speed decoding R² per recording and compression tier, vs shuffled null (black ticks)."><img src="figures/2026-08-31_lfp-compression-decoding_r2-by-pid.png" class="img-fluid figure-img" alt="Wheel-speed decoding R² per recording and compression tier, vs shuffled null (black ticks)."></a></p>
<figcaption>Wheel-speed decoding R² per recording and compression tier, vs shuffled null (black ticks).</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="figures/2026-08-31_lfp-compression-decoding_r2-boxplot.png" class="lightbox" data-gallery="quarto-lightbox-gallery-2" title="R² distribution across the 11 recordings, one box per compression tier."><img src="figures/2026-08-31_lfp-compression-decoding_r2-boxplot.png" class="img-fluid figure-img" alt="R² distribution across the 11 recordings, one box per compression tier."></a></p>
<figcaption>R² distribution across the 11 recordings, one box per compression tier.</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="figures/2026-08-31_lfp-compression-decoding_wheel-overlay.png" class="lightbox" data-gallery="quarto-lightbox-gallery-3" title="Measured vs decoded |wheel velocity|, 60 s windows, three example recordings. Default and aggressive traces track the uncompressed decode closely; all three miss the sharpest movement peaks."><img src="figures/2026-08-31_lfp-compression-decoding_wheel-overlay.png" class="img-fluid figure-img" alt="Measured vs decoded |wheel velocity|, 60 s windows, three example recordings. Default and aggressive traces track the uncompressed decode closely; all three miss the sharpest movement peaks."></a></p>
<figcaption>Measured vs decoded |wheel velocity|, 60 s windows, three example recordings. Default and aggressive traces track the uncompressed decode closely; all three miss the sharpest movement peaks.</figcaption>
</figure>
</div>
</section>
<section id="categorical-targets-choice-and-feedback" class="level3">
<h3 class="anchored" data-anchor-id="categorical-targets-choice-and-feedback">Categorical targets: choice and feedback</h3>
<div id="3382a1d3" class="cell" data-execution_count="2">
<div class="cell-output cell-output-display" data-execution_count="2">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">target</th>
<th colspan="3" data-quarto-table-cell-role="th" data-halign="left">choice</th>
<th colspan="3" data-quarto-table-cell-role="th" data-halign="left">feedback</th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">variant</th>
<th data-quarto-table-cell-role="th">uncompressed</th>
<th data-quarto-table-cell-role="th">default</th>
<th data-quarto-table-cell-role="th">aggressive</th>
<th data-quarto-table-cell-role="th">uncompressed</th>
<th data-quarto-table-cell-role="th">default</th>
<th data-quarto-table-cell-role="th">aggressive</th>
</tr>
<tr class="header">
<th data-quarto-table-cell-role="th">pid</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">1a276285-8b0e-4cc9-9f0a-a3a002978724</th>
<td>0.506</td>
<td>0.502</td>
<td>0.503</td>
<td>0.568</td>
<td>0.540</td>
<td>0.501</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1e104bf4-7a24-4624-a5b2-c2c8289c0de7</th>
<td>0.541</td>
<td>0.533</td>
<td>0.535</td>
<td>0.562</td>
<td>0.542</td>
<td>0.508</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">6638cfb3-3831-4fc2-9327-194b76cf22e1</th>
<td>0.601</td>
<td>0.575</td>
<td>0.600</td>
<td>0.512</td>
<td>0.514</td>
<td>0.512</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">749cb2b7-e57e-4453-a794-f6230e4d0226</th>
<td>0.500</td>
<td>0.499</td>
<td>0.496</td>
<td>0.597</td>
<td>0.606</td>
<td>0.607</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">d7ec0892-0a6c-4f4f-9d8f-72083692af5c</th>
<td>0.780</td>
<td>0.781</td>
<td>0.751</td>
<td>0.864</td>
<td>0.833</td>
<td>0.745</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">da8dfec1-d265-44e8-84ce-6ae9c109b8bd</th>
<td>0.567</td>
<td>0.586</td>
<td>0.560</td>
<td>0.515</td>
<td>0.498</td>
<td>0.501</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">dab512bd-a02d-4c1f-8dbc-9155a163efc0</th>
<td>0.526</td>
<td>0.529</td>
<td>0.507</td>
<td>0.787</td>
<td>0.636</td>
<td>0.584</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">dc7e9403-19f7-409f-9240-05ee57cb7aea</th>
<td>0.565</td>
<td>0.573</td>
<td>0.509</td>
<td>0.562</td>
<td>0.540</td>
<td>0.500</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">e8f9fba4-d151-4b00-bee7-447f0f3e752c</th>
<td>0.546</td>
<td>0.527</td>
<td>0.509</td>
<td>0.727</td>
<td>0.593</td>
<td>0.507</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">eebcaf65-7fa4-4118-869d-a084e84530e2</th>
<td>0.499</td>
<td>0.500</td>
<td>0.500</td>
<td>0.830</td>
<td>0.769</td>
<td>0.663</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">fe380793-8035-414e-b000-09bfe5ece92a</th>
<td>0.572</td>
<td>0.587</td>
<td>0.600</td>
<td>0.535</td>
<td>0.500</td>
<td>0.500</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="figures/2026-08-31_lfp-compression-decoding_categorical_boxplot.png" class="lightbox" data-gallery="quarto-lightbox-gallery-4" title="Choice / feedback balanced accuracy across the 11 recordings, one box per compression tier. Dashed line = chance."><img src="figures/2026-08-31_lfp-compression-decoding_categorical_boxplot.png" class="img-fluid figure-img" alt="Choice / feedback balanced accuracy across the 11 recordings, one box per compression tier. Dashed line = chance."></a></p>
<figcaption>Choice / feedback balanced accuracy across the 11 recordings, one box per compression tier. Dashed line = chance.</figcaption>
</figure>
</div>
<p>Feedback decoding degrades monotonically and substantially: median balanced accuracy 0.568 (uncompressed) → 0.542 (default) → 0.508 (aggressive) — the aggressive-tier distribution collapses almost entirely to chance. Choice shows the same direction but is weaker throughout (median 0.546 → 0.533 → 0.509) and several recordings are already near chance uncompressed, so there is less to lose. One recording (<code>d7ec0892</code>) decodes both targets strongly and stays well above chance even under aggressive compression (feedback 0.86 → 0.83 → 0.74), showing the effect is a graded erosion, not a hard floor.</p>
</section>
</section>
<section id="interpretation" class="level2">
<h2 class="anchored" data-anchor-id="interpretation">Interpretation</h2>
<p>Feedback — decoded from a brief post-event window — is the target most sensitive to compression; wheel speed — a slower, broadband state variable averaged over 50 ms bins — is the least. This lines up with the WP-stage mechanism described in <a href="../../analyses/2026-06-lfp-compression-svd/index.html#adaptive-wp-threshold-calibration">index.qmd §Adaptive WP threshold calibration</a>: the per-coefficient threshold <code>τ_k = α·σ₀/s_k</code> discards low-magnitude wavelet coefficients first, and fine time-scale (higher-frequency) structure is exactly where LFP wavelet coefficients tend to be smallest. Raising α from 28 (default) to 96 (aggressive) doesn’t just lower CR uniformly — it disproportionately removes the fast, phasic content that a post-event classifier like the feedback decoder depends on, while barely touching the slow band-power fluctuations wheel-speed decoding uses. RMSE, being dominated by the (larger-amplitude) slow components, is largely blind to this — it does not distinguish “lost 5 µV of slow drift” from “lost the phasic transient that carries the feedback signal.”</p>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion">Conclusion</h2>
<p>The default pass (ε=150, α=28) is functionally safe for the decoding uses checked here. The aggressive pass (ε=450, α=96) is not: it measurably degrades wheel-speed decoding and substantially degrades feedback decoding, without a corresponding warning from the RMSE/CR metric it was calibrated on. <strong>Recommendation: retire the current aggressive tier</strong> for any downstream use that touches decoding, and calibrate a new intermediate tier using a decoding-aware objective rather than RMSE alone — see <a href="#next-steps">Next steps</a>.</p>
</section>
<section id="next-steps" class="level2">
<h2 class="anchored" data-anchor-id="next-steps">Next steps</h2>
<p>Proposed approach for calibrating an intermediate tier, not yet run:</p>
<ol type="1">
<li><strong>Change the objective.</strong> Sweep candidate (ε, α) pairs and score each by decoding loss relative to uncompressed (ΔR² for wheel speed, Δbalanced-accuracy for choice/feedback) at a given CR, rather than RMSE. Feedback balanced accuracy is the most sensitive of the three metrics found here, so it should anchor the acceptance criterion (e.g.&nbsp;no more than a fixed fraction of the uncompressed decode retained).</li>
<li><strong>Sweep α more finely than ε.</strong> §Interpretation points at α (the WP stage, which governs how much fine temporal/high-frequency structure survives within each retained SVD component) as the more likely lever for the feedback-decoding cost, not ε (which mainly sets spatial rank). A useful first pass: fix ε at its default 150 and sweep α between 28 and 96 (e.g.&nbsp;{28, 40, 55, 70, 96}), before touching ε at all.</li>
<li><strong>Keep the search cheap.</strong> The full decode (band envelopes + 3 decoders) costs ~10 min/recording/variant, so an 11-PID × full-α-grid sweep is expensive. Run the α sweep on 3–4 recordings chosen to span the observed decodability range (e.g.&nbsp;<code>d7ec0892</code> — strong decoder throughout; <code>1e104bf4</code> or <code>da8dfec1</code> — weak decoder, most likely to show a floor effect; one mid-range recording), then confirm the selected operating point on the full 11-PID benchmark used throughout this page.</li>
<li><strong>Report CR alongside decoding loss, not RMSE alongside decoding loss</strong> — RMSE has already been shown here to miss the effect that matters; keep it as a secondary sanity check rather than the selection criterion.</li>
</ol>


<!-- -->

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "LFP Compression: Functional Validation via Neural Decoding"</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="an">description:</span><span class="co"> "Does lossy LFP compression degrade downstream decoding of behaviour? Wheel speed, choice and feedback decoded from band-power envelopes across 11 benchmark recordings, uncompressed vs default vs aggressive SVD+WP compression."</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> "2026-08-31"</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> "Olivier Winter"</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="an">categories:</span><span class="co"> [electrophysiology, LFP, compression, Neuropixels, decoding]</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">## Overview</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>The <span class="co">[</span><span class="ot">SVD/WP compression benchmark</span><span class="co">](index.qmd)</span> calibrates ε/α against **RMSE and SNR** — a</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>spatial/amplitude fidelity proxy. That proxy says nothing about whether the *information*</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>downstream analyses actually use survives compression. This page checks that directly: for</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>each of the same 11 benchmark PIDs, wheel speed, choice and feedback are decoded from LFP</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>band-power envelopes under three variants of the same recording —</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**uncompressed** — <span class="in">`lf_resampled_car_cadzow.npy`</span> (250 Hz, CAR + Cadzow-denoised, no lossy step)</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**default** — ε=150, α=28 (CR ≈ 80–130×), the <span class="co">[</span><span class="ot">shipped BWM release</span><span class="co">](bwm_release_qc.qmd)</span> default pass</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**aggressive** — ε=450, α=96 (CR ≈ 200–430×), the shipped BWM release aggressive pass</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>**Bottom line: the default pass tracks the uncompressed baseline closely on every target; the</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>aggressive pass measurably erodes decoding, most severely for feedback.** RMSE/CR alone would</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>not have surfaced this — see <span class="co">[</span><span class="ot">Interpretation</span><span class="co">](#interpretation)</span>.</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a><span class="fu">## Method</span></span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>**Features.** Same pipeline as the pynapple LFP decoding walkthrough</span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>(<span class="in">`ibldevtools/olivier/2026-08-28_LFP_decoding_pynapple.py`</span>):</span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a>LFP is spatially binned 384→96 channels (sum of 4 adjacent electrodes, matching <span class="in">`lfpack`</span>'s</span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a><span class="in">`bin_channels=4`</span>), then band-pass filtered (4th-order Butterworth) and Hilbert-enveloped in</span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a>four bands (delta 1–4 Hz, theta 4–8 Hz, beta 15–30 Hz, gamma 30–90 Hz), log-transformed, and</span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a>stacked into a 384-dim feature vector (96 channels × 4 bands) per timepoint. Saturated spans</span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a>are excluded via <span class="in">`LFPackReader.saturation_times()`</span>.</span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a>Sample times for the uncompressed/default/aggressive variants (which predate <span class="in">`lfpack`</span>'s</span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a>sync-metadata write, so <span class="in">`t0`</span> is <span class="in">`nan`</span>) are reconstructed from the raw probe clock via</span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a><span class="in">`SpikeSortingLoader.timesprobe2times`</span>, using that decimated sample <span class="in">`j`</span> corresponds to raw LF</span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a>sample <span class="in">`j × Q`</span> (Q=10) at 2500 Hz.</span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a>**Targets and decoders.**</span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Target <span class="pp">|</span> Feature window <span class="pp">|</span> Decoder <span class="pp">|</span> CV <span class="pp">|</span> Metric <span class="pp">|</span></span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---|---|---|---|</span></span>
<span id="cb1-44"><a href="#cb1-44" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="sc">\|</span>wheel velocity<span class="sc">\|</span> <span class="pp">|</span> continuous, 50 ms bins <span class="pp">|</span> RidgeCV (α ∈ logspace(-2,4,20)) <span class="pp">|</span> 5-fold chronological <span class="pp">|</span> R² <span class="pp">|</span></span>
<span id="cb1-45"><a href="#cb1-45" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> choice <span class="pp">|</span> [-0.2, 0) s rel. <span class="in">`firstMovement_times`</span>, nogo excluded <span class="pp">|</span> Standardized LogisticRegressionCV <span class="pp">|</span> 5-fold stratified <span class="pp">|</span> balanced accuracy <span class="pp">|</span></span>
<span id="cb1-46"><a href="#cb1-46" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> feedback <span class="pp">|</span> [0, 0.2) s rel. <span class="in">`feedback_times`</span> <span class="pp">|</span> Standardized LogisticRegressionCV <span class="pp">|</span> 5-fold stratified <span class="pp">|</span> balanced accuracy <span class="pp">|</span></span>
<span id="cb1-47"><a href="#cb1-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-48"><a href="#cb1-48" aria-hidden="true" tabindex="-1"></a>**Null.** A simple per-fold label/target shuffle (20 shuffles for the categorical targets).</span>
<span id="cb1-49"><a href="#cb1-49" aria-hidden="true" tabindex="-1"></a>This is *not* a pseudo-session control — it doesn't preserve trial-to-trial autocorrelation, so</span>
<span id="cb1-50"><a href="#cb1-50" aria-hidden="true" tabindex="-1"></a>it under-states significance for any single recording. That's an acceptable trade-off here:</span>
<span id="cb1-51"><a href="#cb1-51" aria-hidden="true" tabindex="-1"></a>the question is the *relative* effect of compression on the same decode, not whether any one</span>
<span id="cb1-52"><a href="#cb1-52" aria-hidden="true" tabindex="-1"></a>recording's decode is itself significant, and the null is held identical across all three</span>
<span id="cb1-53"><a href="#cb1-53" aria-hidden="true" tabindex="-1"></a>variants of a given recording/target.</span>
<span id="cb1-54"><a href="#cb1-54" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-55"><a href="#cb1-55" aria-hidden="true" tabindex="-1"></a><span class="fu">## Results</span></span>
<span id="cb1-56"><a href="#cb1-56" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-57"><a href="#cb1-57" aria-hidden="true" tabindex="-1"></a><span class="fu">### Continuous target: wheel speed</span></span>
<span id="cb1-58"><a href="#cb1-58" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-61"><a href="#cb1-61" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb1-62"><a href="#cb1-62" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb1-63"><a href="#cb1-63" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-64"><a href="#cb1-64" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-65"><a href="#cb1-65" aria-hidden="true" tabindex="-1"></a>wheel <span class="op">=</span> pd.read_csv(<span class="st">"2026-08-31_decoding_metrics_wheel.csv"</span>)</span>
<span id="cb1-66"><a href="#cb1-66" aria-hidden="true" tabindex="-1"></a>order <span class="op">=</span> [<span class="st">"uncompressed"</span>, <span class="st">"default"</span>, <span class="st">"aggressive"</span>]</span>
<span id="cb1-67"><a href="#cb1-67" aria-hidden="true" tabindex="-1"></a>wheel.pivot(index<span class="op">=</span><span class="st">"pid"</span>, columns<span class="op">=</span><span class="st">"variant"</span>, values<span class="op">=</span><span class="st">"r2"</span>)[order].<span class="bu">round</span>(<span class="dv">3</span>)</span>
<span id="cb1-68"><a href="#cb1-68" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-69"><a href="#cb1-69" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-70"><a href="#cb1-70" aria-hidden="true" tabindex="-1"></a>Median R² drops only slightly from uncompressed (0.134) through default (0.133) to aggressive</span>
<span id="cb1-71"><a href="#cb1-71" aria-hidden="true" tabindex="-1"></a>(0.084) — the default pass is functionally indistinguishable from uncompressed for this</span>
<span id="cb1-72"><a href="#cb1-72" aria-hidden="true" tabindex="-1"></a>target, and even aggressive stays well above the shuffled null (always negative) in every</span>
<span id="cb1-73"><a href="#cb1-73" aria-hidden="true" tabindex="-1"></a>recording.</span>
<span id="cb1-74"><a href="#cb1-74" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-75"><a href="#cb1-75" aria-hidden="true" tabindex="-1"></a><span class="al">![Wheel-speed decoding R² per recording and compression tier, vs shuffled null (black ticks).](figures/2026-08-31_lfp-compression-decoding_r2-by-pid.png)</span>{.lightbox}</span>
<span id="cb1-76"><a href="#cb1-76" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-77"><a href="#cb1-77" aria-hidden="true" tabindex="-1"></a><span class="al">![R² distribution across the 11 recordings, one box per compression tier.](figures/2026-08-31_lfp-compression-decoding_r2-boxplot.png)</span>{.lightbox}</span>
<span id="cb1-78"><a href="#cb1-78" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-79"><a href="#cb1-79" aria-hidden="true" tabindex="-1"></a><span class="al">![Measured vs decoded \|wheel velocity\|, 60 s windows, three example recordings. Default and aggressive traces track the uncompressed decode closely; all three miss the sharpest movement peaks.](figures/2026-08-31_lfp-compression-decoding_wheel-overlay.png)</span>{.lightbox}</span>
<span id="cb1-80"><a href="#cb1-80" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-81"><a href="#cb1-81" aria-hidden="true" tabindex="-1"></a><span class="fu">### Categorical targets: choice and feedback</span></span>
<span id="cb1-82"><a href="#cb1-82" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-85"><a href="#cb1-85" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb1-86"><a href="#cb1-86" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb1-87"><a href="#cb1-87" aria-hidden="true" tabindex="-1"></a>cat <span class="op">=</span> pd.read_csv(<span class="st">"2026-08-31_decoding_metrics_categorical.csv"</span>)</span>
<span id="cb1-88"><a href="#cb1-88" aria-hidden="true" tabindex="-1"></a>cat.pivot_table(index<span class="op">=</span><span class="st">"pid"</span>, columns<span class="op">=</span>[<span class="st">"target"</span>, <span class="st">"variant"</span>], values<span class="op">=</span><span class="st">"balanced_accuracy"</span>)[</span>
<span id="cb1-89"><a href="#cb1-89" aria-hidden="true" tabindex="-1"></a>    [(t, v) <span class="cf">for</span> t <span class="kw">in</span> [<span class="st">"choice"</span>, <span class="st">"feedback"</span>] <span class="cf">for</span> v <span class="kw">in</span> order]</span>
<span id="cb1-90"><a href="#cb1-90" aria-hidden="true" tabindex="-1"></a>].<span class="bu">round</span>(<span class="dv">3</span>)</span>
<span id="cb1-91"><a href="#cb1-91" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-92"><a href="#cb1-92" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-93"><a href="#cb1-93" aria-hidden="true" tabindex="-1"></a><span class="al">![Choice / feedback balanced accuracy across the 11 recordings, one box per compression tier. Dashed line = chance.](figures/2026-08-31_lfp-compression-decoding_categorical_boxplot.png)</span>{.lightbox}</span>
<span id="cb1-94"><a href="#cb1-94" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-95"><a href="#cb1-95" aria-hidden="true" tabindex="-1"></a>Feedback decoding degrades monotonically and substantially: median balanced accuracy 0.568</span>
<span id="cb1-96"><a href="#cb1-96" aria-hidden="true" tabindex="-1"></a>(uncompressed) → 0.542 (default) → 0.508 (aggressive) — the aggressive-tier distribution</span>
<span id="cb1-97"><a href="#cb1-97" aria-hidden="true" tabindex="-1"></a>collapses almost entirely to chance. Choice shows the same direction but is weaker throughout</span>
<span id="cb1-98"><a href="#cb1-98" aria-hidden="true" tabindex="-1"></a>(median 0.546 → 0.533 → 0.509) and several recordings are already near chance uncompressed, so</span>
<span id="cb1-99"><a href="#cb1-99" aria-hidden="true" tabindex="-1"></a>there is less to lose. One recording (<span class="in">`d7ec0892`</span>) decodes both targets strongly and stays well</span>
<span id="cb1-100"><a href="#cb1-100" aria-hidden="true" tabindex="-1"></a>above chance even under aggressive compression (feedback 0.86 → 0.83 → 0.74), showing the</span>
<span id="cb1-101"><a href="#cb1-101" aria-hidden="true" tabindex="-1"></a>effect is a graded erosion, not a hard floor.</span>
<span id="cb1-102"><a href="#cb1-102" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-103"><a href="#cb1-103" aria-hidden="true" tabindex="-1"></a><span class="fu">## Interpretation {#interpretation}</span></span>
<span id="cb1-104"><a href="#cb1-104" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-105"><a href="#cb1-105" aria-hidden="true" tabindex="-1"></a>Feedback — decoded from a brief post-event window — is the target most sensitive to</span>
<span id="cb1-106"><a href="#cb1-106" aria-hidden="true" tabindex="-1"></a>compression; wheel speed — a slower, broadband state variable averaged over 50 ms bins — is</span>
<span id="cb1-107"><a href="#cb1-107" aria-hidden="true" tabindex="-1"></a>the least. This lines up with the WP-stage mechanism described in</span>
<span id="cb1-108"><a href="#cb1-108" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">index.qmd §Adaptive WP threshold calibration</span><span class="co">](index.qmd#adaptive-wp-threshold-calibration)</span>:</span>
<span id="cb1-109"><a href="#cb1-109" aria-hidden="true" tabindex="-1"></a>the per-coefficient threshold <span class="in">`τ_k = α·σ₀/s_k`</span> discards low-magnitude wavelet coefficients</span>
<span id="cb1-110"><a href="#cb1-110" aria-hidden="true" tabindex="-1"></a>first, and fine time-scale (higher-frequency) structure is exactly where LFP wavelet</span>
<span id="cb1-111"><a href="#cb1-111" aria-hidden="true" tabindex="-1"></a>coefficients tend to be smallest. Raising α from 28 (default) to 96 (aggressive) doesn't just</span>
<span id="cb1-112"><a href="#cb1-112" aria-hidden="true" tabindex="-1"></a>lower CR uniformly — it disproportionately removes the fast, phasic content that a post-event</span>
<span id="cb1-113"><a href="#cb1-113" aria-hidden="true" tabindex="-1"></a>classifier like the feedback decoder depends on, while barely touching the slow band-power</span>
<span id="cb1-114"><a href="#cb1-114" aria-hidden="true" tabindex="-1"></a>fluctuations wheel-speed decoding uses. RMSE, being dominated by the (larger-amplitude) slow</span>
<span id="cb1-115"><a href="#cb1-115" aria-hidden="true" tabindex="-1"></a>components, is largely blind to this — it does not distinguish "lost 5 µV of slow drift" from</span>
<span id="cb1-116"><a href="#cb1-116" aria-hidden="true" tabindex="-1"></a>"lost the phasic transient that carries the feedback signal."</span>
<span id="cb1-117"><a href="#cb1-117" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-118"><a href="#cb1-118" aria-hidden="true" tabindex="-1"></a><span class="fu">## Conclusion</span></span>
<span id="cb1-119"><a href="#cb1-119" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-120"><a href="#cb1-120" aria-hidden="true" tabindex="-1"></a>The default pass (ε=150, α=28) is functionally safe for the decoding uses checked here. The</span>
<span id="cb1-121"><a href="#cb1-121" aria-hidden="true" tabindex="-1"></a>aggressive pass (ε=450, α=96) is not: it measurably degrades wheel-speed decoding and</span>
<span id="cb1-122"><a href="#cb1-122" aria-hidden="true" tabindex="-1"></a>substantially degrades feedback decoding, without a corresponding warning from the RMSE/CR</span>
<span id="cb1-123"><a href="#cb1-123" aria-hidden="true" tabindex="-1"></a>metric it was calibrated on. **Recommendation: retire the current aggressive tier** for any</span>
<span id="cb1-124"><a href="#cb1-124" aria-hidden="true" tabindex="-1"></a>downstream use that touches decoding, and calibrate a new intermediate tier using a</span>
<span id="cb1-125"><a href="#cb1-125" aria-hidden="true" tabindex="-1"></a>decoding-aware objective rather than RMSE alone — see</span>
<span id="cb1-126"><a href="#cb1-126" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">Next steps</span><span class="co">](#next-steps)</span>.</span>
<span id="cb1-127"><a href="#cb1-127" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-128"><a href="#cb1-128" aria-hidden="true" tabindex="-1"></a><span class="fu">## Next steps {#next-steps}</span></span>
<span id="cb1-129"><a href="#cb1-129" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-130"><a href="#cb1-130" aria-hidden="true" tabindex="-1"></a>Proposed approach for calibrating an intermediate tier, not yet run:</span>
<span id="cb1-131"><a href="#cb1-131" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-132"><a href="#cb1-132" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>**Change the objective.** Sweep candidate (ε, α) pairs and score each by decoding loss</span>
<span id="cb1-133"><a href="#cb1-133" aria-hidden="true" tabindex="-1"></a>   relative to uncompressed (ΔR² for wheel speed, Δbalanced-accuracy for choice/feedback) at a</span>
<span id="cb1-134"><a href="#cb1-134" aria-hidden="true" tabindex="-1"></a>   given CR, rather than RMSE. Feedback balanced accuracy is the most sensitive of the three</span>
<span id="cb1-135"><a href="#cb1-135" aria-hidden="true" tabindex="-1"></a>   metrics found here, so it should anchor the acceptance criterion (e.g. no more than a fixed</span>
<span id="cb1-136"><a href="#cb1-136" aria-hidden="true" tabindex="-1"></a>   fraction of the uncompressed decode retained).</span>
<span id="cb1-137"><a href="#cb1-137" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>**Sweep α more finely than ε.** §Interpretation points at α (the WP stage, which governs</span>
<span id="cb1-138"><a href="#cb1-138" aria-hidden="true" tabindex="-1"></a>   how much fine temporal/high-frequency structure survives within each retained SVD</span>
<span id="cb1-139"><a href="#cb1-139" aria-hidden="true" tabindex="-1"></a>   component) as the more likely lever for the feedback-decoding cost, not ε (which mainly</span>
<span id="cb1-140"><a href="#cb1-140" aria-hidden="true" tabindex="-1"></a>   sets spatial rank). A useful first pass: fix ε at its default 150 and sweep α between 28 and</span>
<span id="cb1-141"><a href="#cb1-141" aria-hidden="true" tabindex="-1"></a>   96 (e.g. {28, 40, 55, 70, 96}), before touching ε at all.</span>
<span id="cb1-142"><a href="#cb1-142" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>**Keep the search cheap.** The full decode (band envelopes + 3 decoders) costs</span>
<span id="cb1-143"><a href="#cb1-143" aria-hidden="true" tabindex="-1"></a>   ~10 min/recording/variant, so an 11-PID × full-α-grid sweep is expensive. Run the α sweep on</span>
<span id="cb1-144"><a href="#cb1-144" aria-hidden="true" tabindex="-1"></a>   3–4 recordings chosen to span the observed decodability range (e.g. <span class="in">`d7ec0892`</span> — strong</span>
<span id="cb1-145"><a href="#cb1-145" aria-hidden="true" tabindex="-1"></a>   decoder throughout; <span class="in">`1e104bf4`</span> or <span class="in">`da8dfec1`</span> — weak decoder, most likely to show a floor</span>
<span id="cb1-146"><a href="#cb1-146" aria-hidden="true" tabindex="-1"></a>   effect; one mid-range recording), then confirm the selected operating point on the full</span>
<span id="cb1-147"><a href="#cb1-147" aria-hidden="true" tabindex="-1"></a>   11-PID benchmark used throughout this page.</span>
<span id="cb1-148"><a href="#cb1-148" aria-hidden="true" tabindex="-1"></a><span class="ss">4. </span>**Report CR alongside decoding loss, not RMSE alongside decoding loss** — RMSE has already</span>
<span id="cb1-149"><a href="#cb1-149" aria-hidden="true" tabindex="-1"></a>   been shown here to miss the effect that matters; keep it as a secondary sanity check rather</span>
<span id="cb1-150"><a href="#cb1-150" aria-hidden="true" tabindex="-1"></a>   than the selection criterion.</span>
</code></pre></div><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>Olivier Winter</p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>
<script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","descPosition":"bottom","loop":false,"openEffect":"zoom","selector":".lightbox"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script>




</body></html>