<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Olivier Winter">
<meta name="dcterms.date" content="2026-09-05">
<meta name="description" content="Does lossy LFP compression degrade downstream science? Two independent functional validations — wheel/choice/feedback behavioural decoding (11 recordings) and brain-region classification (1099 recordings, full ephys-atlas cohort) — say yes, consistently, and agree on the same recommendation.">

<title>LFP Compression: Functional Validation – Analysis Hub</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-acf12a64177840b8d86f2d4f01b2e9fb.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-997f3bee8414e4416227c4bdeef383f8.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="../../site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="../../site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="../../site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Analysis Hub</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Analyses</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/oliche"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#overview" id="toc-overview" class="nav-link active" data-scroll-target="#overview">Overview</a></li>
  <li><a href="#behavioural-decoding-wheel-choice-feedback" id="toc-behavioural-decoding-wheel-choice-feedback" class="nav-link" data-scroll-target="#behavioural-decoding-wheel-choice-feedback">Behavioural decoding (wheel / choice / feedback)</a>
  <ul class="collapse">
  <li><a href="#method" id="toc-method" class="nav-link" data-scroll-target="#method">Method</a></li>
  <li><a href="#does-compression-hurt-decoding" id="toc-does-compression-hurt-decoding" class="nav-link" data-scroll-target="#does-compression-hurt-decoding">Does compression hurt decoding?</a></li>
  <li><a href="#searching-for-an-intermediate-tier" id="toc-searching-for-an-intermediate-tier" class="nav-link" data-scroll-target="#searching-for-an-intermediate-tier">Searching for an intermediate tier</a></li>
  <li><a href="#full-2d-grid" id="toc-full-2d-grid" class="nav-link" data-scroll-target="#full-2d-grid">Full 2D grid</a></li>
  </ul></li>
  <li><a href="#region-decoding-brain-region-classification" id="toc-region-decoding-brain-region-classification" class="nav-link" data-scroll-target="#region-decoding-brain-region-classification">Region decoding (brain-region classification)</a>
  <ul class="collapse">
  <li><a href="#update-2026-10-01-lfpack-v04-tiers-ts3-cosmos-benchmark" id="toc-update-2026-10-01-lfpack-v04-tiers-ts3-cosmos-benchmark" class="nav-link" data-scroll-target="#update-2026-10-01-lfpack-v04-tiers-ts3-cosmos-benchmark">Update 2026-10-01: lfpack v04 tiers (TS3 Cosmos benchmark)</a></li>
  <li><a href="#method-1" id="toc-method-1" class="nav-link" data-scroll-target="#method-1">Method</a></li>
  <li><a href="#does-compression-hurt-region-decoding" id="toc-does-compression-hurt-region-decoding" class="nav-link" data-scroll-target="#does-compression-hurt-region-decoding">Does compression hurt region decoding?</a></li>
  <li><a href="#does-avoiding-saturated-snippets-help" id="toc-does-avoiding-saturated-snippets-help" class="nav-link" data-scroll-target="#does-avoiding-saturated-snippets-help">Does avoiding saturated snippets help?</a></li>
  <li><a href="#recap" id="toc-recap" class="nav-link" data-scroll-target="#recap">Recap</a></li>
  </ul></li>
  <li><a href="#recommendation" id="toc-recommendation" class="nav-link" data-scroll-target="#recommendation">Recommendation</a></li>
  <li><a href="#code" id="toc-code" class="nav-link" data-scroll-target="#code">Code</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">LFP Compression: Functional Validation</h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
  <div class="quarto-categories">
    <div class="quarto-category">electrophysiology</div>
    <div class="quarto-category">LFP</div>
    <div class="quarto-category">compression</div>
    <div class="quarto-category">Neuropixels</div>
    <div class="quarto-category">decoding</div>
    <div class="quarto-category">region-classification</div>
  </div>
  </div>

<div>
  <div class="description">
    Does lossy LFP compression degrade downstream science? Two independent functional validations — wheel/choice/feedback behavioural decoding (11 recordings) and brain-region classification (1099 recordings, full ephys-atlas cohort) — say yes, consistently, and agree on the same recommendation.
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Olivier Winter </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 5, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="overview" class="level2">
<h2 class="anchored" data-anchor-id="overview">Overview</h2>
<p>The <a href="../../analyses/2026-06-lfp-compression-svd/index.html">SVD/WP compression benchmark</a> calibrates ε and α against <strong>RMSE and SNR</strong> — a spatial/amplitude fidelity proxy that says nothing about whether the <em>information</em> downstream analyses use survives compression. This page checks that directly, with two independent functional validations against real scientific use cases:</p>
<ol type="1">
<li><strong>Behavioural decoding</strong> — wheel speed, choice and feedback decoded from LFP band-power envelopes across 11 benchmark recordings, used to search for a better operating point than the original two-tier (default/aggressive) design.</li>
<li><strong>Region decoding</strong> — brain-region (Cosmos) classification from LF+CSD features at full ephys-atlas cohort scale (1099 recordings) — an independent task, decoder, and ~100× larger sample, run <em>after</em> the tier search above to confirm its conclusion generalises.</li>
</ol>
<p><strong>lfpack’s codec is two independent stages, applied in sequence</strong> (<code>compress()</code> in <code>packages/lfpack/src/lfpack/_core.py</code>):</p>
<ol type="1">
<li><strong>SVD stage — ε only.</strong> Rank <code>r = #{k : sv[k] &gt; ε·σ₀}</code> is fixed from the raw singular-value spectrum before α is used at all. ε alone decides how many spatial components survive.</li>
<li><strong>WP (wavelet-packet) stage — α only.</strong> Each of the <code>r</code> surviving components is wavelet-packet compressed with threshold <code>τ_k = α·σ₀/sv[k]</code>. α alone decides how much fine temporal/high-frequency detail survives <em>within</em> those components.</li>
</ol>
<p>They’re not fully independent in effect, though: <code>τ_k</code> is normalized by <code>sv[k]</code>, and which singular values survive to be thresholded is exactly what ε controls — so a given α lands differently depending on ε’s choice of surviving components. This turns out to matter a lot below.</p>
<p><strong>Bottom line:</strong> both validations agree. The shipped aggressive tier (ε=450, α=96) measurably hurts decoding — feedback especially, and region accuracy — with no warning from RMSE. Neither parameter is a usable lever on its own: α alone reliably costs decoding fidelity (confirmed with a paired test below) without buying real compression, and ε alone buys no compression either, nor — once properly tested — does it reliably cost decoding at all. Real compression only appears when both are pushed together, and a full 42-cell (ε, α) grid (mild through aggressive) maps that trade-off directly. The region-decoding validation, run independently at ~100× the sample size, reproduces the same tier ranking exactly: uncompressed &gt; mild &gt; default &gt; aggressive. <strong>Recommendation: retire the aggressive tier; keep default (ε=150, α=28) as standard; mild (ε=100, α=14) for the highest fidelity; ε=450, α=28 is the best non-dominated upgrade if more compression is required.</strong></p>
</section>
<section id="behavioural-decoding-wheel-choice-feedback" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="behavioural-decoding-wheel-choice-feedback">Behavioural decoding (wheel / choice / feedback)</h2>
<section id="method" class="level3">
<h3 class="anchored" data-anchor-id="method">Method</h3>
<p>Band-power envelope features (log Hilbert amplitude, delta/theta/beta/gamma, 96 channels after 4:1 spatial binning), computed identically for every compression tier from the same Cadzow-denoised checkpoint (<code>lf_resampled_car_cadzow.npy</code>), decoded with:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Target</th>
<th>Feature window</th>
<th>Decoder</th>
<th>Metric</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>|wheel velocity|</td>
<td>continuous, 50 ms bins</td>
<td>RidgeCV, 5-fold chronological CV</td>
<td>R²</td>
</tr>
<tr class="even">
<td>choice</td>
<td>[-0.2, 0) s rel. <code>firstMovement_times</code></td>
<td>Standardized LogisticRegressionCV, 5-fold stratified CV</td>
<td>balanced accuracy</td>
</tr>
<tr class="odd">
<td>feedback</td>
<td>[0, 0.2) s rel. <code>feedback_times</code></td>
<td>same</td>
<td>balanced accuracy</td>
</tr>
</tbody>
</table>
<p>Null: a simple per-fold label/target shuffle — not a pseudo-session control, so it understates single-recording significance, but it’s held identical across tiers, which is what matters for a <em>relative</em> compression-effect comparison. Sample times (t0 is <code>nan</code> on these benchmark files) are reconstructed via <code>SpikeSortingLoader.timesprobe2times</code>.</p>
</section>
<section id="does-compression-hurt-decoding" class="level3">
<h3 class="anchored" data-anchor-id="does-compression-hurt-decoding">Does compression hurt decoding?</h3>
<div id="fa05b3fc" class="cell" data-execution_count="1">
<div class="cell-output cell-output-display" data-execution_count="1">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th colspan="2" data-quarto-table-cell-role="th" data-halign="left">r2_wheel</th>
<th colspan="2" data-quarto-table-cell-role="th" data-halign="left">balanced_accuracy_choice</th>
<th colspan="2" data-quarto-table-cell-role="th" data-halign="left">balanced_accuracy_feedback</th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">mean</th>
<th data-quarto-table-cell-role="th">median</th>
<th data-quarto-table-cell-role="th">mean</th>
<th data-quarto-table-cell-role="th">median</th>
<th data-quarto-table-cell-role="th">mean</th>
<th data-quarto-table-cell-role="th">median</th>
</tr>
<tr class="header">
<th data-quarto-table-cell-role="th">tier</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">uncompressed</th>
<td>0.139</td>
<td>0.134</td>
<td>0.564</td>
<td>0.546</td>
<td>0.642</td>
<td>0.568</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">mild (eps100, alpha14)</th>
<td>0.134</td>
<td>0.133</td>
<td>0.556</td>
<td>0.531</td>
<td>0.626</td>
<td>0.570</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">alpha28 (default)</th>
<td>0.127</td>
<td>0.133</td>
<td>0.563</td>
<td>0.533</td>
<td>0.597</td>
<td>0.542</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">aggressive (eps450, alpha96, shipped)</th>
<td>0.104</td>
<td>0.084</td>
<td>0.552</td>
<td>0.509</td>
<td>0.557</td>
<td>0.508</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="fig-r2-by-pid" class="lightbox quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-r2-by-pid-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="figures/2026-09-05_lfp-compression-decoding_r2-by-pid.png" class="lightbox" data-gallery="quarto-lightbox-gallery-1" title="Figure&nbsp;1: Wheel-speed decoding R² per recording (uncompressed, mild, default, aggressive), vs shuffled null (black ticks)."><img src="figures/2026-09-05_lfp-compression-decoding_r2-by-pid.png" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-r2-by-pid-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Wheel-speed decoding R² per recording (uncompressed, mild, default, aggressive), vs shuffled null (black ticks).
</figcaption>
</figure>
</div>
<div id="fig-categorical-boxplot" class="lightbox quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-categorical-boxplot-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="figures/2026-09-05_lfp-compression-decoding_categorical_boxplot.png" class="lightbox" data-gallery="quarto-lightbox-gallery-2" title="Figure&nbsp;2: Choice / feedback balanced accuracy per recording, one box per tier (uncompressed, mild, default, aggressive). Dashed line = chance."><img src="figures/2026-09-05_lfp-compression-decoding_categorical_boxplot.png" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-categorical-boxplot-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Choice / feedback balanced accuracy per recording, one box per tier (uncompressed, mild, default, aggressive). Dashed line = chance.
</figcaption>
</figure>
</div>
<p>Default tracks uncompressed closely on every target; mild tracks it even more closely still (feedback balanced accuracy 0.626 vs.&nbsp;default’s 0.597 and uncompressed’s 0.642 — see <a href="#fig-r2-by-pid" class="quarto-xref">Figure&nbsp;1</a>, <a href="#fig-categorical-boxplot" class="quarto-xref">Figure&nbsp;2</a>). Aggressive erodes all three, feedback most severely (mean 0.642 → 0.557), because it’s decoded from a brief post-event window — exactly the fast, phasic structure the WP stage’s per-coefficient threshold removes first (small-magnitude coefficients are discarded before large ones, and fine time-scale structure is where LFP wavelet coefficients tend to be smallest). Wheel speed, a slower band-power average, is the least affected.</p>
</section>
<section id="searching-for-an-intermediate-tier" class="level3">
<h3 class="anchored" data-anchor-id="searching-for-an-intermediate-tier">Searching for an intermediate tier</h3>
<p>Sweeping <strong>ε alone</strong> (α=28 fixed, ε ∈ 150–450) or <strong>α alone</strong> (ε=150 fixed, α ∈ 28–96) both left total file size across the 11 recordings essentially flat (0.242 GB → ~0.21 GB either way, an ~13% reduction). But their effect on decoding fidelity is <em>not</em> symmetric, and the raw per- recording numbers are easy to misread here: feedback balanced accuracy varies enormously between recordings (SD ≈0.11 at a single grid cell — some recordings decode feedback near chance, others above 0.8), which swamps both parameters’ effects unless it’s controlled for. A paired per-recording test (same 11 recordings, before vs.&nbsp;after moving one parameter) shows they’re not equivalent: moving <strong>α</strong> from 28→96 (ε=150 fixed) drops feedback balanced accuracy in <strong>10/11 recordings</strong> (Wilcoxon p=0.005) — a real, consistent effect. Moving <strong>ε</strong> from 150→450 (α=28 fixed) only drops it in 6/11 (p=0.17) — <strong>not distinguishable from between-recording noise</strong>, and driven almost entirely by two strong-feedback-decoding recordings rather than a general effect. So: α alone reliably costs decoding fidelity without buying compression; ε alone buys no compression either, but its apparent decoding cost mostly isn’t real. Yet at ε=450, moving α from 28→96 — the shipped aggressive tier vs.&nbsp;the same ε at default’s α — <em>nearly halves</em> the file size (0.211 GB → 0.098 GB): the ε/α interaction described above, in action. Real compression only appears when both are pushed together.</p>
<div id="477e85cc" class="cell" data-execution_count="2">
<div class="cell-output cell-output-display" data-execution_count="2">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">r2_wheel</th>
<th data-quarto-table-cell-role="th">balanced_accuracy_choice</th>
<th data-quarto-table-cell-role="th">balanced_accuracy_feedback</th>
<th data-quarto-table-cell-role="th">cr_realized</th>
<th data-quarto-table-cell-role="th">total_GB</th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">tier</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">uncompressed</th>
<td>0.139</td>
<td>0.564</td>
<td>0.642</td>
<td>1.000</td>
<td>20.402</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">alpha28 (default)</th>
<td>0.127</td>
<td>0.563</td>
<td>0.597</td>
<td>86.679</td>
<td>0.242</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">eps250/alpha50</th>
<td>0.117</td>
<td>0.552</td>
<td>0.575</td>
<td>103.736</td>
<td>0.201</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">eps350/alpha75</th>
<td>0.109</td>
<td>0.549</td>
<td>0.558</td>
<td>128.251</td>
<td>0.163</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">aggressive (eps450, alpha96, shipped)</th>
<td>0.104</td>
<td>0.552</td>
<td>0.557</td>
<td>217.478</td>
<td>0.098</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="fig-diagonal-summary" class="lightbox quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-diagonal-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="figures/2026-08-31_diagonal_sweep_decoding_summary.png" class="lightbox" data-gallery="quarto-lightbox-gallery-3" title="Figure&nbsp;3: Diagonal sweep (ε and α scaled together, default → shipped aggressive): wheel R², choice/feedback balanced accuracy, and total file size (realized CR labelled), 11 recordings."><img src="figures/2026-08-31_diagonal_sweep_decoding_summary.png" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-diagonal-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Diagonal sweep (ε and α scaled together, default → shipped aggressive): wheel R², choice/feedback balanced accuracy, and total file size (realized CR labelled), 11 recordings.
</figcaption>
</figure>
</div>
<div id="fig-diagonal-psd" class="lightbox quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-diagonal-psd-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="figures/2026-08-31_diagonal_sweep_psd.png" class="lightbox" data-gallery="quarto-lightbox-gallery-4" title="Figure&nbsp;4: Median channel-averaged PSD, diagonal sweep — cleanly ordered by compression level; the high-frequency roll-off tracks decoding cost directly."><img src="figures/2026-08-31_diagonal_sweep_psd.png" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-diagonal-psd-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Median channel-averaged PSD, diagonal sweep — cleanly ordered by compression level; the high-frequency roll-off tracks decoding cost directly.
</figcaption>
</figure>
</div>
<p>Realized CR climbs steadily (87×→104×→128×→217×) as feedback retention falls in step (0.688→0.530→0.410→0.402) — <strong>no free knee</strong>: every step away from default costs real fidelity immediately (<a href="#fig-diagonal-summary" class="quarto-xref">Figure&nbsp;3</a>, <a href="#fig-diagonal-psd" class="quarto-xref">Figure&nbsp;4</a>). <code>eps350/alpha75</code> is dominated by the shipped aggressive tier (almost the same feedback cost, barely half the compression) — not worth using. This diagonal only sampled the line between two points, though — the full grid below covers the surface.</p>
</section>
<section id="full-2d-grid" class="level3 page-columns page-full">
<h3 class="anchored" data-anchor-id="full-2d-grid">Full 2D grid</h3>
<p>ε ∈ {50, 100, 150, 250, 300, 350, 450} × α ∈ {14, 28, 40, 55, 75, 96} — 42 cells (milder than default through the shipped aggressive point), all three decode targets, across the same 11 benchmark recordings used throughout this section — 14.8 h of LFP in total.</p>
<div id="d30f7651" class="cell" data-execution_count="3">
<div class="cell-output cell-output-display" data-execution_count="3">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">r2_wheel</th>
<th data-quarto-table-cell-role="th">balanced_accuracy_choice</th>
<th data-quarto-table-cell-role="th">balanced_accuracy_feedback</th>
<th data-quarto-table-cell-role="th">cr_realized</th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">epsilon</th>
<th data-quarto-table-cell-role="th">alpha</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th rowspan="6" data-quarto-table-cell-role="th" data-valign="top">50.0</th>
<th data-quarto-table-cell-role="th">14.0</th>
<td>0.134</td>
<td>0.557</td>
<td>0.628</td>
<td>38.476</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">28.0</th>
<td>0.127</td>
<td>0.563</td>
<td>0.595</td>
<td>47.945</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">40.0</th>
<td>0.122</td>
<td>0.559</td>
<td>0.584</td>
<td>51.625</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">55.0</th>
<td>0.116</td>
<td>0.553</td>
<td>0.569</td>
<td>54.057</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">75.0</th>
<td>0.110</td>
<td>0.549</td>
<td>0.559</td>
<td>56.123</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">96.0</th>
<td>0.104</td>
<td>0.552</td>
<td>0.555</td>
<td>57.458</td>
</tr>
<tr class="odd">
<th rowspan="6" data-quarto-table-cell-role="th" data-valign="top">100.0</th>
<th data-quarto-table-cell-role="th">14.0</th>
<td>0.134</td>
<td>0.556</td>
<td>0.626</td>
<td>48.228</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">28.0</th>
<td>0.127</td>
<td>0.562</td>
<td>0.595</td>
<td>64.020</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">40.0</th>
<td>0.122</td>
<td>0.559</td>
<td>0.584</td>
<td>70.683</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">55.0</th>
<td>0.116</td>
<td>0.553</td>
<td>0.569</td>
<td>75.292</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">75.0</th>
<td>0.110</td>
<td>0.549</td>
<td>0.559</td>
<td>79.255</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">96.0</th>
<td>0.104</td>
<td>0.552</td>
<td>0.555</td>
<td>81.882</td>
</tr>
<tr class="odd">
<th rowspan="6" data-quarto-table-cell-role="th" data-valign="top">150.0</th>
<th data-quarto-table-cell-role="th">14.0</th>
<td>0.133</td>
<td>0.558</td>
<td>0.623</td>
<td>53.483</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">28.0</th>
<td>0.127</td>
<td>0.563</td>
<td>0.597</td>
<td>86.679</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">40.0</th>
<td>0.122</td>
<td>0.560</td>
<td>0.584</td>
<td>82.420</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">55.0</th>
<td>0.116</td>
<td>0.553</td>
<td>0.569</td>
<td>88.756</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">75.0</th>
<td>0.110</td>
<td>0.549</td>
<td>0.559</td>
<td>94.279</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">96.0</th>
<td>0.104</td>
<td>0.552</td>
<td>0.555</td>
<td>97.974</td>
</tr>
<tr class="odd">
<th rowspan="6" data-quarto-table-cell-role="th" data-valign="top">250.0</th>
<th data-quarto-table-cell-role="th">14.0</th>
<td>0.131</td>
<td>0.554</td>
<td>0.615</td>
<td>59.972</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">28.0</th>
<td>0.125</td>
<td>0.559</td>
<td>0.589</td>
<td>85.213</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">40.0</th>
<td>0.121</td>
<td>0.559</td>
<td>0.581</td>
<td>97.263</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">55.0</th>
<td>0.115</td>
<td>0.552</td>
<td>0.568</td>
<td>106.184</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">75.0</th>
<td>0.109</td>
<td>0.550</td>
<td>0.557</td>
<td>114.185</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">96.0</th>
<td>0.104</td>
<td>0.552</td>
<td>0.554</td>
<td>119.582</td>
</tr>
<tr class="odd">
<th rowspan="6" data-quarto-table-cell-role="th" data-valign="top">300.0</th>
<th data-quarto-table-cell-role="th">14.0</th>
<td>0.131</td>
<td>0.555</td>
<td>0.611</td>
<td>62.484</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">28.0</th>
<td>0.124</td>
<td>0.563</td>
<td>0.591</td>
<td>89.387</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">40.0</th>
<td>0.120</td>
<td>0.560</td>
<td>0.582</td>
<td>102.596</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">55.0</th>
<td>0.115</td>
<td>0.554</td>
<td>0.569</td>
<td>112.573</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">75.0</th>
<td>0.109</td>
<td>0.549</td>
<td>0.560</td>
<td>121.583</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">96.0</th>
<td>0.104</td>
<td>0.552</td>
<td>0.556</td>
<td>127.672</td>
</tr>
<tr class="odd">
<th rowspan="6" data-quarto-table-cell-role="th" data-valign="top">350.0</th>
<th data-quarto-table-cell-role="th">14.0</th>
<td>0.130</td>
<td>0.557</td>
<td>0.596</td>
<td>64.939</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">28.0</th>
<td>0.124</td>
<td>0.557</td>
<td>0.586</td>
<td>93.133</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">40.0</th>
<td>0.120</td>
<td>0.562</td>
<td>0.580</td>
<td>107.362</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">55.0</th>
<td>0.114</td>
<td>0.552</td>
<td>0.569</td>
<td>118.304</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">75.0</th>
<td>0.109</td>
<td>0.549</td>
<td>0.558</td>
<td>128.251</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">96.0</th>
<td>0.104</td>
<td>0.551</td>
<td>0.555</td>
<td>134.987</td>
</tr>
<tr class="odd">
<th rowspan="6" data-quarto-table-cell-role="th" data-valign="top">450.0</th>
<th data-quarto-table-cell-role="th">14.0</th>
<td>0.127</td>
<td>0.556</td>
<td>0.594</td>
<td>69.960</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">28.0</th>
<td>0.122</td>
<td>0.555</td>
<td>0.585</td>
<td>99.948</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">40.0</th>
<td>0.119</td>
<td>0.561</td>
<td>0.578</td>
<td>115.902</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">55.0</th>
<td>0.114</td>
<td>0.548</td>
<td>0.568</td>
<td>128.589</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">75.0</th>
<td>0.109</td>
<td>0.549</td>
<td>0.559</td>
<td>140.247</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">96.0</th>
<td>0.104</td>
<td>0.552</td>
<td>0.557</td>
<td>217.478</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="fig-grid-heatmaps" class="lightbox quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-grid-heatmaps-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="figures/2026-09-05_grid_heatmaps.png" class="lightbox" data-gallery="quarto-lightbox-gallery-5" title="Figure&nbsp;5: Mean decode metrics and realized CR over the full (ε, α) grid. Uncompressed is added as a literal (ε=0, α=0) corner cell; the rest of that extra row/column is left blank. Mild, default and aggressive cells are outlined (green / red / orange)."><img src="figures/2026-09-05_grid_heatmaps.png" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-grid-heatmaps-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: Mean decode metrics and realized CR over the full (ε, α) grid. Uncompressed is added as a literal (ε=0, α=0) corner cell; the rest of that extra row/column is left blank. Mild, default and aggressive cells are outlined (green / red / orange).
</figcaption>
</figure>
</div>
<p>The heatmaps make the asymmetry from the previous section visible directly (<a href="#fig-grid-heatmaps" class="quarto-xref">Figure&nbsp;5</a>): wheel and feedback both shift clearly moving <em>across</em> alpha (columns) but barely at all moving <em>down</em> epsilon (rows) — until the (450, 96) corner, which stands out as a clear outlier in the CR panel (217× vs.&nbsp;140× and 135× in its immediate neighbors), the interaction in action. The corner cells also show plainly how close default’s decode metrics already sit to uncompressed (0.127 vs.&nbsp;0.139 wheel R², 0.597 vs.&nbsp;0.642 feedback) — and how much closer mild’s sit (0.134 wheel R², 0.626 feedback) — and how far realized CR has to climb from uncompressed’s 1×.</p>
<div id="fig-grid-boxplots" class="lightbox quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-grid-boxplots-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="figures/2026-09-01_grid_boxplots_by_epsilon.png" class="lightbox" data-gallery="quarto-lightbox-gallery-6" title="Figure&nbsp;6: Decoding metrics grouped by epsilon (hue = alpha), plotted as each recording’s own delta from its default (150,28) cell — this removes the ~0.11 SD between-recording offset that hides the effect in raw values. Uncompressed (blue dash-dot line) is each recording’s own delta between its uncompressed and default scores, since it doesn’t sit at any (ε, α) x-position."><img src="figures/2026-09-01_grid_boxplots_by_epsilon.png" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-grid-boxplots-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6: Decoding metrics grouped by epsilon (hue = alpha), plotted as each recording’s own delta from its default (150,28) cell — this removes the ~0.11 SD between-recording offset that hides the effect in raw values. Uncompressed (blue dash-dot line) is each recording’s own delta between its uncompressed and default scores, since it doesn’t sit at any (ε, α) x-position.
</figcaption>
</figure>
</div>
<div id="fig-grid-barplot-log" class="lightbox quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-grid-barplot-log-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="figures/2026-09-01_grid_barplot_size_by_epsilon.png" class="lightbox" data-gallery="quarto-lightbox-gallery-7" title="Figure&nbsp;7: Total compressed size grouped by epsilon (hue = alpha), log scale, with the uncompressed total (20.4 GB, blue dash-dot line) for scale — every tested tier is at least ~40× smaller — and a secondary axis converting size directly to realized CR. The (450,96) bar is visibly shorter than its neighbors, again the interaction."><img src="figures/2026-09-01_grid_barplot_size_by_epsilon.png" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-grid-barplot-log-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7: Total compressed size grouped by epsilon (hue = alpha), log scale, with the uncompressed total (20.4 GB, blue dash-dot line) for scale — every tested tier is at least ~40× smaller — and a secondary axis converting size directly to realized CR. The (450,96) bar is visibly shorter than its neighbors, again the interaction.
</figcaption>
</figure>
</div>
<div id="fig-grid-barplot-linear" class="lightbox quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-grid-barplot-linear-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="figures/2026-09-01_grid_barplot_size_by_epsilon_linear.png" class="lightbox" data-gallery="quarto-lightbox-gallery-8" title="Figure&nbsp;8: Same, linear scale (bars stay honestly zero-based; the uncompressed line is dropped here since at 20.4 GB it would flatten every bar to an invisible sliver) — makes the actual size differences between adjacent cells easier to judge than the log version above."><img src="figures/2026-09-01_grid_barplot_size_by_epsilon_linear.png" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-grid-barplot-linear-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8: Same, linear scale (bars stay honestly zero-based; the uncompressed line is dropped here since at 20.4 GB it would flatten every bar to an invisible sliver) — makes the actual size differences between adjacent cells easier to judge than the log version above.
</figcaption>
</figure>
</div>
<p><strong>Retained fraction</strong> (below) is how much of the uncompressed decode a tier keeps: for wheel, <code>R²(tier) / R²(uncompressed)</code>; for choice/feedback, <code>(balanced_accuracy(tier) - 0.5) / (balanced_accuracy(uncompressed) - 0.5)</code> — chance-corrected, since balanced accuracy’s floor is 0.5, not 0. 1.0 means indistinguishable from uncompressed.</p>
<div class="page-columns page-full">
<div id="fig-grid-pareto" class="lightbox quarto-float quarto-figure quarto-figure-center anchored page-columns page-full">
<figure class="quarto-float quarto-float-fig figure page-columns page-full">
<div aria-describedby="fig-grid-pareto-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca" class="page-columns page-full">
<a href="figures/2026-09-05_grid_pareto.png" class="lightbox page-columns page-full" data-gallery="quarto-lightbox-gallery-9" title="Figure&nbsp;9: Pareto: realized CR vs.&nbsp;retained decode fraction, one panel per target (marker size = alpha, colour = epsilon). Mild (green plus), default (red star) and aggressive (orange X) are labelled. Default sits on the frontier for wheel and near it for feedback; mild sits further up the fidelity axis at lower CR."><img src="figures/2026-09-05_grid_pareto.png" class="img-fluid figure-img column-page"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-grid-pareto-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9: Pareto: realized CR vs.&nbsp;retained decode fraction, one panel per target (marker size = alpha, colour = epsilon). Mild (green plus), default (red star) and aggressive (orange X) are labelled. Default sits on the frontier for wheel and near it for feedback; mild sits further up the fidelity axis at lower CR.
</figcaption>
</figure>
</div>
</div>
<p><strong>The true Pareto frontier</strong> (cells where no other cell has both higher realized CR and higher retained feedback) contains 16 of the 42 cells, and default (150, 28) is on it — nothing dominates it (<a href="#fig-grid-pareto" class="quarto-xref">Figure&nbsp;9</a>). Mild (100, 14) sits further up the fidelity axis, at lower CR — also on the frontier, the best-fidelity point tested. Stepping along the frontier past default is a real, gradual trade the whole way: (300, 28) barely improves CR (89× vs.&nbsp;87×) for a real feedback cost (retained fraction 0.640 vs.&nbsp;0.688); (350, 28) and (450, 28) are close together and both meaningfully better value — (450, 28) reaches 100× for retained fraction 0.603, a small further cost over (350, 28)’s 93×/0.605 for real extra compression. Past that, the frontier only continues by also raising α, which is where the interaction — and the larger feedback cost — kicks in.</p>
</section>
</section>
<section id="region-decoding-brain-region-classification" class="level2">
<h2 class="anchored" data-anchor-id="region-decoding-brain-region-classification">Region decoding (brain-region classification)</h2>
<p>A second, independent functional check, run <em>after</em> the tier search above, at a much larger and more heterogeneous scale (1099 PIDs, not 11) and on a completely different task — to see whether the tier ranking found above is a real property of the codec or an artefact of the wheel/choice/feedback validation’s specific method.</p>
<section id="update-2026-10-01-lfpack-v04-tiers-ts3-cosmos-benchmark" class="level3">
<h3 class="anchored" data-anchor-id="update-2026-10-01-lfpack-v04-tiers-ts3-cosmos-benchmark">Update 2026-10-01: lfpack v04 tiers (TS3 Cosmos benchmark)</h3>
<p><strong>The v04 <code>small</code> tier (α = 14) decodes regions as well as v03 mild at 0.33× its size, and lowering α keeps improving region decoding.</strong> At equal α, the format-2 + shared-basis codec is neutral, so region decoding, like behaviour decoding, depends only on α. Unlike behaviour decoding, which is within noise at every v04 tier, region decoding still gains from α = 14 to 2.5: +2.5 pp 5-fold CV accuracy and +1.7 pp TS3 eval accuracy.</p>
<div class="cell" data-execution_count="4">
<div id="tbl-ts3-v04" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="4">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ts3-v04-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: TS3 Cosmos region classification per lfpack tier: mean ± s.e.m. over 3 model seeds (43/44/45), 3222 eval units. CV: 5-fold PID-grouped held-out accuracy on the 1054 training PIDs. 1/CR: file / uncompressed float32 at 250 Hz (1955.7 GB over 1099 PIDs).
</figcaption>
<div aria-describedby="tbl-ts3-v04-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display" data-execution_count="4">
<div>


<table class="dataframe cell caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">α</th>
<th data-quarto-table-cell-role="th">file (GB)</th>
<th data-quarto-table-cell-role="th">1/CR</th>
<th data-quarto-table-cell-role="th">file / v03 mild</th>
<th data-quarto-table-cell-role="th">accuracy</th>
<th data-quarto-table-cell-role="th">macro F1</th>
<th data-quarto-table-cell-role="th">CV accuracy</th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">tier</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">v03-mild</th>
<td>14</td>
<td>34.2</td>
<td>1.75%</td>
<td>1.00</td>
<td>0.572 ± 0.004</td>
<td>0.438 ± 0.008</td>
<td>0.513 ± 0.000</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">v04-small</th>
<td>14</td>
<td>11.2</td>
<td>0.57%</td>
<td>0.33</td>
<td>0.576 ± 0.003</td>
<td>0.444 ± 0.003</td>
<td>0.518 ± 0.000</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">v04-default</th>
<td>7</td>
<td>21.5</td>
<td>1.10%</td>
<td>0.63</td>
<td>0.580 ± 0.001</td>
<td>0.513 ± 0.005</td>
<td>0.538 ± 0.001</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">v04-fine</th>
<td>2.5</td>
<td>46.1</td>
<td>2.36%</td>
<td>1.35</td>
<td>0.593 ± 0.006</td>
<td>0.489 ± 0.006</td>
<td>0.544 ± 0.001</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</figure>
</div>
</div>
<div class="cell" data-execution_count="5">
<div id="tbl-ts3-v04-classes" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="5">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ts3-v04-classes-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Per-class F1 (mean over 3 seeds) for the classes whose F1 moves by more than 0.05 across tiers (MB, 0.69–0.71, is left out). n: eval units per class.
</figcaption>
<div aria-describedby="tbl-ts3-v04-classes-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display" data-execution_count="5">
<div>


<table class="dataframe cell caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">tier</th>
<th data-quarto-table-cell-role="th">n</th>
<th data-quarto-table-cell-role="th">v03-mild</th>
<th data-quarto-table-cell-role="th">v04-small</th>
<th data-quarto-table-cell-role="th">v04-default</th>
<th data-quarto-table-cell-role="th">v04-fine</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">CB</th>
<td>162</td>
<td>0.303</td>
<td>0.331</td>
<td>0.570</td>
<td>0.660</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">CNU</th>
<td>187</td>
<td>0.415</td>
<td>0.411</td>
<td>0.465</td>
<td>0.501</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">CTXsp</th>
<td>48</td>
<td>0.071</td>
<td>0.037</td>
<td>0.202</td>
<td>0.108</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">HB</th>
<td>218</td>
<td>0.503</td>
<td>0.496</td>
<td>0.519</td>
<td>0.578</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">HPF</th>
<td>323</td>
<td>0.591</td>
<td>0.592</td>
<td>0.533</td>
<td>0.510</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">HY</th>
<td>54</td>
<td>0.271</td>
<td>0.315</td>
<td>0.568</td>
<td>0.159</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">Isocortex</th>
<td>578</td>
<td>0.594</td>
<td>0.592</td>
<td>0.613</td>
<td>0.688</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">OLF</th>
<td>265</td>
<td>0.247</td>
<td>0.276</td>
<td>0.340</td>
<td>0.404</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">TH</th>
<td>690</td>
<td>0.691</td>
<td>0.695</td>
<td>0.623</td>
<td>0.577</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</figure>
</div>
</div>
<ul>
<li><strong>Equal α, smaller file: no loss.</strong> v04 <code>small</code> against v03 mild (both α = 14; format 2 and a shared spatial basis instead of format 1 and per-chunk U): accuracy 0.576 vs 0.572, macro F1 0.444 vs 0.438, CV accuracy 0.518 vs 0.513. Every per-class F1 agrees within noise.</li>
<li><strong>Lower α helps region decoding.</strong> CV accuracy rises monotonically, 0.518 → 0.538 → 0.544 (α = 14 → 7 → 2.5), and so does eval accuracy, 0.576 → 0.580 → 0.593. Isocortex, CB, OLF and HB gain the most; TH and HPF lose 0.1 F1, so lower α also shifts which regions get predicted.</li>
<li><strong>Eval macro F1 peaks at <code>default</code></strong> (0.513 vs <code>fine</code>’s 0.489). That comes almost entirely from HY (0.57 vs 0.16, 54 units) and CTXsp (48 units). Classes that small, from 29 sessions, make macro F1 noisy, so CV accuracy (330k channels) is the more reliable ranking.</li>
<li><strong>Paired design.</strong> Same 1099 PIDs, same saturation-avoided snippet start times (saturation comes from the raw ADC signal and the Cadzow checkpoints are shared), same 5-fold split, same ground truth. Only the archive changes.</li>
<li>The v03 mild baseline was rescored from its existing channel predictions on the current eval build. That build has 3222 units, up from 3209, so the 2026-09-04 single-run score (0.584 / 0.416) is not directly comparable.</li>
</ul>
<p>Code: <code>~/Documents/ibldevtools/olivier/2026-09-04_ts3-lfp-baseline/</code> (<code>LFPACK_TIER</code> env var in <code>paths.py</code>; <code>score_tiers.py</code> writes <code>2026-09-30_ts3_v04_region_decoding.csv</code>).</p>
</section>
<section id="method-1" class="level3">
<h3 class="anchored" data-anchor-id="method-1">Method</h3>
<p>Per-recording LF-band-power and CSD features (raw_lf + raw_lf_csd feature families, 33 columns, <code>ephysatlas.features.voltage_features_set</code>) are computed identically for every LFP source from ~8 snippets/PID (8.79 s windows, 600 s spacing, matching the canonical ephys-atlas snippet grid), aggregated into one channel-level table, then classified with the canonical ephys-atlas XGBoost pipeline (5-fold <strong>PID-grouped</strong> CV, Cosmos-level labels, <code>VINTAGE = "2026-08_lfp-decoders"</code>).</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>LFP source</th>
<th>Read from</th>
<th>Notes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>uncompressed</code></td>
<td><code>lf_resampled_car_cadzow.npy</code> (Cadzow checkpoint, pre-SVD/WP)</td>
<td>reference — already on the compute cluster</td>
</tr>
<tr class="even">
<td><code>mild</code></td>
<td><code>lf_compressed_mild_all.h5</code></td>
<td>lfpack SVD+WP ε=100, α=14</td>
</tr>
<tr class="odd">
<td><code>default</code></td>
<td><code>lf_compressed_all.h5</code></td>
<td>lfpack SVD+WP ε=150, α=28</td>
</tr>
<tr class="even">
<td><code>aggressive</code></td>
<td><code>lf_compressed_aggressive_all.h5</code></td>
<td>lfpack SVD+WP ε=450, α=96</td>
</tr>
</tbody>
</table>
<p>Two snippet-selection modes are compared per source (except <code>mild</code>, run only at full-cohort scale for <code>all</code> — see <a href="#recap">Recap</a>): naive (<code>all</code>) vs.&nbsp;<strong>saturation-avoided</strong>, which drops snippets overlapping an ADC-saturated interval. This isolates the saturation question from the compression question directly, on the same cohort.</p>
<p>Cohort: every histology-resolved insertion in <code>ibl_neuropixel_brainwide_01</code> (the ephys-atlas cohort — a strict superset of the curated ~700-PID BWM behavioural cohort), <strong>1099 PIDs, 407616 channels</strong> per source/mode combination.</p>
</section>
<section id="does-compression-hurt-region-decoding" class="level3">
<h3 class="anchored" data-anchor-id="does-compression-hurt-region-decoding">Does compression hurt region decoding?</h3>
<div id="479064bd" class="cell" data-execution_count="6">
<div class="cell-output cell-output-display" data-execution_count="6">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">lfp_source</th>
<th data-quarto-table-cell-role="th">snippet_mode</th>
<th data-quarto-table-cell-role="th">accuracy</th>
<th data-quarto-table-cell-role="th">n_pids</th>
<th data-quarto-table-cell-role="th">n_channels</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>uncompressed</td>
<td>all</td>
<td>0.468500</td>
<td>1099</td>
<td>407616</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>uncompressed</td>
<td>saturation-avoided</td>
<td>0.470953</td>
<td>1099</td>
<td>407616</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>mild</td>
<td>all</td>
<td>0.434706</td>
<td>1099</td>
<td>407616</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>default</td>
<td>all</td>
<td>0.420096</td>
<td>1099</td>
<td>407616</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>default</td>
<td>saturation-avoided</td>
<td>0.416753</td>
<td>1099</td>
<td>407616</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">5</th>
<td>aggressive</td>
<td>all</td>
<td>0.389008</td>
<td>1099</td>
<td>407616</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">6</th>
<td>aggressive</td>
<td>saturation-avoided</td>
<td>0.391597</td>
<td>1099</td>
<td>407616</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="fig-region-compression-impact" class="lightbox quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-region-compression-impact-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="figures/2026-09-05_lfp-decoders_compression-impact.png" class="lightbox" data-gallery="quarto-lightbox-gallery-10" title="Figure&nbsp;10: Impact of LFP compression tier on region decoding — mean accuracy (Cosmos, held-out) across 1099 PIDs, snippet_mode=“all”. Same ranking as the wheel/choice/feedback validation."><img src="figures/2026-09-05_lfp-decoders_compression-impact.png" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-region-compression-impact-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;10: Impact of LFP compression tier on region decoding — mean accuracy (Cosmos, held-out) across 1099 PIDs, snippet_mode=“all”. Same ranking as the wheel/choice/feedback validation.
</figcaption>
</figure>
</div>
<p>Compression clearly costs region-decoding accuracy, and the cost is monotonic with compression aggressiveness (<a href="#fig-region-compression-impact" class="quarto-xref">Figure&nbsp;10</a>): uncompressed (0.468) &gt; mild (0.435, −3.3pp) &gt; default (0.420, −4.8pp) &gt; aggressive (0.389, −7.9pp vs.&nbsp;uncompressed). This mirrors the wheel/choice/feedback validation’s ranking exactly, on a completely different task, decoder, and cohort scale — strong evidence that the compression-tier ordering is a real property of the codec, not an artefact of one validation’s specific method.</p>
</section>
<section id="does-avoiding-saturated-snippets-help" class="level3">
<h3 class="anchored" data-anchor-id="does-avoiding-saturated-snippets-help">Does avoiding saturated snippets help?</h3>
<div id="fig-region-saturation-impact" class="lightbox quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-region-saturation-impact-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="figures/2026-09-05_lfp-decoders_saturation-impact.png" class="lightbox" data-gallery="quarto-lightbox-gallery-11" title="Figure&nbsp;11: Impact of ADC saturation avoidance on region decoding — bars: mean ± SD across 5 folds; dots: individual folds. Restricted to the three sources with both snippet modes (mild is all-only, see Recap)."><img src="figures/2026-09-05_lfp-decoders_saturation-impact.png" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-region-saturation-impact-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;11: Impact of ADC saturation avoidance on region decoding — bars: mean ± SD across 5 folds; dots: individual folds. Restricted to the three sources with both snippet modes (<code>mild</code> is <code>all</code>-only, see <a href="#recap">Recap</a>).
</figcaption>
</figure>
</div>
<p>Small and inconsistent in direction (<a href="#fig-region-saturation-impact" class="quarto-xref">Figure&nbsp;11</a>): default drops slightly avoiding saturation (−0.3pp), aggressive and uncompressed both gain slightly (+0.3pp, +0.2pp) — all differences are within the fold-to-fold spread seen within a single combo’s own 5 folds. Avoiding ADC-saturated snippets does not meaningfully change region-decoding accuracy at this snippet-selection scale — a separate axis from the compression-tier effect above, and not something saturation handling needs to trade off against.</p>
</section>
<section id="recap" class="level3">
<h3 class="anchored" data-anchor-id="recap">Recap</h3>
<div id="fig-region-recap-table" class="lightbox quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-region-recap-table-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="figures/2026-09-05_lfp-decoders_recap-table.png" class="lightbox" data-gallery="quarto-lightbox-gallery-12" title="Figure&nbsp;12: Full numeric recap: accuracy mean/SD/min/max across folds, sample sizes, per source × snippet mode."><img src="figures/2026-09-05_lfp-decoders_recap-table.png" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-region-recap-table-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;12: Full numeric recap: accuracy mean/SD/min/max across folds, sample sizes, per source × snippet mode.
</figcaption>
</figure>
</div>
<p><code>mild</code> was added to this validation after the wheel/choice/feedback grid had already identified ε=100/α=14 as the best-fidelity operating point worth naming and shipping (see <a href="#full-2d-grid">Full 2D grid</a> above) — run only at <code>snippet_mode="all"</code> full-cohort scale, not <code>saturation-avoided</code>, since the saturation question was already answered by the other three sources and doesn’t need re-litigating per tier (<a href="#fig-region-recap-table" class="quarto-xref">Figure&nbsp;12</a>).</p>
</section>
</section>
<section id="recommendation" class="level2">
<h2 class="anchored" data-anchor-id="recommendation">Recommendation</h2>
<ul>
<li><strong>Keep default (ε=150, α=28)</strong> as the standard cohort-wide tier — it’s Pareto-efficient on the behavioural grid, and every tested alternative in that direction trades away real feedback fidelity.</li>
<li><strong>Use mild (ε=100, α=14) for the highest fidelity.</strong> Named and shipped as a third production tier: realized CR 48× (vs.&nbsp;default’s 87×, uncompressed’s 1×), feedback balanced accuracy 0.626 vs.&nbsp;default’s 0.597 and uncompressed’s 0.642 — a chance-corrected retained-feedback-fraction of <strong>0.89</strong> vs.&nbsp;default’s 0.68. Confirmed independently at full ephys-atlas cohort scale (1099 PIDs) by the region-decoding validation above (0.435 vs.&nbsp;default’s 0.420, uncompressed’s 0.468).</li>
<li><strong>If more compression is required, use ε=450, α=28</strong> — 100× realized CR (0.211 GB vs. default’s 0.242 GB across the 11 recordings, both tiny next to uncompressed’s 20.4 GB), R² 0.122 vs.&nbsp;default’s 0.127, feedback balanced accuracy 0.585 vs.&nbsp;default’s 0.597. That feedback gap is not statistically distinguishable from between-recording noise (paired Wilcoxon p=0.17) — the best-value, lowest-risk upgrade found on the whole grid.</li>
<li><strong>Retire the aggressive tier (ε=450, α=96).</strong> Nothing between ε=450/α=28 and aggressive is worth shipping — the frontier only gets there by also raising α, which is where the real, significant decoding cost (p=0.005) lives, and the largest region-decoding cost measured (−7.9pp vs.&nbsp;uncompressed).</li>
<li><strong>Build command</strong> (per-recording, ≈10–60 s from the existing Cadzow checkpoint, no re-download needed): <code>lfpack.compress_to_h5(cadzow_npy, out_h5, recording=pid, epsilon=450.0, alpha=28.0, fs=250.0, ...)</code>.</li>
</ul>
</section>
<section id="code" class="level2">
<h2 class="anchored" data-anchor-id="code">Code</h2>
<p><strong>Behavioural decoding</strong>: <code>oliche-quarto/analyses/2026-06-lfp-compression-svd/</code> — <code>compression_benchmark.py</code>, <code>svd_adaptive_wp.py</code> and the dated <code>2026-08-31_LFP_compression_*.py</code> / <code>2026-08-31_LFP_compression_full_grid_displays.py</code> scripts under <code>~/Documents/ibldevtools/olivier/</code> (sweep computation + this page’s figures). The <code>mild</code> tier was added after the fact by <code>2026-09-05_LFP_compression_decoding_add_mild.py</code> / <code>2026-09-05_LFP_compression_decoding_categorical_add_mild.py</code> (reuse the already-computed uncompressed/default/aggressive rows, decode only the new variant, regenerate <a href="#fig-r2-by-pid" class="quarto-xref">Figure&nbsp;1</a> / <a href="#fig-categorical-boxplot" class="quarto-xref">Figure&nbsp;2</a>) and directly in <code>2026-08-31_LFP_compression_full_grid_displays.py</code> (<a href="#fig-grid-heatmaps" class="quarto-xref">Figure&nbsp;5</a> / <a href="#fig-grid-pareto" class="quarto-xref">Figure&nbsp;9</a> already covered the ε=100/α=14 cell — only the mild/default/aggressive highlight markers were added), same directory.</p>
<p><strong>Region decoding</strong>: <code>sdsc-slurms/2026-08_lfp-decoders/</code> — <code>extract.py</code> (per-PID/per-snippet LF+CSD feature extraction, joblib-parallel), <code>aggregate.py</code> (thin wrapper around <code>ephysatlas.aggregation.produce_output_dataframes</code>), <code>train_classifier.py</code> (5-fold PID-grouped XGBoost), <code>report.py</code> (this section’s table + figures, run locally after rsyncing <code>accuracy.json</code> back from the cluster). Region annotations (<code>atlas_id</code>/<code>acronym</code>/<code>x</code>/<code>y</code>/<code>z</code>) come embedded in each lfpack archive via <code>attach_ibl_metadata.py</code> (<code>sdsc-slurms/2026-06-lfpack/</code>).</p>


<!-- -->

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "LFP Compression: Functional Validation"</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="an">description:</span><span class="co"> "Does lossy LFP compression degrade downstream science? Two independent functional validations — wheel/choice/feedback behavioural decoding (11 recordings) and brain-region classification (1099 recordings, full ephys-atlas cohort) — say yes, consistently, and agree on the same recommendation."</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> "2026-09-05"</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> "Olivier Winter"</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="an">categories:</span><span class="co"> [electrophysiology, LFP, compression, Neuropixels, decoding, region-classification]</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">## Overview</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>The <span class="co">[</span><span class="ot">SVD/WP compression benchmark</span><span class="co">](index.qmd)</span> calibrates ε and α against **RMSE and SNR** — a</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>spatial/amplitude fidelity proxy that says nothing about whether the *information* downstream</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>analyses use survives compression. This page checks that directly, with two independent</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>functional validations against real scientific use cases:</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>**Behavioural decoding** — wheel speed, choice and feedback decoded from LFP band-power</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>   envelopes across 11 benchmark recordings, used to search for a better operating point than</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>   the original two-tier (default/aggressive) design.</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>**Region decoding** — brain-region (Cosmos) classification from LF+CSD features at full</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>   ephys-atlas cohort scale (1099 recordings) — an independent task, decoder, and ~100× larger</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>   sample, run *after* the tier search above to confirm its conclusion generalises.</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>**lfpack's codec is two independent stages, applied in sequence** (<span class="in">`compress()`</span> in</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a><span class="in">`packages/lfpack/src/lfpack/_core.py`</span>):</span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>**SVD stage — ε only.** Rank <span class="in">`r = #{k : sv[k] &gt; ε·σ₀}`</span> is fixed from the raw singular-value</span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>   spectrum before α is used at all. ε alone decides how many spatial components survive.</span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>**WP (wavelet-packet) stage — α only.** Each of the <span class="in">`r`</span> surviving components is</span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a>   wavelet-packet compressed with threshold <span class="in">`τ_k = α·σ₀/sv[k]`</span>. α alone decides how much fine</span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a>   temporal/high-frequency detail survives *within* those components.</span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a>They're not fully independent in effect, though: <span class="in">`τ_k`</span> is normalized by <span class="in">`sv[k]`</span>, and which</span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a>singular values survive to be thresholded is exactly what ε controls — so a given α lands</span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a>differently depending on ε's choice of surviving components. This turns out to matter a lot</span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a>below.</span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a>**Bottom line:** both validations agree. The shipped aggressive tier (ε=450, α=96) measurably</span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a>hurts decoding — feedback especially, and region accuracy — with no warning from RMSE. Neither</span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a>parameter is a usable lever on its own: α alone reliably costs decoding fidelity (confirmed with</span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a>a paired test below) without buying real compression, and ε alone buys no compression either,</span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a>nor — once properly tested — does it reliably cost decoding at all. Real compression only</span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a>appears when both are pushed together, and a full 42-cell (ε, α) grid (mild through aggressive)</span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a>maps that trade-off directly. The region-decoding validation, run independently at ~100× the</span>
<span id="cb1-44"><a href="#cb1-44" aria-hidden="true" tabindex="-1"></a>sample size, reproduces the same tier ranking exactly: uncompressed &gt; mild &gt; default &gt;</span>
<span id="cb1-45"><a href="#cb1-45" aria-hidden="true" tabindex="-1"></a>aggressive.</span>
<span id="cb1-46"><a href="#cb1-46" aria-hidden="true" tabindex="-1"></a>**Recommendation: retire the aggressive tier; keep default (ε=150, α=28) as standard; mild</span>
<span id="cb1-47"><a href="#cb1-47" aria-hidden="true" tabindex="-1"></a>(ε=100, α=14) for the highest fidelity; ε=450, α=28 is the best non-dominated upgrade if more</span>
<span id="cb1-48"><a href="#cb1-48" aria-hidden="true" tabindex="-1"></a>compression is required.**</span>
<span id="cb1-49"><a href="#cb1-49" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-50"><a href="#cb1-50" aria-hidden="true" tabindex="-1"></a><span class="fu">## Behavioural decoding (wheel / choice / feedback)</span></span>
<span id="cb1-51"><a href="#cb1-51" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-52"><a href="#cb1-52" aria-hidden="true" tabindex="-1"></a><span class="fu">### Method</span></span>
<span id="cb1-53"><a href="#cb1-53" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-54"><a href="#cb1-54" aria-hidden="true" tabindex="-1"></a>Band-power envelope features (log Hilbert amplitude, delta/theta/beta/gamma, 96 channels after</span>
<span id="cb1-55"><a href="#cb1-55" aria-hidden="true" tabindex="-1"></a>4:1 spatial binning), computed identically for every compression tier from the same</span>
<span id="cb1-56"><a href="#cb1-56" aria-hidden="true" tabindex="-1"></a>Cadzow-denoised checkpoint (<span class="in">`lf_resampled_car_cadzow.npy`</span>), decoded with:</span>
<span id="cb1-57"><a href="#cb1-57" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-58"><a href="#cb1-58" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Target <span class="pp">|</span> Feature window <span class="pp">|</span> Decoder <span class="pp">|</span> Metric <span class="pp">|</span></span>
<span id="cb1-59"><a href="#cb1-59" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---|---|---|</span></span>
<span id="cb1-60"><a href="#cb1-60" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="sc">\|</span>wheel velocity<span class="sc">\|</span> <span class="pp">|</span> continuous, 50 ms bins <span class="pp">|</span> RidgeCV, 5-fold chronological CV <span class="pp">|</span> R² <span class="pp">|</span></span>
<span id="cb1-61"><a href="#cb1-61" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> choice <span class="pp">|</span> [-0.2, 0) s rel. <span class="in">`firstMovement_times`</span> <span class="pp">|</span> Standardized LogisticRegressionCV, 5-fold stratified CV <span class="pp">|</span> balanced accuracy <span class="pp">|</span></span>
<span id="cb1-62"><a href="#cb1-62" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> feedback <span class="pp">|</span> [0, 0.2) s rel. <span class="in">`feedback_times`</span> <span class="pp">|</span> same <span class="pp">|</span> balanced accuracy <span class="pp">|</span></span>
<span id="cb1-63"><a href="#cb1-63" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-64"><a href="#cb1-64" aria-hidden="true" tabindex="-1"></a>Null: a simple per-fold label/target shuffle — not a pseudo-session control, so it understates</span>
<span id="cb1-65"><a href="#cb1-65" aria-hidden="true" tabindex="-1"></a>single-recording significance, but it's held identical across tiers, which is what matters for</span>
<span id="cb1-66"><a href="#cb1-66" aria-hidden="true" tabindex="-1"></a>a *relative* compression-effect comparison. Sample times (t0 is <span class="in">`nan`</span> on these benchmark files)</span>
<span id="cb1-67"><a href="#cb1-67" aria-hidden="true" tabindex="-1"></a>are reconstructed via <span class="in">`SpikeSortingLoader.timesprobe2times`</span>.</span>
<span id="cb1-68"><a href="#cb1-68" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-69"><a href="#cb1-69" aria-hidden="true" tabindex="-1"></a><span class="fu">### Does compression hurt decoding?</span></span>
<span id="cb1-70"><a href="#cb1-70" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-73"><a href="#cb1-73" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb1-74"><a href="#cb1-74" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb1-75"><a href="#cb1-75" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-76"><a href="#cb1-76" aria-hidden="true" tabindex="-1"></a>m <span class="op">=</span> pd.read_csv(<span class="st">"2026-08-31_compression_tuning_metrics.csv"</span>)</span>
<span id="cb1-77"><a href="#cb1-77" aria-hidden="true" tabindex="-1"></a>g_full <span class="op">=</span> pd.read_csv(<span class="st">"2026-09-01_full_grid_metrics.csv"</span>)</span>
<span id="cb1-78"><a href="#cb1-78" aria-hidden="true" tabindex="-1"></a>mild_rows <span class="op">=</span> g_full[(g_full[<span class="st">"epsilon"</span>] <span class="op">==</span> <span class="fl">100.0</span>) <span class="op">&amp;</span> (g_full[<span class="st">"alpha"</span>] <span class="op">==</span> <span class="fl">14.0</span>)].copy()</span>
<span id="cb1-79"><a href="#cb1-79" aria-hidden="true" tabindex="-1"></a>mild_rows[<span class="st">"tier"</span>] <span class="op">=</span> <span class="st">"mild (eps100, alpha14)"</span></span>
<span id="cb1-80"><a href="#cb1-80" aria-hidden="true" tabindex="-1"></a>m2 <span class="op">=</span> pd.concat(</span>
<span id="cb1-81"><a href="#cb1-81" aria-hidden="true" tabindex="-1"></a>    [m, mild_rows[[<span class="st">"tier"</span>, <span class="st">"r2_wheel"</span>, <span class="st">"balanced_accuracy_choice"</span>, <span class="st">"balanced_accuracy_feedback"</span>]]],</span>
<span id="cb1-82"><a href="#cb1-82" aria-hidden="true" tabindex="-1"></a>    ignore_index<span class="op">=</span><span class="va">True</span>,</span>
<span id="cb1-83"><a href="#cb1-83" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-84"><a href="#cb1-84" aria-hidden="true" tabindex="-1"></a>base_order <span class="op">=</span> [<span class="st">"uncompressed"</span>, <span class="st">"mild (eps100, alpha14)"</span>, <span class="st">"alpha28 (default)"</span>,</span>
<span id="cb1-85"><a href="#cb1-85" aria-hidden="true" tabindex="-1"></a>              <span class="st">"aggressive (eps450, alpha96, shipped)"</span>]</span>
<span id="cb1-86"><a href="#cb1-86" aria-hidden="true" tabindex="-1"></a>m2.groupby(<span class="st">"tier"</span>)[[<span class="st">"r2_wheel"</span>, <span class="st">"balanced_accuracy_choice"</span>, <span class="st">"balanced_accuracy_feedback"</span>]].agg([<span class="st">"mean"</span>, <span class="st">"median"</span>]).loc[base_order].<span class="bu">round</span>(<span class="dv">3</span>)</span>
<span id="cb1-87"><a href="#cb1-87" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-88"><a href="#cb1-88" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-89"><a href="#cb1-89" aria-hidden="true" tabindex="-1"></a><span class="al">![Wheel-speed decoding R² per recording (uncompressed, mild, default, aggressive), vs shuffled null (black ticks).](figures/2026-09-05_lfp-compression-decoding_r2-by-pid.png)</span>{#fig-r2-by-pid .lightbox}</span>
<span id="cb1-90"><a href="#cb1-90" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-91"><a href="#cb1-91" aria-hidden="true" tabindex="-1"></a><span class="al">![Choice / feedback balanced accuracy per recording, one box per tier (uncompressed, mild, default, aggressive). Dashed line = chance.](figures/2026-09-05_lfp-compression-decoding_categorical_boxplot.png)</span>{#fig-categorical-boxplot .lightbox}</span>
<span id="cb1-92"><a href="#cb1-92" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-93"><a href="#cb1-93" aria-hidden="true" tabindex="-1"></a>Default tracks uncompressed closely on every target; mild tracks it even more closely still</span>
<span id="cb1-94"><a href="#cb1-94" aria-hidden="true" tabindex="-1"></a>(feedback balanced accuracy 0.626 vs. default's 0.597 and uncompressed's 0.642 — see</span>
<span id="cb1-95"><a href="#cb1-95" aria-hidden="true" tabindex="-1"></a>@fig-r2-by-pid, @fig-categorical-boxplot). Aggressive erodes all three, feedback most</span>
<span id="cb1-96"><a href="#cb1-96" aria-hidden="true" tabindex="-1"></a>severely (mean 0.642 → 0.557), because it's decoded from a brief post-event window — exactly</span>
<span id="cb1-97"><a href="#cb1-97" aria-hidden="true" tabindex="-1"></a>the fast, phasic structure the WP stage's per-coefficient threshold removes first (small-magnitude</span>
<span id="cb1-98"><a href="#cb1-98" aria-hidden="true" tabindex="-1"></a>coefficients are discarded before large ones, and fine time-scale structure is where LFP</span>
<span id="cb1-99"><a href="#cb1-99" aria-hidden="true" tabindex="-1"></a>wavelet coefficients tend to be smallest). Wheel speed, a slower band-power average, is the</span>
<span id="cb1-100"><a href="#cb1-100" aria-hidden="true" tabindex="-1"></a>least affected.</span>
<span id="cb1-101"><a href="#cb1-101" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-102"><a href="#cb1-102" aria-hidden="true" tabindex="-1"></a><span class="fu">### Searching for an intermediate tier</span></span>
<span id="cb1-103"><a href="#cb1-103" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-104"><a href="#cb1-104" aria-hidden="true" tabindex="-1"></a>Sweeping **ε alone** (α=28 fixed, ε ∈ 150–450) or **α alone** (ε=150 fixed, α ∈ 28–96) both left</span>
<span id="cb1-105"><a href="#cb1-105" aria-hidden="true" tabindex="-1"></a>total file size across the 11 recordings essentially flat (0.242 GB → ~0.21 GB either way, an</span>
<span id="cb1-106"><a href="#cb1-106" aria-hidden="true" tabindex="-1"></a>~13% reduction). But their effect on decoding fidelity is *not* symmetric, and the raw per-</span>
<span id="cb1-107"><a href="#cb1-107" aria-hidden="true" tabindex="-1"></a>recording numbers are easy to misread here: feedback balanced accuracy varies enormously</span>
<span id="cb1-108"><a href="#cb1-108" aria-hidden="true" tabindex="-1"></a>between recordings (SD ≈0.11 at a single grid cell — some recordings decode feedback near</span>
<span id="cb1-109"><a href="#cb1-109" aria-hidden="true" tabindex="-1"></a>chance, others above 0.8), which swamps both parameters' effects unless it's controlled for. A</span>
<span id="cb1-110"><a href="#cb1-110" aria-hidden="true" tabindex="-1"></a>paired per-recording test (same 11 recordings, before vs. after moving one parameter) shows</span>
<span id="cb1-111"><a href="#cb1-111" aria-hidden="true" tabindex="-1"></a>they're not equivalent: moving **α** from 28→96 (ε=150 fixed) drops feedback balanced accuracy</span>
<span id="cb1-112"><a href="#cb1-112" aria-hidden="true" tabindex="-1"></a>in **10/11 recordings** (Wilcoxon p=0.005) — a real, consistent effect. Moving **ε** from</span>
<span id="cb1-113"><a href="#cb1-113" aria-hidden="true" tabindex="-1"></a>150→450 (α=28 fixed) only drops it in 6/11 (p=0.17) — **not distinguishable from</span>
<span id="cb1-114"><a href="#cb1-114" aria-hidden="true" tabindex="-1"></a>between-recording noise**, and driven almost entirely by two strong-feedback-decoding</span>
<span id="cb1-115"><a href="#cb1-115" aria-hidden="true" tabindex="-1"></a>recordings rather than a general effect. So: α alone reliably costs decoding fidelity without</span>
<span id="cb1-116"><a href="#cb1-116" aria-hidden="true" tabindex="-1"></a>buying compression; ε alone buys no compression either, but its apparent decoding cost mostly</span>
<span id="cb1-117"><a href="#cb1-117" aria-hidden="true" tabindex="-1"></a>isn't real. Yet at ε=450, moving α from 28→96 — the shipped aggressive tier vs. the same ε at</span>
<span id="cb1-118"><a href="#cb1-118" aria-hidden="true" tabindex="-1"></a>default's α — *nearly halves* the file size (0.211 GB → 0.098 GB): the ε/α interaction</span>
<span id="cb1-119"><a href="#cb1-119" aria-hidden="true" tabindex="-1"></a>described above, in action. Real compression only appears when both are pushed together.</span>
<span id="cb1-120"><a href="#cb1-120" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-123"><a href="#cb1-123" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb1-124"><a href="#cb1-124" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb1-125"><a href="#cb1-125" aria-hidden="true" tabindex="-1"></a>diag_order <span class="op">=</span> [<span class="st">"uncompressed"</span>, <span class="st">"alpha28 (default)"</span>, <span class="st">"eps250/alpha50"</span>, <span class="st">"eps350/alpha75"</span>,</span>
<span id="cb1-126"><a href="#cb1-126" aria-hidden="true" tabindex="-1"></a>              <span class="st">"aggressive (eps450, alpha96, shipped)"</span>]</span>
<span id="cb1-127"><a href="#cb1-127" aria-hidden="true" tabindex="-1"></a>tbl <span class="op">=</span> m.groupby(<span class="st">"tier"</span>)[[<span class="st">"r2_wheel"</span>, <span class="st">"balanced_accuracy_choice"</span>, <span class="st">"balanced_accuracy_feedback"</span>, <span class="st">"cr_realized"</span>]].mean().loc[diag_order]</span>
<span id="cb1-128"><a href="#cb1-128" aria-hidden="true" tabindex="-1"></a>tbl[<span class="st">"total_GB"</span>] <span class="op">=</span> m.groupby(<span class="st">"tier"</span>)[<span class="st">"file_bytes"</span>].<span class="bu">sum</span>().loc[diag_order] <span class="op">/</span> <span class="fl">1e9</span></span>
<span id="cb1-129"><a href="#cb1-129" aria-hidden="true" tabindex="-1"></a>tbl.<span class="bu">round</span>(<span class="dv">3</span>)</span>
<span id="cb1-130"><a href="#cb1-130" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-131"><a href="#cb1-131" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-132"><a href="#cb1-132" aria-hidden="true" tabindex="-1"></a><span class="al">![Diagonal sweep (ε and α scaled together, default → shipped aggressive): wheel R², choice/feedback balanced accuracy, and total file size (realized CR labelled), 11 recordings.](figures/2026-08-31_diagonal_sweep_decoding_summary.png)</span>{#fig-diagonal-summary .lightbox}</span>
<span id="cb1-133"><a href="#cb1-133" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-134"><a href="#cb1-134" aria-hidden="true" tabindex="-1"></a><span class="al">![Median channel-averaged PSD, diagonal sweep — cleanly ordered by compression level; the high-frequency roll-off tracks decoding cost directly.](figures/2026-08-31_diagonal_sweep_psd.png)</span>{#fig-diagonal-psd .lightbox}</span>
<span id="cb1-135"><a href="#cb1-135" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-136"><a href="#cb1-136" aria-hidden="true" tabindex="-1"></a>Realized CR climbs steadily (87×→104×→128×→217×) as feedback retention falls in step</span>
<span id="cb1-137"><a href="#cb1-137" aria-hidden="true" tabindex="-1"></a>(0.688→0.530→0.410→0.402) — **no free knee**: every step away from default costs real fidelity</span>
<span id="cb1-138"><a href="#cb1-138" aria-hidden="true" tabindex="-1"></a>immediately (@fig-diagonal-summary, @fig-diagonal-psd). <span class="in">`eps350/alpha75`</span> is dominated by the</span>
<span id="cb1-139"><a href="#cb1-139" aria-hidden="true" tabindex="-1"></a>shipped aggressive tier (almost the same feedback cost, barely half the compression) — not</span>
<span id="cb1-140"><a href="#cb1-140" aria-hidden="true" tabindex="-1"></a>worth using. This diagonal only sampled the line between two points, though — the full grid</span>
<span id="cb1-141"><a href="#cb1-141" aria-hidden="true" tabindex="-1"></a>below covers the surface.</span>
<span id="cb1-142"><a href="#cb1-142" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-143"><a href="#cb1-143" aria-hidden="true" tabindex="-1"></a><span class="fu">### Full 2D grid</span></span>
<span id="cb1-144"><a href="#cb1-144" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-145"><a href="#cb1-145" aria-hidden="true" tabindex="-1"></a>ε ∈ {50, 100, 150, 250, 300, 350, 450} × α ∈ {14, 28, 40, 55, 75, 96} — 42 cells (milder than</span>
<span id="cb1-146"><a href="#cb1-146" aria-hidden="true" tabindex="-1"></a>default through the shipped aggressive point), all three decode targets, across the same 11</span>
<span id="cb1-147"><a href="#cb1-147" aria-hidden="true" tabindex="-1"></a>benchmark recordings used throughout this section — 14.8 h of LFP in total.</span>
<span id="cb1-148"><a href="#cb1-148" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-151"><a href="#cb1-151" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb1-152"><a href="#cb1-152" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb1-153"><a href="#cb1-153" aria-hidden="true" tabindex="-1"></a>g <span class="op">=</span> pd.read_csv(<span class="st">"2026-09-01_full_grid_metrics.csv"</span>)</span>
<span id="cb1-154"><a href="#cb1-154" aria-hidden="true" tabindex="-1"></a>grid <span class="op">=</span> g.dropna(subset<span class="op">=</span>[<span class="st">"epsilon"</span>])</span>
<span id="cb1-155"><a href="#cb1-155" aria-hidden="true" tabindex="-1"></a>grid.groupby([<span class="st">"epsilon"</span>, <span class="st">"alpha"</span>])[[<span class="st">"r2_wheel"</span>, <span class="st">"balanced_accuracy_choice"</span>,</span>
<span id="cb1-156"><a href="#cb1-156" aria-hidden="true" tabindex="-1"></a>                                     <span class="st">"balanced_accuracy_feedback"</span>, <span class="st">"cr_realized"</span>]].mean().<span class="bu">round</span>(<span class="dv">3</span>)</span>
<span id="cb1-157"><a href="#cb1-157" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-158"><a href="#cb1-158" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-159"><a href="#cb1-159" aria-hidden="true" tabindex="-1"></a><span class="al">![Mean decode metrics and realized CR over the full (ε, α) grid. Uncompressed is added as a literal (ε=0, α=0) corner cell; the rest of that extra row/column is left blank. Mild, default and aggressive cells are outlined (green / red / orange).](figures/2026-09-05_grid_heatmaps.png)</span>{#fig-grid-heatmaps .lightbox}</span>
<span id="cb1-160"><a href="#cb1-160" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-161"><a href="#cb1-161" aria-hidden="true" tabindex="-1"></a>The heatmaps make the asymmetry from the previous section visible directly (@fig-grid-heatmaps):</span>
<span id="cb1-162"><a href="#cb1-162" aria-hidden="true" tabindex="-1"></a>wheel and feedback both shift clearly moving *across* alpha (columns) but barely at all moving</span>
<span id="cb1-163"><a href="#cb1-163" aria-hidden="true" tabindex="-1"></a>*down* epsilon (rows) — until the (450, 96) corner, which stands out as a clear outlier in the</span>
<span id="cb1-164"><a href="#cb1-164" aria-hidden="true" tabindex="-1"></a>CR panel (217× vs. 140× and 135× in its immediate neighbors), the interaction in action. The</span>
<span id="cb1-165"><a href="#cb1-165" aria-hidden="true" tabindex="-1"></a>corner cells also show plainly how close default's decode metrics already sit to uncompressed</span>
<span id="cb1-166"><a href="#cb1-166" aria-hidden="true" tabindex="-1"></a>(0.127 vs. 0.139 wheel R², 0.597 vs. 0.642 feedback) — and how much closer mild's sit (0.134</span>
<span id="cb1-167"><a href="#cb1-167" aria-hidden="true" tabindex="-1"></a>wheel R², 0.626 feedback) — and how far realized CR has to climb from uncompressed's 1×.</span>
<span id="cb1-168"><a href="#cb1-168" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-169"><a href="#cb1-169" aria-hidden="true" tabindex="-1"></a><span class="al">![Decoding metrics grouped by epsilon (hue = alpha), plotted as each recording's own delta from its default (150,28) cell — this removes the ~0.11 SD between-recording offset that hides the effect in raw values. Uncompressed (blue dash-dot line) is each recording's own delta between its uncompressed and default scores, since it doesn't sit at any (ε, α) x-position.](figures/2026-09-01_grid_boxplots_by_epsilon.png)</span>{#fig-grid-boxplots .lightbox}</span>
<span id="cb1-170"><a href="#cb1-170" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-171"><a href="#cb1-171" aria-hidden="true" tabindex="-1"></a><span class="al">![Total compressed size grouped by epsilon (hue = alpha), log scale, with the uncompressed total (20.4 GB, blue dash-dot line) for scale — every tested tier is at least ~40× smaller — and a secondary axis converting size directly to realized CR. The (450,96) bar is visibly shorter than its neighbors, again the interaction.](figures/2026-09-01_grid_barplot_size_by_epsilon.png)</span>{#fig-grid-barplot-log .lightbox}</span>
<span id="cb1-172"><a href="#cb1-172" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-173"><a href="#cb1-173" aria-hidden="true" tabindex="-1"></a><span class="al">![Same, linear scale (bars stay honestly zero-based; the uncompressed line is dropped here since at 20.4 GB it would flatten every bar to an invisible sliver) — makes the actual size differences between adjacent cells easier to judge than the log version above.](figures/2026-09-01_grid_barplot_size_by_epsilon_linear.png)</span>{#fig-grid-barplot-linear .lightbox}</span>
<span id="cb1-174"><a href="#cb1-174" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-175"><a href="#cb1-175" aria-hidden="true" tabindex="-1"></a>**Retained fraction** (below) is how much of the uncompressed decode a tier keeps: for wheel,</span>
<span id="cb1-176"><a href="#cb1-176" aria-hidden="true" tabindex="-1"></a><span class="in">`R²(tier) / R²(uncompressed)`</span>; for choice/feedback, `(balanced_accuracy(tier) - 0.5) /</span>
<span id="cb1-177"><a href="#cb1-177" aria-hidden="true" tabindex="-1"></a>(balanced_accuracy(uncompressed) - 0.5)` — chance-corrected, since balanced accuracy's floor is</span>
<span id="cb1-178"><a href="#cb1-178" aria-hidden="true" tabindex="-1"></a>0.5, not 0. 1.0 means indistinguishable from uncompressed.</span>
<span id="cb1-179"><a href="#cb1-179" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-180"><a href="#cb1-180" aria-hidden="true" tabindex="-1"></a>::: {.column-page}</span>
<span id="cb1-181"><a href="#cb1-181" aria-hidden="true" tabindex="-1"></a><span class="al">![Pareto: realized CR vs. retained decode fraction, one panel per target (marker size = alpha, colour = epsilon). Mild (green plus), default (red star) and aggressive (orange X) are labelled. Default sits on the frontier for wheel and near it for feedback; mild sits further up the fidelity axis at lower CR.](figures/2026-09-05_grid_pareto.png)</span>{#fig-grid-pareto .lightbox}</span>
<span id="cb1-182"><a href="#cb1-182" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-183"><a href="#cb1-183" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-184"><a href="#cb1-184" aria-hidden="true" tabindex="-1"></a>**The true Pareto frontier** (cells where no other cell has both higher realized CR and higher</span>
<span id="cb1-185"><a href="#cb1-185" aria-hidden="true" tabindex="-1"></a>retained feedback) contains 16 of the 42 cells, and default (150, 28) is on it — nothing</span>
<span id="cb1-186"><a href="#cb1-186" aria-hidden="true" tabindex="-1"></a>dominates it (@fig-grid-pareto). Mild (100, 14) sits further up the fidelity axis, at lower CR —</span>
<span id="cb1-187"><a href="#cb1-187" aria-hidden="true" tabindex="-1"></a>also on the frontier, the best-fidelity point tested. Stepping along the frontier past default is</span>
<span id="cb1-188"><a href="#cb1-188" aria-hidden="true" tabindex="-1"></a>a real, gradual trade the whole way: (300, 28) barely improves CR (89× vs. 87×) for a real</span>
<span id="cb1-189"><a href="#cb1-189" aria-hidden="true" tabindex="-1"></a>feedback cost (retained fraction 0.640 vs. 0.688); (350, 28) and (450, 28) are close together and</span>
<span id="cb1-190"><a href="#cb1-190" aria-hidden="true" tabindex="-1"></a>both meaningfully better value — (450, 28) reaches 100× for retained fraction 0.603, a small</span>
<span id="cb1-191"><a href="#cb1-191" aria-hidden="true" tabindex="-1"></a>further cost over (350, 28)'s 93×/0.605 for real extra compression. Past that, the frontier only</span>
<span id="cb1-192"><a href="#cb1-192" aria-hidden="true" tabindex="-1"></a>continues by also raising α, which is where the interaction — and the larger feedback cost —</span>
<span id="cb1-193"><a href="#cb1-193" aria-hidden="true" tabindex="-1"></a>kicks in.</span>
<span id="cb1-194"><a href="#cb1-194" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-195"><a href="#cb1-195" aria-hidden="true" tabindex="-1"></a><span class="fu">## Region decoding (brain-region classification)</span></span>
<span id="cb1-196"><a href="#cb1-196" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-197"><a href="#cb1-197" aria-hidden="true" tabindex="-1"></a>A second, independent functional check, run *after* the tier search above, at a much larger and</span>
<span id="cb1-198"><a href="#cb1-198" aria-hidden="true" tabindex="-1"></a>more heterogeneous scale (1099 PIDs, not 11) and on a completely different task — to see whether</span>
<span id="cb1-199"><a href="#cb1-199" aria-hidden="true" tabindex="-1"></a>the tier ranking found above is a real property of the codec or an artefact of the</span>
<span id="cb1-200"><a href="#cb1-200" aria-hidden="true" tabindex="-1"></a>wheel/choice/feedback validation's specific method.</span>
<span id="cb1-201"><a href="#cb1-201" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-202"><a href="#cb1-202" aria-hidden="true" tabindex="-1"></a><span class="fu">### Update 2026-10-01: lfpack v04 tiers (TS3 Cosmos benchmark)</span></span>
<span id="cb1-203"><a href="#cb1-203" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-204"><a href="#cb1-204" aria-hidden="true" tabindex="-1"></a>**The v04 <span class="in">`small`</span> tier (α = 14) decodes regions as well as v03 mild at 0.33× its size, and</span>
<span id="cb1-205"><a href="#cb1-205" aria-hidden="true" tabindex="-1"></a>lowering α keeps improving region decoding.** At equal α, the format-2 + shared-basis codec is</span>
<span id="cb1-206"><a href="#cb1-206" aria-hidden="true" tabindex="-1"></a>neutral, so region decoding, like behaviour decoding, depends only on α. Unlike behaviour</span>
<span id="cb1-207"><a href="#cb1-207" aria-hidden="true" tabindex="-1"></a>decoding, which is within noise at every v04 tier, region decoding still gains from α = 14 to</span>
<span id="cb1-208"><a href="#cb1-208" aria-hidden="true" tabindex="-1"></a>2.5: +2.5 pp 5-fold CV accuracy and +1.7 pp TS3 eval accuracy.</span>
<span id="cb1-209"><a href="#cb1-209" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-212"><a href="#cb1-212" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb1-213"><a href="#cb1-213" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb1-214"><a href="#cb1-214" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: tbl-ts3-v04</span></span>
<span id="cb1-215"><a href="#cb1-215" aria-hidden="true" tabindex="-1"></a><span class="co">#| tbl-cap: "TS3 Cosmos region classification per lfpack tier: mean ± s.e.m. over 3 model seeds (43/44/45), 3222 eval units. CV: 5-fold PID-grouped held-out accuracy on the 1054 training PIDs. 1/CR: file / uncompressed float32 at 250 Hz (1955.7 GB over 1099 PIDs)."</span></span>
<span id="cb1-216"><a href="#cb1-216" aria-hidden="true" tabindex="-1"></a>ts3 <span class="op">=</span> pd.read_csv(<span class="st">"2026-09-30_ts3_v04_region_decoding.csv"</span>)</span>
<span id="cb1-217"><a href="#cb1-217" aria-hidden="true" tabindex="-1"></a>UNCOMPRESSED_GB <span class="op">=</span> <span class="fl">1955.7</span></span>
<span id="cb1-218"><a href="#cb1-218" aria-hidden="true" tabindex="-1"></a>alpha <span class="op">=</span> {<span class="st">"v03-mild"</span>: <span class="st">"14"</span>, <span class="st">"v04-small"</span>: <span class="st">"14"</span>, <span class="st">"v04-default"</span>: <span class="st">"7"</span>, <span class="st">"v04-fine"</span>: <span class="st">"2.5"</span>}</span>
<span id="cb1-219"><a href="#cb1-219" aria-hidden="true" tabindex="-1"></a>g <span class="op">=</span> ts3.groupby(<span class="st">"tier"</span>, sort<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb1-220"><a href="#cb1-220" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-221"><a href="#cb1-221" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-222"><a href="#cb1-222" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> pm(col):</span>
<span id="cb1-223"><a href="#cb1-223" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> g[col].mean().<span class="bu">map</span>(<span class="st">"</span><span class="sc">{:.3f}</span><span class="st">"</span>.<span class="bu">format</span>) <span class="op">+</span> <span class="st">" ± "</span> <span class="op">+</span> g[col].sem().<span class="bu">map</span>(<span class="st">"</span><span class="sc">{:.3f}</span><span class="st">"</span>.<span class="bu">format</span>)</span>
<span id="cb1-224"><a href="#cb1-224" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-225"><a href="#cb1-225" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-226"><a href="#cb1-226" aria-hidden="true" tabindex="-1"></a>file_gb <span class="op">=</span> g[<span class="st">"file_gb"</span>].first()</span>
<span id="cb1-227"><a href="#cb1-227" aria-hidden="true" tabindex="-1"></a>pd.DataFrame({</span>
<span id="cb1-228"><a href="#cb1-228" aria-hidden="true" tabindex="-1"></a>    <span class="st">"α"</span>: pd.Series(alpha),</span>
<span id="cb1-229"><a href="#cb1-229" aria-hidden="true" tabindex="-1"></a>    <span class="st">"file (GB)"</span>: file_gb.<span class="bu">round</span>(<span class="dv">1</span>),</span>
<span id="cb1-230"><a href="#cb1-230" aria-hidden="true" tabindex="-1"></a>    <span class="st">"1/CR"</span>: (file_gb <span class="op">/</span> UNCOMPRESSED_GB).<span class="bu">map</span>(<span class="st">"</span><span class="sc">{:.2%}</span><span class="st">"</span>.<span class="bu">format</span>),</span>
<span id="cb1-231"><a href="#cb1-231" aria-hidden="true" tabindex="-1"></a>    <span class="st">"file / v03 mild"</span>: (file_gb <span class="op">/</span> file_gb[<span class="st">"v03-mild"</span>]).<span class="bu">round</span>(<span class="dv">2</span>),</span>
<span id="cb1-232"><a href="#cb1-232" aria-hidden="true" tabindex="-1"></a>    <span class="st">"accuracy"</span>: pm(<span class="st">"accuracy"</span>),</span>
<span id="cb1-233"><a href="#cb1-233" aria-hidden="true" tabindex="-1"></a>    <span class="st">"macro F1"</span>: pm(<span class="st">"macro_f1"</span>),</span>
<span id="cb1-234"><a href="#cb1-234" aria-hidden="true" tabindex="-1"></a>    <span class="st">"CV accuracy"</span>: pm(<span class="st">"cv_accuracy"</span>),</span>
<span id="cb1-235"><a href="#cb1-235" aria-hidden="true" tabindex="-1"></a>}).rename_axis(<span class="st">"tier"</span>)</span>
<span id="cb1-236"><a href="#cb1-236" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-237"><a href="#cb1-237" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-240"><a href="#cb1-240" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb1-241"><a href="#cb1-241" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb1-242"><a href="#cb1-242" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: tbl-ts3-v04-classes</span></span>
<span id="cb1-243"><a href="#cb1-243" aria-hidden="true" tabindex="-1"></a><span class="co">#| tbl-cap: "Per-class F1 (mean over 3 seeds) for the classes whose F1 moves by more than 0.05 across tiers (MB, 0.69–0.71, is left out). n: eval units per class."</span></span>
<span id="cb1-244"><a href="#cb1-244" aria-hidden="true" tabindex="-1"></a>n_units <span class="op">=</span> {<span class="st">"CB"</span>: <span class="dv">162</span>, <span class="st">"CNU"</span>: <span class="dv">187</span>, <span class="st">"CTXsp"</span>: <span class="dv">48</span>, <span class="st">"HB"</span>: <span class="dv">218</span>, <span class="st">"HPF"</span>: <span class="dv">323</span>, <span class="st">"HY"</span>: <span class="dv">54</span>,</span>
<span id="cb1-245"><a href="#cb1-245" aria-hidden="true" tabindex="-1"></a>           <span class="st">"Isocortex"</span>: <span class="dv">578</span>, <span class="st">"MB"</span>: <span class="dv">697</span>, <span class="st">"OLF"</span>: <span class="dv">265</span>, <span class="st">"TH"</span>: <span class="dv">690</span>}</span>
<span id="cb1-246"><a href="#cb1-246" aria-hidden="true" tabindex="-1"></a>f1 <span class="op">=</span> g[[<span class="ss">f"</span><span class="sc">{</span>c<span class="sc">}</span><span class="ss">_f1"</span> <span class="cf">for</span> c <span class="kw">in</span> n_units]].mean().T</span>
<span id="cb1-247"><a href="#cb1-247" aria-hidden="true" tabindex="-1"></a>f1.index <span class="op">=</span> [c.removesuffix(<span class="st">"_f1"</span>) <span class="cf">for</span> c <span class="kw">in</span> f1.index]</span>
<span id="cb1-248"><a href="#cb1-248" aria-hidden="true" tabindex="-1"></a>f1 <span class="op">=</span> f1[(f1.<span class="bu">max</span>(axis<span class="op">=</span><span class="dv">1</span>) <span class="op">-</span> f1.<span class="bu">min</span>(axis<span class="op">=</span><span class="dv">1</span>)) <span class="op">&gt;</span> <span class="fl">0.05</span>].<span class="bu">round</span>(<span class="dv">3</span>)</span>
<span id="cb1-249"><a href="#cb1-249" aria-hidden="true" tabindex="-1"></a>f1.insert(<span class="dv">0</span>, <span class="st">"n"</span>, pd.Series(n_units))</span>
<span id="cb1-250"><a href="#cb1-250" aria-hidden="true" tabindex="-1"></a>f1</span>
<span id="cb1-251"><a href="#cb1-251" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-252"><a href="#cb1-252" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-253"><a href="#cb1-253" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Equal α, smaller file: no loss.** v04 <span class="in">`small`</span> against v03 mild (both α = 14; format 2 and a</span>
<span id="cb1-254"><a href="#cb1-254" aria-hidden="true" tabindex="-1"></a>  shared spatial basis instead of format 1 and per-chunk U): accuracy 0.576 vs 0.572, macro F1</span>
<span id="cb1-255"><a href="#cb1-255" aria-hidden="true" tabindex="-1"></a>  0.444 vs 0.438, CV accuracy 0.518 vs 0.513. Every per-class F1 agrees within noise.</span>
<span id="cb1-256"><a href="#cb1-256" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Lower α helps region decoding.** CV accuracy rises monotonically, 0.518 → 0.538 → 0.544</span>
<span id="cb1-257"><a href="#cb1-257" aria-hidden="true" tabindex="-1"></a>  (α = 14 → 7 → 2.5), and so does eval accuracy, 0.576 → 0.580 → 0.593. Isocortex, CB, OLF and</span>
<span id="cb1-258"><a href="#cb1-258" aria-hidden="true" tabindex="-1"></a>  HB gain the most; TH and HPF lose 0.1 F1, so lower α also shifts which regions get predicted.</span>
<span id="cb1-259"><a href="#cb1-259" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Eval macro F1 peaks at `default`** (0.513 vs <span class="in">`fine`</span>'s 0.489). That comes almost entirely</span>
<span id="cb1-260"><a href="#cb1-260" aria-hidden="true" tabindex="-1"></a>  from HY (0.57 vs 0.16, 54 units) and CTXsp (48 units). Classes that small, from 29 sessions,</span>
<span id="cb1-261"><a href="#cb1-261" aria-hidden="true" tabindex="-1"></a>  make macro F1 noisy, so CV accuracy (330k channels) is the more reliable ranking.</span>
<span id="cb1-262"><a href="#cb1-262" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Paired design.** Same 1099 PIDs, same saturation-avoided snippet start times (saturation</span>
<span id="cb1-263"><a href="#cb1-263" aria-hidden="true" tabindex="-1"></a>  comes from the raw ADC signal and the Cadzow checkpoints are shared), same 5-fold split, same</span>
<span id="cb1-264"><a href="#cb1-264" aria-hidden="true" tabindex="-1"></a>  ground truth. Only the archive changes.</span>
<span id="cb1-265"><a href="#cb1-265" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>The v03 mild baseline was rescored from its existing channel predictions on the current eval</span>
<span id="cb1-266"><a href="#cb1-266" aria-hidden="true" tabindex="-1"></a>  build. That build has 3222 units, up from 3209, so the 2026-09-04 single-run score (0.584 /</span>
<span id="cb1-267"><a href="#cb1-267" aria-hidden="true" tabindex="-1"></a>  0.416) is not directly comparable.</span>
<span id="cb1-268"><a href="#cb1-268" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-269"><a href="#cb1-269" aria-hidden="true" tabindex="-1"></a>Code: <span class="in">`~/Documents/ibldevtools/olivier/2026-09-04_ts3-lfp-baseline/`</span> (<span class="in">`LFPACK_TIER`</span> env var in</span>
<span id="cb1-270"><a href="#cb1-270" aria-hidden="true" tabindex="-1"></a><span class="in">`paths.py`</span>; <span class="in">`score_tiers.py`</span> writes <span class="in">`2026-09-30_ts3_v04_region_decoding.csv`</span>).</span>
<span id="cb1-271"><a href="#cb1-271" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-272"><a href="#cb1-272" aria-hidden="true" tabindex="-1"></a><span class="fu">### Method</span></span>
<span id="cb1-273"><a href="#cb1-273" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-274"><a href="#cb1-274" aria-hidden="true" tabindex="-1"></a>Per-recording LF-band-power and CSD features (raw_lf + raw_lf_csd feature families, 33 columns,</span>
<span id="cb1-275"><a href="#cb1-275" aria-hidden="true" tabindex="-1"></a><span class="in">`ephysatlas.features.voltage_features_set`</span>) are computed identically for every LFP source from</span>
<span id="cb1-276"><a href="#cb1-276" aria-hidden="true" tabindex="-1"></a>~8 snippets/PID (8.79 s windows, 600 s spacing, matching the canonical ephys-atlas snippet</span>
<span id="cb1-277"><a href="#cb1-277" aria-hidden="true" tabindex="-1"></a>grid), aggregated into one channel-level table, then classified with the canonical ephys-atlas</span>
<span id="cb1-278"><a href="#cb1-278" aria-hidden="true" tabindex="-1"></a>XGBoost pipeline (5-fold **PID-grouped** CV, Cosmos-level labels, `VINTAGE =</span>
<span id="cb1-279"><a href="#cb1-279" aria-hidden="true" tabindex="-1"></a>"2026-08_lfp-decoders"`).</span>
<span id="cb1-280"><a href="#cb1-280" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-281"><a href="#cb1-281" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> LFP source <span class="pp">|</span> Read from <span class="pp">|</span> Notes <span class="pp">|</span></span>
<span id="cb1-282"><a href="#cb1-282" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---|---|</span></span>
<span id="cb1-283"><a href="#cb1-283" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`uncompressed`</span> <span class="pp">|</span> <span class="in">`lf_resampled_car_cadzow.npy`</span> (Cadzow checkpoint, pre-SVD/WP) <span class="pp">|</span> reference — already on the compute cluster <span class="pp">|</span></span>
<span id="cb1-284"><a href="#cb1-284" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`mild`</span> <span class="pp">|</span> <span class="in">`lf_compressed_mild_all.h5`</span> <span class="pp">|</span> lfpack SVD+WP ε=100, α=14 <span class="pp">|</span></span>
<span id="cb1-285"><a href="#cb1-285" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`default`</span> <span class="pp">|</span> <span class="in">`lf_compressed_all.h5`</span> <span class="pp">|</span> lfpack SVD+WP ε=150, α=28 <span class="pp">|</span></span>
<span id="cb1-286"><a href="#cb1-286" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`aggressive`</span> <span class="pp">|</span> <span class="in">`lf_compressed_aggressive_all.h5`</span> <span class="pp">|</span> lfpack SVD+WP ε=450, α=96 <span class="pp">|</span></span>
<span id="cb1-287"><a href="#cb1-287" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-288"><a href="#cb1-288" aria-hidden="true" tabindex="-1"></a>Two snippet-selection modes are compared per source (except <span class="in">`mild`</span>, run only at full-cohort</span>
<span id="cb1-289"><a href="#cb1-289" aria-hidden="true" tabindex="-1"></a>scale for <span class="in">`all`</span> — see <span class="co">[</span><span class="ot">Recap</span><span class="co">](#recap)</span>): naive (<span class="in">`all`</span>) vs. **saturation-avoided**, which drops</span>
<span id="cb1-290"><a href="#cb1-290" aria-hidden="true" tabindex="-1"></a>snippets overlapping an ADC-saturated interval. This isolates the saturation question from the</span>
<span id="cb1-291"><a href="#cb1-291" aria-hidden="true" tabindex="-1"></a>compression question directly, on the same cohort.</span>
<span id="cb1-292"><a href="#cb1-292" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-293"><a href="#cb1-293" aria-hidden="true" tabindex="-1"></a>Cohort: every histology-resolved insertion in <span class="in">`ibl_neuropixel_brainwide_01`</span> (the ephys-atlas</span>
<span id="cb1-294"><a href="#cb1-294" aria-hidden="true" tabindex="-1"></a>cohort — a strict superset of the curated ~700-PID BWM behavioural cohort), **1099 PIDs, 407616</span>
<span id="cb1-295"><a href="#cb1-295" aria-hidden="true" tabindex="-1"></a>channels** per source/mode combination.</span>
<span id="cb1-296"><a href="#cb1-296" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-297"><a href="#cb1-297" aria-hidden="true" tabindex="-1"></a><span class="fu">### Does compression hurt region decoding?</span></span>
<span id="cb1-298"><a href="#cb1-298" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-301"><a href="#cb1-301" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb1-302"><a href="#cb1-302" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb1-303"><a href="#cb1-303" aria-hidden="true" tabindex="-1"></a>r <span class="op">=</span> pd.read_csv(<span class="st">"2026-09-05_region_decoding_metrics.csv"</span>)</span>
<span id="cb1-304"><a href="#cb1-304" aria-hidden="true" tabindex="-1"></a>order <span class="op">=</span> [<span class="st">"uncompressed"</span>, <span class="st">"mild"</span>, <span class="st">"default"</span>, <span class="st">"aggressive"</span>]</span>
<span id="cb1-305"><a href="#cb1-305" aria-hidden="true" tabindex="-1"></a>r[<span class="st">"lfp_source"</span>] <span class="op">=</span> pd.Categorical(r[<span class="st">"lfp_source"</span>], categories<span class="op">=</span>order, ordered<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb1-306"><a href="#cb1-306" aria-hidden="true" tabindex="-1"></a>r.sort_values([<span class="st">"lfp_source"</span>, <span class="st">"snippet_mode"</span>])[</span>
<span id="cb1-307"><a href="#cb1-307" aria-hidden="true" tabindex="-1"></a>    [<span class="st">"lfp_source"</span>, <span class="st">"snippet_mode"</span>, <span class="st">"accuracy"</span>, <span class="st">"n_pids"</span>, <span class="st">"n_channels"</span>]</span>
<span id="cb1-308"><a href="#cb1-308" aria-hidden="true" tabindex="-1"></a>].reset_index(drop<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb1-309"><a href="#cb1-309" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-310"><a href="#cb1-310" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-311"><a href="#cb1-311" aria-hidden="true" tabindex="-1"></a><span class="al">![Impact of LFP compression tier on region decoding — mean accuracy (Cosmos, held-out) across 1099 PIDs, snippet_mode="all". Same ranking as the wheel/choice/feedback validation.](figures/2026-09-05_lfp-decoders_compression-impact.png)</span>{#fig-region-compression-impact .lightbox}</span>
<span id="cb1-312"><a href="#cb1-312" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-313"><a href="#cb1-313" aria-hidden="true" tabindex="-1"></a>Compression clearly costs region-decoding accuracy, and the cost is monotonic with compression</span>
<span id="cb1-314"><a href="#cb1-314" aria-hidden="true" tabindex="-1"></a>aggressiveness (@fig-region-compression-impact): uncompressed (0.468) &gt; mild (0.435, −3.3pp) &gt;</span>
<span id="cb1-315"><a href="#cb1-315" aria-hidden="true" tabindex="-1"></a>default (0.420, −4.8pp) &gt; aggressive (0.389, −7.9pp vs. uncompressed). This mirrors the</span>
<span id="cb1-316"><a href="#cb1-316" aria-hidden="true" tabindex="-1"></a>wheel/choice/feedback validation's ranking exactly, on a completely different task, decoder, and</span>
<span id="cb1-317"><a href="#cb1-317" aria-hidden="true" tabindex="-1"></a>cohort scale — strong evidence that the compression-tier ordering is a real property of the</span>
<span id="cb1-318"><a href="#cb1-318" aria-hidden="true" tabindex="-1"></a>codec, not an artefact of one validation's specific method.</span>
<span id="cb1-319"><a href="#cb1-319" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-320"><a href="#cb1-320" aria-hidden="true" tabindex="-1"></a><span class="fu">### Does avoiding saturated snippets help?</span></span>
<span id="cb1-321"><a href="#cb1-321" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-322"><a href="#cb1-322" aria-hidden="true" tabindex="-1"></a>!<span class="co">[</span><span class="ot">Impact of ADC saturation avoidance on region decoding — bars: mean ± SD across 5 folds; dots: individual folds. Restricted to the three sources with both snippet modes (`mild` is `all`-only, see [Recap](#recap)).</span><span class="co">](figures/2026-09-05_lfp-decoders_saturation-impact.png)</span>{#fig-region-saturation-impact .lightbox}</span>
<span id="cb1-323"><a href="#cb1-323" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-324"><a href="#cb1-324" aria-hidden="true" tabindex="-1"></a>Small and inconsistent in direction (@fig-region-saturation-impact): default drops slightly</span>
<span id="cb1-325"><a href="#cb1-325" aria-hidden="true" tabindex="-1"></a>avoiding saturation (−0.3pp), aggressive and uncompressed both gain slightly (+0.3pp, +0.2pp) —</span>
<span id="cb1-326"><a href="#cb1-326" aria-hidden="true" tabindex="-1"></a>all differences are within the fold-to-fold spread seen within a single combo's own 5 folds.</span>
<span id="cb1-327"><a href="#cb1-327" aria-hidden="true" tabindex="-1"></a>Avoiding ADC-saturated snippets does not meaningfully change region-decoding accuracy at this</span>
<span id="cb1-328"><a href="#cb1-328" aria-hidden="true" tabindex="-1"></a>snippet-selection scale — a separate axis from the compression-tier effect above, and not</span>
<span id="cb1-329"><a href="#cb1-329" aria-hidden="true" tabindex="-1"></a>something saturation handling needs to trade off against.</span>
<span id="cb1-330"><a href="#cb1-330" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-331"><a href="#cb1-331" aria-hidden="true" tabindex="-1"></a><span class="fu">### Recap {#recap}</span></span>
<span id="cb1-332"><a href="#cb1-332" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-333"><a href="#cb1-333" aria-hidden="true" tabindex="-1"></a><span class="al">![Full numeric recap: accuracy mean/SD/min/max across folds, sample sizes, per source × snippet mode.](figures/2026-09-05_lfp-decoders_recap-table.png)</span>{#fig-region-recap-table .lightbox}</span>
<span id="cb1-334"><a href="#cb1-334" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-335"><a href="#cb1-335" aria-hidden="true" tabindex="-1"></a><span class="in">`mild`</span> was added to this validation after the wheel/choice/feedback grid had already identified</span>
<span id="cb1-336"><a href="#cb1-336" aria-hidden="true" tabindex="-1"></a>ε=100/α=14 as the best-fidelity operating point worth naming and shipping (see</span>
<span id="cb1-337"><a href="#cb1-337" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">Full 2D grid</span><span class="co">](#full-2d-grid)</span> above) — run only at <span class="in">`snippet_mode="all"`</span> full-cohort scale, not</span>
<span id="cb1-338"><a href="#cb1-338" aria-hidden="true" tabindex="-1"></a><span class="in">`saturation-avoided`</span>, since the saturation question was already answered by the other three</span>
<span id="cb1-339"><a href="#cb1-339" aria-hidden="true" tabindex="-1"></a>sources and doesn't need re-litigating per tier (@fig-region-recap-table).</span>
<span id="cb1-340"><a href="#cb1-340" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-341"><a href="#cb1-341" aria-hidden="true" tabindex="-1"></a><span class="fu">## Recommendation</span></span>
<span id="cb1-342"><a href="#cb1-342" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-343"><a href="#cb1-343" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Keep default (ε=150, α=28)** as the standard cohort-wide tier — it's Pareto-efficient on the</span>
<span id="cb1-344"><a href="#cb1-344" aria-hidden="true" tabindex="-1"></a>  behavioural grid, and every tested alternative in that direction trades away real feedback</span>
<span id="cb1-345"><a href="#cb1-345" aria-hidden="true" tabindex="-1"></a>  fidelity.</span>
<span id="cb1-346"><a href="#cb1-346" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Use mild (ε=100, α=14) for the highest fidelity.** Named and shipped as a third production</span>
<span id="cb1-347"><a href="#cb1-347" aria-hidden="true" tabindex="-1"></a>  tier: realized CR 48× (vs. default's 87×, uncompressed's 1×), feedback balanced accuracy 0.626</span>
<span id="cb1-348"><a href="#cb1-348" aria-hidden="true" tabindex="-1"></a>  vs. default's 0.597 and uncompressed's 0.642 — a chance-corrected retained-feedback-fraction of</span>
<span id="cb1-349"><a href="#cb1-349" aria-hidden="true" tabindex="-1"></a>  **0.89** vs. default's 0.68. Confirmed independently at full ephys-atlas cohort scale (1099</span>
<span id="cb1-350"><a href="#cb1-350" aria-hidden="true" tabindex="-1"></a>  PIDs) by the region-decoding validation above (0.435 vs. default's 0.420, uncompressed's</span>
<span id="cb1-351"><a href="#cb1-351" aria-hidden="true" tabindex="-1"></a>  0.468).</span>
<span id="cb1-352"><a href="#cb1-352" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**If more compression is required, use ε=450, α=28** — 100× realized CR (0.211 GB vs.</span>
<span id="cb1-353"><a href="#cb1-353" aria-hidden="true" tabindex="-1"></a>  default's 0.242 GB across the 11 recordings, both tiny next to uncompressed's 20.4 GB), R²</span>
<span id="cb1-354"><a href="#cb1-354" aria-hidden="true" tabindex="-1"></a>  0.122 vs. default's 0.127, feedback balanced accuracy 0.585 vs. default's 0.597. That</span>
<span id="cb1-355"><a href="#cb1-355" aria-hidden="true" tabindex="-1"></a>  feedback gap is not statistically distinguishable from between-recording noise (paired</span>
<span id="cb1-356"><a href="#cb1-356" aria-hidden="true" tabindex="-1"></a>  Wilcoxon p=0.17) — the best-value, lowest-risk upgrade found on the whole grid.</span>
<span id="cb1-357"><a href="#cb1-357" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Retire the aggressive tier (ε=450, α=96).** Nothing between ε=450/α=28 and aggressive is</span>
<span id="cb1-358"><a href="#cb1-358" aria-hidden="true" tabindex="-1"></a>  worth shipping — the frontier only gets there by also raising α, which is where the real,</span>
<span id="cb1-359"><a href="#cb1-359" aria-hidden="true" tabindex="-1"></a>  significant decoding cost (p=0.005) lives, and the largest region-decoding cost measured</span>
<span id="cb1-360"><a href="#cb1-360" aria-hidden="true" tabindex="-1"></a>  (−7.9pp vs. uncompressed).</span>
<span id="cb1-361"><a href="#cb1-361" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Build command** (per-recording, ≈10–60 s from the existing Cadzow checkpoint, no</span>
<span id="cb1-362"><a href="#cb1-362" aria-hidden="true" tabindex="-1"></a>  re-download needed): `lfpack.compress_to_h5(cadzow_npy, out_h5, recording=pid, epsilon=450.0,</span>
<span id="cb1-363"><a href="#cb1-363" aria-hidden="true" tabindex="-1"></a>  alpha=28.0, fs=250.0, ...)`.</span>
<span id="cb1-364"><a href="#cb1-364" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-365"><a href="#cb1-365" aria-hidden="true" tabindex="-1"></a><span class="fu">## Code</span></span>
<span id="cb1-366"><a href="#cb1-366" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-367"><a href="#cb1-367" aria-hidden="true" tabindex="-1"></a>**Behavioural decoding**: <span class="in">`oliche-quarto/analyses/2026-06-lfp-compression-svd/`</span> —</span>
<span id="cb1-368"><a href="#cb1-368" aria-hidden="true" tabindex="-1"></a><span class="in">`compression_benchmark.py`</span>, <span class="in">`svd_adaptive_wp.py`</span> and the dated</span>
<span id="cb1-369"><a href="#cb1-369" aria-hidden="true" tabindex="-1"></a><span class="in">`2026-08-31_LFP_compression_*.py`</span> / <span class="in">`2026-08-31_LFP_compression_full_grid_displays.py`</span> scripts</span>
<span id="cb1-370"><a href="#cb1-370" aria-hidden="true" tabindex="-1"></a>under <span class="in">`~/Documents/ibldevtools/olivier/`</span> (sweep computation + this page's figures). The <span class="in">`mild`</span></span>
<span id="cb1-371"><a href="#cb1-371" aria-hidden="true" tabindex="-1"></a>tier was added after the fact by <span class="in">`2026-09-05_LFP_compression_decoding_add_mild.py`</span> /</span>
<span id="cb1-372"><a href="#cb1-372" aria-hidden="true" tabindex="-1"></a><span class="in">`2026-09-05_LFP_compression_decoding_categorical_add_mild.py`</span> (reuse the already-computed</span>
<span id="cb1-373"><a href="#cb1-373" aria-hidden="true" tabindex="-1"></a>uncompressed/default/aggressive rows, decode only the new variant, regenerate @fig-r2-by-pid /</span>
<span id="cb1-374"><a href="#cb1-374" aria-hidden="true" tabindex="-1"></a>@fig-categorical-boxplot) and directly in</span>
<span id="cb1-375"><a href="#cb1-375" aria-hidden="true" tabindex="-1"></a><span class="in">`2026-08-31_LFP_compression_full_grid_displays.py`</span> (@fig-grid-heatmaps / @fig-grid-pareto</span>
<span id="cb1-376"><a href="#cb1-376" aria-hidden="true" tabindex="-1"></a>already covered the ε=100/α=14 cell — only the mild/default/aggressive highlight markers were</span>
<span id="cb1-377"><a href="#cb1-377" aria-hidden="true" tabindex="-1"></a>added), same directory.</span>
<span id="cb1-378"><a href="#cb1-378" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-379"><a href="#cb1-379" aria-hidden="true" tabindex="-1"></a>**Region decoding**: <span class="in">`sdsc-slurms/2026-08_lfp-decoders/`</span> — <span class="in">`extract.py`</span> (per-PID/per-snippet</span>
<span id="cb1-380"><a href="#cb1-380" aria-hidden="true" tabindex="-1"></a>LF+CSD feature extraction, joblib-parallel), <span class="in">`aggregate.py`</span> (thin wrapper around</span>
<span id="cb1-381"><a href="#cb1-381" aria-hidden="true" tabindex="-1"></a><span class="in">`ephysatlas.aggregation.produce_output_dataframes`</span>), <span class="in">`train_classifier.py`</span> (5-fold PID-grouped</span>
<span id="cb1-382"><a href="#cb1-382" aria-hidden="true" tabindex="-1"></a>XGBoost), <span class="in">`report.py`</span> (this section's table + figures, run locally after rsyncing</span>
<span id="cb1-383"><a href="#cb1-383" aria-hidden="true" tabindex="-1"></a><span class="in">`accuracy.json`</span> back from the cluster). Region annotations (<span class="in">`atlas_id`</span>/<span class="in">`acronym`</span>/<span class="in">`x`</span>/<span class="in">`y`</span>/<span class="in">`z`</span>)</span>
<span id="cb1-384"><a href="#cb1-384" aria-hidden="true" tabindex="-1"></a>come embedded in each lfpack archive via <span class="in">`attach_ibl_metadata.py`</span></span>
<span id="cb1-385"><a href="#cb1-385" aria-hidden="true" tabindex="-1"></a>(<span class="in">`sdsc-slurms/2026-06-lfpack/`</span>).</span>
</code></pre></div><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>Olivier Winter</p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>
<script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","descPosition":"bottom","loop":false,"openEffect":"zoom","selector":".lightbox"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script>




</body></html>