<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Olivier Winter">
<meta name="dcterms.date" content="2026-06-09">
<meta name="description" content="Benchmarking SVD-based LFP compression methods on 11 Neuropixels insertions, evaluating RMSE and SNR across compression ratios up to 3000×.">

<title>LFP Compression Benchmark: SVD and Adaptive SVD+WP Methods – Analysis Hub</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-acf12a64177840b8d86f2d4f01b2e9fb.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-997f3bee8414e4416227c4bdeef383f8.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="../../site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="../../site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="../../site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Analysis Hub</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Analyses</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/oliche"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#overview" id="toc-overview" class="nav-link active" data-scroll-target="#overview">Overview</a></li>
  <li><a href="#pre-processing-pipeline" id="toc-pre-processing-pipeline" class="nav-link" data-scroll-target="#pre-processing-pipeline">Pre-processing pipeline</a></li>
  <li><a href="#compression-methods" id="toc-compression-methods" class="nav-link" data-scroll-target="#compression-methods">Compression methods</a></li>
  <li><a href="#metrics" id="toc-metrics" class="nav-link" data-scroll-target="#metrics">Metrics</a></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results">Results</a>
  <ul class="collapse">
  <li><a href="#aggregate-benchmark-11-pids" id="toc-aggregate-benchmark-11-pids" class="nav-link" data-scroll-target="#aggregate-benchmark-11-pids">Aggregate benchmark (11 PIDs)</a></li>
  <li><a href="#svd-spectrum-and-ε-calibration" id="toc-svd-spectrum-and-ε-calibration" class="nav-link" data-scroll-target="#svd-spectrum-and-ε-calibration">SVD spectrum and ε calibration</a></li>
  <li><a href="#adaptive-wp-threshold-calibration" id="toc-adaptive-wp-threshold-calibration" class="nav-link" data-scroll-target="#adaptive-wp-threshold-calibration">Adaptive WP threshold calibration</a></li>
  <li><a href="#parameter-sweep-gallery-svd-ε-wp-α" id="toc-parameter-sweep-gallery-svd-ε-wp-α" class="nav-link" data-scroll-target="#parameter-sweep-gallery-svd-ε-wp-α">Parameter sweep gallery (SVD-ε × WP-α)</a></li>
  <li><a href="#csd-gallery-pid-dab512bd" id="toc-csd-gallery-pid-dab512bd" class="nav-link" data-scroll-target="#csd-gallery-pid-dab512bd">CSD gallery (PID dab512bd)</a></li>
  </ul></li>
  <li><a href="#appendix-per-insertion-results" id="toc-appendix-per-insertion-results" class="nav-link" data-scroll-target="#appendix-per-insertion-results">Appendix: Per-insertion results</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">LFP Compression Benchmark: SVD and Adaptive SVD+WP Methods</h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
  <div class="quarto-categories">
    <div class="quarto-category">electrophysiology</div>
    <div class="quarto-category">LFP</div>
    <div class="quarto-category">compression</div>
    <div class="quarto-category">Neuropixels</div>
  </div>
  </div>

<div>
  <div class="description">
    Benchmarking SVD-based LFP compression methods on 11 Neuropixels insertions, evaluating RMSE and SNR across compression ratios up to 3000×.
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Olivier Winter </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">June 9, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="overview" class="level2">
<h2 class="anchored" data-anchor-id="overview">Overview</h2>
<p>The IBL holds <strong>936 hours</strong> of Brainwide Map (BWM) recordings and <strong>1472 hours</strong> from the Ephys Atlas. Raw LFP at 2500 Hz, 384 channels, float32 amounts to ~12 TB for the BWM alone. After standard preprocessing (bad-channel rejection, 2–250 Hz bandpass, ×10 decimation to 250 Hz), the footprint shrinks to ~1.2 Tb — still too large for routine distribution or streaming. The goal is to identify a lossy compression strategy that reduces this further.</p>
<p><strong>Practical recommendation: SVD + WP (ε≈150, α≈28) gives total CR≈125 (104-181) with RMSE≈15 µV and SNR≈10 dB.</strong> <strong>This would shrink the 936-hour BWM dataset to ~9.6 Gb.</strong></p>
</section>
<section id="pre-processing-pipeline" class="level2">
<h2 class="anchored" data-anchor-id="pre-processing-pipeline">Pre-processing pipeline</h2>
<p>Raw LFP (NP1, 2500 Hz, <code>.cbin</code>) was preprocessed before benchmarking:</p>
<ol type="1">
<li><strong>Bad-channel detection</strong> — channels with anomalous variance flagged and excluded.</li>
<li><strong>Bandpass + CAR + decimation</strong> — 2–250 Hz FIR bandpass, common-average referencing, ×10 FIR decimation → 250 Hz float32.</li>
<li><strong>Cadzow PPCA spatial denoising</strong> — F-X Cadzow on 3 s snippets (nw=64, f_max=100 Hz, max rank r=5, adaptive rank via singular-value gap threshold=2.0, PPCA outlier k=2.0) to remove incoherent channel noise.</li>
</ol>
<p>All methods were benchmarked on the Cadzow-denoised snippets so residuals reflect compression loss, not pre-existing noise.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="figures/2026-06-06_cadzow_e8f9fba4-d151-4b00-bee7-447f0f3e752c.png" class="lightbox" data-gallery="quarto-lightbox-gallery-1" title="Cadzow denoising for PID e8f9fba4. Three 3 s snippets (rows): original / denoised (adaptive rank) / difference (same colour scale)."><img src="figures/2026-06-06_cadzow_e8f9fba4-d151-4b00-bee7-447f0f3e752c.png" class="img-fluid figure-img" alt="Cadzow denoising for PID e8f9fba4. Three 3 s snippets (rows): original / denoised (adaptive rank) / difference (same colour scale)."></a></p>
<figcaption>Cadzow denoising for PID e8f9fba4. Three 3 s snippets (rows): original / denoised (adaptive rank) / difference (same colour scale).</figcaption>
</figure>
</div>
</section>
<section id="compression-methods" class="level2">
<h2 class="anchored" data-anchor-id="compression-methods">Compression methods</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Method</th>
<th>Principle</th>
<th>CR formula</th>
<th>Parameters</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>SVD-adapt</strong></td>
<td>First-stage: truncated SVD with adaptive rank: retain components where <span class="math inline">\(s_k &gt; \varepsilon \cdot \sigma_0\)</span>, with <span class="math inline">\(\sigma_0 = \text{median}(\text{lower half of } s)\)</span> as the noise-floor estimate. <span class="math inline">\(\varepsilon\)</span> is swept to cover the full CR range.</td>
<td><span class="math inline">\(n_c n_s / (r_\varepsilon(n_c+n_s))\)</span></td>
<td>ε ∈ logspace(10⁴, 10⁻¹, 30)</td>
</tr>
<tr class="even">
<td><strong>WP</strong></td>
<td>Second-stage: db4 wavelet-packet adaptive thresholding on the <span class="math inline">\(r\)</span> temporal rows of <span class="math inline">\(V_r^\top\)</span>. Per-component threshold <span class="math inline">\(\tau_k = \alpha \sigma_0 / \sigma_k\)</span> ensures uniform error contribution across all ranks.</td>
<td><span class="math inline">\(\text{CR}_\text{SVD} \times \text{CR}_\text{WP}\)</span></td>
<td>ε (SVD stage), α (WP stage)</td>
</tr>
</tbody>
</table>
</section>
<section id="metrics" class="level2">
<h2 class="anchored" data-anchor-id="metrics">Metrics</h2>
<p><span class="math display">\[\text{RMSE}(c) = \left\langle \sqrt{\left\langle (x - \hat{x})^2 \right\rangle_t} \right\rangle_{\text{snippets}} \quad [\mu\text{V}] \qquad \text{SNR}(c) = 20 \cdot \log_{10} \left( \frac{\text{RMS}(c)}{\text{RMSE}(c)} \right) \quad [\text{dB}]\]</span></p>
<p>Aggregated as median over channels, then mean over 11 PIDs.</p>
</section>
<section id="results" class="level2">
<h2 class="anchored" data-anchor-id="results">Results</h2>
<section id="aggregate-benchmark-11-pids" class="level3">
<h3 class="anchored" data-anchor-id="aggregate-benchmark-11-pids">Aggregate benchmark (11 PIDs)</h3>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="figures/2026-06-12_adaptive_wp_aggregate.png" class="lightbox" data-gallery="quarto-lightbox-gallery-2" title="Adaptive SVD+WP aggregate quality. Left: median RMSE (µV, log–log) vs total CR; right: median SNR (dB) vs total CR. One curve per SVD-stage CR; α values labelled at each operating point."><img src="figures/2026-06-12_adaptive_wp_aggregate.png" class="img-fluid figure-img" alt="Adaptive SVD+WP aggregate quality. Left: median RMSE (µV, log–log) vs total CR; right: median SNR (dB) vs total CR. One curve per SVD-stage CR; α values labelled at each operating point."></a></p>
<figcaption>Adaptive SVD+WP aggregate quality. Left: median RMSE (µV, log–log) vs total CR; right: median SNR (dB) vs total CR. One curve per SVD-stage CR; α values labelled at each operating point.</figcaption>
</figure>
</div>
<p>Each curve sweeps α from 0 (single stage SVD) through 64 (aggressive WP thresholding). All curves eventually converge from CR≈100 (α≈24), meaning the wavepack is eventually catching up.</p>
</section>
<section id="svd-spectrum-and-ε-calibration" class="level3">
<h3 class="anchored" data-anchor-id="svd-spectrum-and-ε-calibration">SVD spectrum and ε calibration</h3>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="figures/2026-06-10_epsilon_vs_rank.png" class="lightbox" data-gallery="quarto-lightbox-gallery-3" title="Left: for each PID, \varepsilon(r) = s_r / \sigma_0 — the signal-to-noise-floor ratio of the r-th singular value — vs rank (bottom axis, 1–96). This is the \varepsilon that would select exactly rank r. Right: singular value s_r (µV) vs rank, with the per-PID noise floor \sigma_0 shown as a dashed horizontal line. The secondary top axis shows the compression ratio at each rank."><img src="figures/2026-06-10_epsilon_vs_rank.png" class="img-fluid figure-img" alt="Left: for each PID, \varepsilon(r) = s_r / \sigma_0 — the signal-to-noise-floor ratio of the r-th singular value — vs rank (bottom axis, 1–96). This is the \varepsilon that would select exactly rank r. Right: singular value s_r (µV) vs rank, with the per-PID noise floor \sigma_0 shown as a dashed horizontal line. The secondary top axis shows the compression ratio at each rank."></a></p>
<figcaption>Left: for each PID, <span class="math inline">\(\varepsilon(r) = s_r / \sigma_0\)</span> — the signal-to-noise-floor ratio of the <span class="math inline">\(r\)</span>-th singular value — vs rank (bottom axis, 1–96). This is the <span class="math inline">\(\varepsilon\)</span> that would select exactly rank <span class="math inline">\(r\)</span>. Right: singular value <span class="math inline">\(s_r\)</span> (µV) vs rank, with the per-PID noise floor <span class="math inline">\(\sigma_0\)</span> shown as a dashed horizontal line. The secondary top axis shows the <strong>compression ratio</strong> at each rank.</figcaption>
</figure>
</div>
<p>Median ε values (and range across 11 PIDs) that select each evaluated rank:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: right;">Rank</th>
<th style="text-align: right;">ε median</th>
<th style="text-align: left;">ε range</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">4073</td>
<td style="text-align: left;">2772–4697</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: right;">2252</td>
<td style="text-align: left;">1540–2898</td>
</tr>
<tr class="odd">
<td style="text-align: right;">4</td>
<td style="text-align: right;">909</td>
<td style="text-align: left;">574–1240</td>
</tr>
<tr class="even">
<td style="text-align: right;">8</td>
<td style="text-align: right;">461</td>
<td style="text-align: left;">255–584</td>
</tr>
<tr class="odd">
<td style="text-align: right;">16</td>
<td style="text-align: right;">155</td>
<td style="text-align: left;">89–207</td>
</tr>
<tr class="even">
<td style="text-align: right;">32</td>
<td style="text-align: right;">47</td>
<td style="text-align: left;">22–73</td>
</tr>
<tr class="odd">
<td style="text-align: right;">64</td>
<td style="text-align: right;">10</td>
<td style="text-align: left;">4–22</td>
</tr>
<tr class="even">
<td style="text-align: right;">96</td>
<td style="text-align: right;">4</td>
<td style="text-align: left;">1–10</td>
</tr>
</tbody>
</table>
</section>
<section id="adaptive-wp-threshold-calibration" class="level3">
<h3 class="anchored" data-anchor-id="adaptive-wp-threshold-calibration">Adaptive WP threshold calibration</h3>
<p>After SVD truncation at rank <span class="math inline">\(r\)</span>, each temporal component <span class="math inline">\(V_k\)</span> (a row of <span class="math inline">\(V_r^\top\)</span>, unit-L2-norm) is wavelet-packet compressed with a per-component hard threshold:</p>
<p><span class="math display">\[\tau_k = \frac{\alpha \cdot \sigma_0}{\sigma_k}\]</span></p>
<p>where <span class="math inline">\(\sigma_0\)</span> is the same SVD noise floor used for ε-based rank selection, <span class="math inline">\(\sigma_k\)</span> is the singular value of component <span class="math inline">\(k\)</span>, and <span class="math inline">\(\alpha\)</span> is a single global multiplier. The threshold ensures every discarded coefficient contributes less than <span class="math inline">\(\alpha \cdot \sigma_0\)</span> — uniform across all components regardless of their amplitude.</p>
<ul>
<li>Dominant components (large <span class="math inline">\(\sigma_k\)</span>) receive a small threshold → many WP coefficients retained.</li>
<li>Weak components (small <span class="math inline">\(\sigma_k\)</span>) receive a large threshold → only the coarsest WP structure kept.</li>
</ul>
<p><strong>Choosing the operating point.</strong> <span class="math inline">\(\alpha\)</span> and <span class="math inline">\(\varepsilon\)</span> are calibrated on the 11-PID benchmark (figure below): the recommended <span class="math inline">\(\varepsilon \approx 150\)</span>, <span class="math inline">\(\alpha \approx 28\)</span> sits where CR is maximised while RMSE stays below ~25 µV, and the tight spread of the α-sweep curves across insertions confirms the pair generalises without per-recording tuning.</p>
<p><strong>Minimum retained coefficients (survival floor).</strong> Because each <span class="math inline">\(V_k\)</span> has unit norm, its WP coefficients have a fixed magnitude ceiling (<span class="math inline">\(\max_j|w_{kj}| \approx 0.2\text{–}0.4\)</span>). When even the <em>dominant</em> component is weak relative to the noise floor — <span class="math inline">\(s_0/\sigma_0 \lesssim \alpha/\max_j|w_{0j}| \approx 140\)</span> — the threshold <span class="math inline">\(\tau_0\)</span> exceeds every coefficient and the entire snippet is zeroed, silently discarding real low-amplitude LFP. A <strong>survival floor</strong> removes this failure mode: the dominant component (<span class="math inline">\(k=0\)</span>) always keeps its <span class="math inline">\(n_\text{min}=64\)</span> largest-magnitude coefficients, so a retained chunk can never reconstruct to exact zero. Higher-SNR recordings are bit-for-bit unchanged (their dominant row already keeps far more than <span class="math inline">\(n_\text{min}\)</span>), and saturation-muted spans — which enter the codec as all-zero — still reconstruct to zero regardless of the floor.</p>
<p><span class="math display">\[\text{CR}_\text{total} = \text{CR}_\text{SVD} \times \text{CR}_\text{WP}, \qquad \text{CR}_\text{WP} = \frac{r \cdot n_\text{WP\,slots}}{n_\text{kept}}\]</span></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="figures/2026-06-12_svd_adaptive_wp_alpha_sweep.png" class="lightbox" data-gallery="quarto-lightbox-gallery-4" title="α vs CR_WP for each SVD-stage CR (db4, level 5). Individual PIDs as thin lines; median as heavy line. Curves are tight across insertions, confirming α generalises across recordings."><img src="figures/2026-06-12_svd_adaptive_wp_alpha_sweep.png" class="img-fluid figure-img" alt="α vs CR_WP for each SVD-stage CR (db4, level 5). Individual PIDs as thin lines; median as heavy line. Curves are tight across insertions, confirming α generalises across recordings."></a></p>
<figcaption>α vs CR_WP for each SVD-stage CR (db4, level 5). Individual PIDs as thin lines; median as heavy line. Curves are tight across insertions, confirming α generalises across recordings.</figcaption>
</figure>
</div>
</section>
<section id="parameter-sweep-gallery-svd-ε-wp-α" class="level3">
<h3 class="anchored" data-anchor-id="parameter-sweep-gallery-svd-ε-wp-α">Parameter sweep gallery (SVD-ε × WP-α)</h3>
<p>Each cell applies SVD-adapt at threshold ε (which selects rank <span class="math inline">\(r\)</span> from the snippet’s own SV spectrum), then adaptive WP at threshold α. Rows sweep ε ∈ {150, 300, 450, 750}; the resulting rank <span class="math inline">\(r\)</span> and CR_SVD are labelled per row and per cell. Columns sweep α ∈ {0, 12, 24, 32, 48, 64, 96}; α=0 is pure-SVD reference. Total CR cells show <strong>median (min–max)</strong> across the 11 benchmark insertions.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 7%">
<col style="width: 10%">
<col style="width: 18%">
<col style="width: 7%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">ε</th>
<th style="text-align: right;">r med</th>
<th style="text-align: right;">CR_SVD med</th>
<th style="text-align: right;">α=0</th>
<th style="text-align: right;">α=12</th>
<th style="text-align: right;">α=24</th>
<th style="text-align: right;">α=32</th>
<th style="text-align: right;">α=48</th>
<th style="text-align: right;">α=64</th>
<th style="text-align: right;">α=96</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">150</td>
<td style="text-align: right;">16</td>
<td style="text-align: right;">16</td>
<td style="text-align: right;">16 (14–23)</td>
<td style="text-align: right;">50 (41–71)</td>
<td style="text-align: right;">94 (76–135)</td>
<td style="text-align: right;">125 (104–183)</td>
<td style="text-align: right;">204 (175–313)</td>
<td style="text-align: right;">299 (235–486)</td>
<td style="text-align: right;">538 (361–956)</td>
</tr>
<tr class="even">
<td style="text-align: right;">300</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">25</td>
<td style="text-align: right;">25 (21–42)</td>
<td style="text-align: right;">53 (45–87)</td>
<td style="text-align: right;">98 (77–144)</td>
<td style="text-align: right;">127 (106–188)</td>
<td style="text-align: right;">205 (176–315)</td>
<td style="text-align: right;">301 (236–488)</td>
<td style="text-align: right;">538 (361–956)</td>
</tr>
<tr class="odd">
<td style="text-align: right;">450</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">32</td>
<td style="text-align: right;">32 (28–63)</td>
<td style="text-align: right;">65 (53–107)</td>
<td style="text-align: right;">105 (83–156)</td>
<td style="text-align: right;">136 (110–197)</td>
<td style="text-align: right;">212 (180–326)</td>
<td style="text-align: right;">304 (239–495)</td>
<td style="text-align: right;">538 (361–956)</td>
</tr>
<tr class="even">
<td style="text-align: right;">750</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">51</td>
<td style="text-align: right;">51 (42–126)</td>
<td style="text-align: right;">88 (70–184)</td>
<td style="text-align: right;">126 (97–233)</td>
<td style="text-align: right;">156 (126–275)</td>
<td style="text-align: right;">231 (195–393)</td>
<td style="text-align: right;">322 (259–556)</td>
<td style="text-align: right;">550 (369–1003)</td>
</tr>
</tbody>
</table>
<p><em>(Exact r, CR, RMSE and SNR for the gallery PID (dab512bd) are labelled in each cell.)</em></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="figures/2026-06-12_adaptive_wp_gallery_dab512bd-a02d-4c1f-8dbc-9155a163efc0.png" class="lightbox" data-gallery="quarto-lightbox-gallery-5" title="SVD-ε × WP-α reconstruction gallery for PID dab512bd (notable CSD). Rows: SVD-adapt ε ∈ {150, 300, 450, 750}; columns: WP α ∈ {0, 12, 24, 32, 48, 64, 96}. Each cell labels the selected rank r, achieved CRs, RMSE (µV), and SNR (dB)."><img src="figures/2026-06-12_adaptive_wp_gallery_dab512bd-a02d-4c1f-8dbc-9155a163efc0.png" class="img-fluid figure-img" alt="SVD-ε × WP-α reconstruction gallery for PID dab512bd (notable CSD). Rows: SVD-adapt ε ∈ {150, 300, 450, 750}; columns: WP α ∈ {0, 12, 24, 32, 48, 64, 96}. Each cell labels the selected rank r, achieved CRs, RMSE (µV), and SNR (dB)."></a></p>
<figcaption>SVD-ε × WP-α reconstruction gallery for PID dab512bd (notable CSD). Rows: SVD-adapt ε ∈ {150, 300, 450, 750}; columns: WP α ∈ {0, 12, 24, 32, 48, 64, 96}. Each cell labels the selected rank r, achieved CRs, RMSE (µV), and SNR (dB).</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="figures/2026-06-12_adaptive_wp_gallery_dab512bd-a02d-4c1f-8dbc-9155a163efc0_residual.png" class="lightbox" data-gallery="quarto-lightbox-gallery-6" title="Residual gallery (original − reconstruction). Same layout and colour scale. Residuals remain spatially incoherent up to the aggressive bottom-right corner (ε=750, α=96), where WP artefacts become visible."><img src="figures/2026-06-12_adaptive_wp_gallery_dab512bd-a02d-4c1f-8dbc-9155a163efc0_residual.png" class="img-fluid figure-img" alt="Residual gallery (original − reconstruction). Same layout and colour scale. Residuals remain spatially incoherent up to the aggressive bottom-right corner (ε=750, α=96), where WP artefacts become visible."></a></p>
<figcaption>Residual gallery (original − reconstruction). Same layout and colour scale. Residuals remain spatially incoherent up to the aggressive bottom-right corner (ε=750, α=96), where WP artefacts become visible.</figcaption>
</figure>
</div>
</section>
<section id="csd-gallery-pid-dab512bd" class="level3">
<h3 class="anchored" data-anchor-id="csd-gallery-pid-dab512bd">CSD gallery (PID dab512bd)</h3>
<p>Same ε × α grid as above, but displaying the <strong>current source density</strong> (second spatial finite difference, scaled by tissue conductivity σ = 1/3 S m⁻¹) of the reconstructed LFP. CSD emphasises the laminar sink/source structure and is more sensitive to spatial smearing than the raw LFP.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="figures/2026-06-12_adaptive_wp_gallery_csd_dab512bd-a02d-4c1f-8dbc-9155a163efc0.png" class="lightbox" data-gallery="quarto-lightbox-gallery-7" title="CSD reconstruction gallery for PID dab512bd. Colour scale shared across all cells, set to the 99th percentile of the original CSD."><img src="figures/2026-06-12_adaptive_wp_gallery_csd_dab512bd-a02d-4c1f-8dbc-9155a163efc0.png" class="img-fluid figure-img" alt="CSD reconstruction gallery for PID dab512bd. Colour scale shared across all cells, set to the 99th percentile of the original CSD."></a></p>
<figcaption>CSD reconstruction gallery for PID dab512bd. Colour scale shared across all cells, set to the 99th percentile of the original CSD.</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="figures/2026-06-12_adaptive_wp_gallery_csd_dab512bd-a02d-4c1f-8dbc-9155a163efc0_residual.png" class="lightbox" data-gallery="quarto-lightbox-gallery-8" title="CSD residual gallery — CSD(original) − CSD(reconstruction). Structured CSD residuals emerge at high ε and α, revealing where the spatial gradients are lost."><img src="figures/2026-06-12_adaptive_wp_gallery_csd_dab512bd-a02d-4c1f-8dbc-9155a163efc0_residual.png" class="img-fluid figure-img" alt="CSD residual gallery — CSD(original) − CSD(reconstruction). Structured CSD residuals emerge at high ε and α, revealing where the spatial gradients are lost."></a></p>
<figcaption>CSD residual gallery — CSD(original) − CSD(reconstruction). Structured CSD residuals emerge at high ε and α, revealing where the spatial gradients are lost.</figcaption>
</figure>
</div>
</section>
</section>
<section id="appendix-per-insertion-results" class="level2">
<h2 class="anchored" data-anchor-id="appendix-per-insertion-results">Appendix: Per-insertion results</h2>
<p>Cadzow denoising and SVD-ε × WP-α adaptive gallery for each of the 11 benchmark insertions.</p>
<div class="callout callout-style-simple callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>PID 1a276285
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="figures/2026-06-06_cadzow_1a276285-8b0e-4cc9-9f0a-a3a002978724.png" class="lightbox" data-gallery="quarto-lightbox-gallery-9" title="Cadzow denoising — PID 1a276285."><img src="figures/2026-06-06_cadzow_1a276285-8b0e-4cc9-9f0a-a3a002978724.png" class="img-fluid figure-img" alt="Cadzow denoising — PID 1a276285."></a></p>
<figcaption>Cadzow denoising — PID 1a276285.</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="figures/2026-06-12_adaptive_wp_gallery_1a276285-8b0e-4cc9-9f0a-a3a002978724.png" class="lightbox" data-gallery="quarto-lightbox-gallery-10" title="Adaptive gallery (SVD-ε × WP-α) — PID 1a276285."><img src="figures/2026-06-12_adaptive_wp_gallery_1a276285-8b0e-4cc9-9f0a-a3a002978724.png" class="img-fluid figure-img" alt="Adaptive gallery (SVD-ε × WP-α) — PID 1a276285."></a></p>
<figcaption>Adaptive gallery (SVD-ε × WP-α) — PID 1a276285.</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="figures/2026-06-12_adaptive_wp_gallery_1a276285-8b0e-4cc9-9f0a-a3a002978724_residual.png" class="lightbox" data-gallery="quarto-lightbox-gallery-11" title="Adaptive residual gallery — PID 1a276285."><img src="figures/2026-06-12_adaptive_wp_gallery_1a276285-8b0e-4cc9-9f0a-a3a002978724_residual.png" class="img-fluid figure-img" alt="Adaptive residual gallery — PID 1a276285."></a></p>
<figcaption>Adaptive residual gallery — PID 1a276285.</figcaption>
</figure>
</div>
</div>
</div>
</div>
<div class="callout callout-style-simple callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>PID 1e104bf4
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="figures/2026-06-06_cadzow_1e104bf4-7a24-4624-a5b2-c2c8289c0de7.png" class="lightbox" data-gallery="quarto-lightbox-gallery-12" title="Cadzow denoising — PID 1e104bf4."><img src="figures/2026-06-06_cadzow_1e104bf4-7a24-4624-a5b2-c2c8289c0de7.png" class="img-fluid figure-img" alt="Cadzow denoising — PID 1e104bf4."></a></p>
<figcaption>Cadzow denoising — PID 1e104bf4.</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="figures/2026-06-12_adaptive_wp_gallery_1e104bf4-7a24-4624-a5b2-c2c8289c0de7.png" class="lightbox" data-gallery="quarto-lightbox-gallery-13" title="Adaptive gallery (SVD-ε × WP-α) — PID 1e104bf4."><img src="figures/2026-06-12_adaptive_wp_gallery_1e104bf4-7a24-4624-a5b2-c2c8289c0de7.png" class="img-fluid figure-img" alt="Adaptive gallery (SVD-ε × WP-α) — PID 1e104bf4."></a></p>
<figcaption>Adaptive gallery (SVD-ε × WP-α) — PID 1e104bf4.</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="figures/2026-06-12_adaptive_wp_gallery_1e104bf4-7a24-4624-a5b2-c2c8289c0de7_residual.png" class="lightbox" data-gallery="quarto-lightbox-gallery-14" title="Adaptive residual gallery — PID 1e104bf4."><img src="figures/2026-06-12_adaptive_wp_gallery_1e104bf4-7a24-4624-a5b2-c2c8289c0de7_residual.png" class="img-fluid figure-img" alt="Adaptive residual gallery — PID 1e104bf4."></a></p>
<figcaption>Adaptive residual gallery — PID 1e104bf4.</figcaption>
</figure>
</div>
</div>
</div>
</div>
<div class="callout callout-style-simple callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>PID 6638cfb3
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="figures/2026-06-06_cadzow_6638cfb3-3831-4fc2-9327-194b76cf22e1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-15" title="Cadzow denoising — PID 6638cfb3."><img src="figures/2026-06-06_cadzow_6638cfb3-3831-4fc2-9327-194b76cf22e1.png" class="img-fluid figure-img" alt="Cadzow denoising — PID 6638cfb3."></a></p>
<figcaption>Cadzow denoising — PID 6638cfb3.</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="figures/2026-06-12_adaptive_wp_gallery_6638cfb3-3831-4fc2-9327-194b76cf22e1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-16" title="Adaptive gallery (SVD-ε × WP-α) — PID 6638cfb3."><img src="figures/2026-06-12_adaptive_wp_gallery_6638cfb3-3831-4fc2-9327-194b76cf22e1.png" class="img-fluid figure-img" alt="Adaptive gallery (SVD-ε × WP-α) — PID 6638cfb3."></a></p>
<figcaption>Adaptive gallery (SVD-ε × WP-α) — PID 6638cfb3.</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="figures/2026-06-12_adaptive_wp_gallery_6638cfb3-3831-4fc2-9327-194b76cf22e1_residual.png" class="lightbox" data-gallery="quarto-lightbox-gallery-17" title="Adaptive residual gallery — PID 6638cfb3."><img src="figures/2026-06-12_adaptive_wp_gallery_6638cfb3-3831-4fc2-9327-194b76cf22e1_residual.png" class="img-fluid figure-img" alt="Adaptive residual gallery — PID 6638cfb3."></a></p>
<figcaption>Adaptive residual gallery — PID 6638cfb3.</figcaption>
</figure>
</div>
</div>
</div>
</div>
<div class="callout callout-style-simple callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>PID 749cb2b7
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="figures/2026-06-06_cadzow_749cb2b7-e57e-4453-a794-f6230e4d0226.png" class="lightbox" data-gallery="quarto-lightbox-gallery-18" title="Cadzow denoising — PID 749cb2b7."><img src="figures/2026-06-06_cadzow_749cb2b7-e57e-4453-a794-f6230e4d0226.png" class="img-fluid figure-img" alt="Cadzow denoising — PID 749cb2b7."></a></p>
<figcaption>Cadzow denoising — PID 749cb2b7.</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="figures/2026-06-12_adaptive_wp_gallery_749cb2b7-e57e-4453-a794-f6230e4d0226.png" class="lightbox" data-gallery="quarto-lightbox-gallery-19" title="Adaptive gallery (SVD-ε × WP-α) — PID 749cb2b7."><img src="figures/2026-06-12_adaptive_wp_gallery_749cb2b7-e57e-4453-a794-f6230e4d0226.png" class="img-fluid figure-img" alt="Adaptive gallery (SVD-ε × WP-α) — PID 749cb2b7."></a></p>
<figcaption>Adaptive gallery (SVD-ε × WP-α) — PID 749cb2b7.</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="figures/2026-06-12_adaptive_wp_gallery_749cb2b7-e57e-4453-a794-f6230e4d0226_residual.png" class="lightbox" data-gallery="quarto-lightbox-gallery-20" title="Adaptive residual gallery — PID 749cb2b7."><img src="figures/2026-06-12_adaptive_wp_gallery_749cb2b7-e57e-4453-a794-f6230e4d0226_residual.png" class="img-fluid figure-img" alt="Adaptive residual gallery — PID 749cb2b7."></a></p>
<figcaption>Adaptive residual gallery — PID 749cb2b7.</figcaption>
</figure>
</div>
</div>
</div>
</div>
<div class="callout callout-style-simple callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>PID d7ec0892
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="figures/2026-06-06_cadzow_d7ec0892-0a6c-4f4f-9d8f-72083692af5c.png" class="lightbox" data-gallery="quarto-lightbox-gallery-21" title="Cadzow denoising — PID d7ec0892."><img src="figures/2026-06-06_cadzow_d7ec0892-0a6c-4f4f-9d8f-72083692af5c.png" class="img-fluid figure-img" alt="Cadzow denoising — PID d7ec0892."></a></p>
<figcaption>Cadzow denoising — PID d7ec0892.</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="figures/2026-06-12_adaptive_wp_gallery_d7ec0892-0a6c-4f4f-9d8f-72083692af5c.png" class="lightbox" data-gallery="quarto-lightbox-gallery-22" title="Adaptive gallery (SVD-ε × WP-α) — PID d7ec0892."><img src="figures/2026-06-12_adaptive_wp_gallery_d7ec0892-0a6c-4f4f-9d8f-72083692af5c.png" class="img-fluid figure-img" alt="Adaptive gallery (SVD-ε × WP-α) — PID d7ec0892."></a></p>
<figcaption>Adaptive gallery (SVD-ε × WP-α) — PID d7ec0892.</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="figures/2026-06-12_adaptive_wp_gallery_d7ec0892-0a6c-4f4f-9d8f-72083692af5c_residual.png" class="lightbox" data-gallery="quarto-lightbox-gallery-23" title="Adaptive residual gallery — PID d7ec0892."><img src="figures/2026-06-12_adaptive_wp_gallery_d7ec0892-0a6c-4f4f-9d8f-72083692af5c_residual.png" class="img-fluid figure-img" alt="Adaptive residual gallery — PID d7ec0892."></a></p>
<figcaption>Adaptive residual gallery — PID d7ec0892.</figcaption>
</figure>
</div>
</div>
</div>
</div>
<div class="callout callout-style-simple callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>PID da8dfec1
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="figures/2026-06-06_cadzow_da8dfec1-d265-44e8-84ce-6ae9c109b8bd.png" class="lightbox" data-gallery="quarto-lightbox-gallery-24" title="Cadzow denoising — PID da8dfec1."><img src="figures/2026-06-06_cadzow_da8dfec1-d265-44e8-84ce-6ae9c109b8bd.png" class="img-fluid figure-img" alt="Cadzow denoising — PID da8dfec1."></a></p>
<figcaption>Cadzow denoising — PID da8dfec1.</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="figures/2026-06-12_adaptive_wp_gallery_da8dfec1-d265-44e8-84ce-6ae9c109b8bd.png" class="lightbox" data-gallery="quarto-lightbox-gallery-25" title="Adaptive gallery (SVD-ε × WP-α) — PID da8dfec1."><img src="figures/2026-06-12_adaptive_wp_gallery_da8dfec1-d265-44e8-84ce-6ae9c109b8bd.png" class="img-fluid figure-img" alt="Adaptive gallery (SVD-ε × WP-α) — PID da8dfec1."></a></p>
<figcaption>Adaptive gallery (SVD-ε × WP-α) — PID da8dfec1.</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="figures/2026-06-12_adaptive_wp_gallery_da8dfec1-d265-44e8-84ce-6ae9c109b8bd_residual.png" class="lightbox" data-gallery="quarto-lightbox-gallery-26" title="Adaptive residual gallery — PID da8dfec1."><img src="figures/2026-06-12_adaptive_wp_gallery_da8dfec1-d265-44e8-84ce-6ae9c109b8bd_residual.png" class="img-fluid figure-img" alt="Adaptive residual gallery — PID da8dfec1."></a></p>
<figcaption>Adaptive residual gallery — PID da8dfec1.</figcaption>
</figure>
</div>
</div>
</div>
</div>
<div class="callout callout-style-simple callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>PID dab512bd
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="figures/2026-06-06_cadzow_dab512bd-a02d-4c1f-8dbc-9155a163efc0.png" class="lightbox" data-gallery="quarto-lightbox-gallery-27" title="Cadzow denoising — PID dab512bd."><img src="figures/2026-06-06_cadzow_dab512bd-a02d-4c1f-8dbc-9155a163efc0.png" class="img-fluid figure-img" alt="Cadzow denoising — PID dab512bd."></a></p>
<figcaption>Cadzow denoising — PID dab512bd.</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="figures/2026-06-12_adaptive_wp_gallery_dab512bd-a02d-4c1f-8dbc-9155a163efc0.png" class="lightbox" data-gallery="quarto-lightbox-gallery-28" title="Adaptive gallery (SVD-ε × WP-α) — PID dab512bd."><img src="figures/2026-06-12_adaptive_wp_gallery_dab512bd-a02d-4c1f-8dbc-9155a163efc0.png" class="img-fluid figure-img" alt="Adaptive gallery (SVD-ε × WP-α) — PID dab512bd."></a></p>
<figcaption>Adaptive gallery (SVD-ε × WP-α) — PID dab512bd.</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="figures/2026-06-12_adaptive_wp_gallery_dab512bd-a02d-4c1f-8dbc-9155a163efc0_residual.png" class="lightbox" data-gallery="quarto-lightbox-gallery-29" title="Adaptive residual gallery — PID dab512bd."><img src="figures/2026-06-12_adaptive_wp_gallery_dab512bd-a02d-4c1f-8dbc-9155a163efc0_residual.png" class="img-fluid figure-img" alt="Adaptive residual gallery — PID dab512bd."></a></p>
<figcaption>Adaptive residual gallery — PID dab512bd.</figcaption>
</figure>
</div>
</div>
</div>
</div>
<div class="callout callout-style-simple callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>PID dc7e9403
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="figures/2026-06-06_cadzow_dc7e9403-19f7-409f-9240-05ee57cb7aea.png" class="lightbox" data-gallery="quarto-lightbox-gallery-30" title="Cadzow denoising — PID dc7e9403."><img src="figures/2026-06-06_cadzow_dc7e9403-19f7-409f-9240-05ee57cb7aea.png" class="img-fluid figure-img" alt="Cadzow denoising — PID dc7e9403."></a></p>
<figcaption>Cadzow denoising — PID dc7e9403.</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="figures/2026-06-12_adaptive_wp_gallery_dc7e9403-19f7-409f-9240-05ee57cb7aea.png" class="lightbox" data-gallery="quarto-lightbox-gallery-31" title="Adaptive gallery (SVD-ε × WP-α) — PID dc7e9403."><img src="figures/2026-06-12_adaptive_wp_gallery_dc7e9403-19f7-409f-9240-05ee57cb7aea.png" class="img-fluid figure-img" alt="Adaptive gallery (SVD-ε × WP-α) — PID dc7e9403."></a></p>
<figcaption>Adaptive gallery (SVD-ε × WP-α) — PID dc7e9403.</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="figures/2026-06-12_adaptive_wp_gallery_dc7e9403-19f7-409f-9240-05ee57cb7aea_residual.png" class="lightbox" data-gallery="quarto-lightbox-gallery-32" title="Adaptive residual gallery — PID dc7e9403."><img src="figures/2026-06-12_adaptive_wp_gallery_dc7e9403-19f7-409f-9240-05ee57cb7aea_residual.png" class="img-fluid figure-img" alt="Adaptive residual gallery — PID dc7e9403."></a></p>
<figcaption>Adaptive residual gallery — PID dc7e9403.</figcaption>
</figure>
</div>
</div>
</div>
</div>
<div class="callout callout-style-simple callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>PID e8f9fba4
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="figures/2026-06-06_cadzow_e8f9fba4-d151-4b00-bee7-447f0f3e752c.png" class="lightbox" data-gallery="quarto-lightbox-gallery-33" title="Cadzow denoising — PID e8f9fba4."><img src="figures/2026-06-06_cadzow_e8f9fba4-d151-4b00-bee7-447f0f3e752c.png" class="img-fluid figure-img" alt="Cadzow denoising — PID e8f9fba4."></a></p>
<figcaption>Cadzow denoising — PID e8f9fba4.</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="figures/2026-06-12_adaptive_wp_gallery_e8f9fba4-d151-4b00-bee7-447f0f3e752c.png" class="lightbox" data-gallery="quarto-lightbox-gallery-34" title="Adaptive gallery (SVD-ε × WP-α) — PID e8f9fba4."><img src="figures/2026-06-12_adaptive_wp_gallery_e8f9fba4-d151-4b00-bee7-447f0f3e752c.png" class="img-fluid figure-img" alt="Adaptive gallery (SVD-ε × WP-α) — PID e8f9fba4."></a></p>
<figcaption>Adaptive gallery (SVD-ε × WP-α) — PID e8f9fba4.</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="figures/2026-06-12_adaptive_wp_gallery_e8f9fba4-d151-4b00-bee7-447f0f3e752c_residual.png" class="lightbox" data-gallery="quarto-lightbox-gallery-35" title="Adaptive residual gallery — PID e8f9fba4."><img src="figures/2026-06-12_adaptive_wp_gallery_e8f9fba4-d151-4b00-bee7-447f0f3e752c_residual.png" class="img-fluid figure-img" alt="Adaptive residual gallery — PID e8f9fba4."></a></p>
<figcaption>Adaptive residual gallery — PID e8f9fba4.</figcaption>
</figure>
</div>
</div>
</div>
</div>
<div class="callout callout-style-simple callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-10-contents" aria-controls="callout-10" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>PID eebcaf65
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-10" class="callout-10-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="figures/2026-06-06_cadzow_eebcaf65-7fa4-4118-869d-a084e84530e2.png" class="lightbox" data-gallery="quarto-lightbox-gallery-36" title="Cadzow denoising — PID eebcaf65."><img src="figures/2026-06-06_cadzow_eebcaf65-7fa4-4118-869d-a084e84530e2.png" class="img-fluid figure-img" alt="Cadzow denoising — PID eebcaf65."></a></p>
<figcaption>Cadzow denoising — PID eebcaf65.</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="figures/2026-06-12_adaptive_wp_gallery_eebcaf65-7fa4-4118-869d-a084e84530e2.png" class="lightbox" data-gallery="quarto-lightbox-gallery-37" title="Adaptive gallery (SVD-ε × WP-α) — PID eebcaf65."><img src="figures/2026-06-12_adaptive_wp_gallery_eebcaf65-7fa4-4118-869d-a084e84530e2.png" class="img-fluid figure-img" alt="Adaptive gallery (SVD-ε × WP-α) — PID eebcaf65."></a></p>
<figcaption>Adaptive gallery (SVD-ε × WP-α) — PID eebcaf65.</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="figures/2026-06-12_adaptive_wp_gallery_eebcaf65-7fa4-4118-869d-a084e84530e2_residual.png" class="lightbox" data-gallery="quarto-lightbox-gallery-38" title="Adaptive residual gallery — PID eebcaf65."><img src="figures/2026-06-12_adaptive_wp_gallery_eebcaf65-7fa4-4118-869d-a084e84530e2_residual.png" class="img-fluid figure-img" alt="Adaptive residual gallery — PID eebcaf65."></a></p>
<figcaption>Adaptive residual gallery — PID eebcaf65.</figcaption>
</figure>
</div>
</div>
</div>
</div>
<div class="callout callout-style-simple callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-11-contents" aria-controls="callout-11" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>PID fe380793
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-11" class="callout-11-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="figures/2026-06-06_cadzow_fe380793-8035-414e-b000-09bfe5ece92a.png" class="lightbox" data-gallery="quarto-lightbox-gallery-39" title="Cadzow denoising — PID fe380793."><img src="figures/2026-06-06_cadzow_fe380793-8035-414e-b000-09bfe5ece92a.png" class="img-fluid figure-img" alt="Cadzow denoising — PID fe380793."></a></p>
<figcaption>Cadzow denoising — PID fe380793.</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="figures/2026-06-12_adaptive_wp_gallery_fe380793-8035-414e-b000-09bfe5ece92a.png" class="lightbox" data-gallery="quarto-lightbox-gallery-40" title="Adaptive gallery (SVD-ε × WP-α) — PID fe380793."><img src="figures/2026-06-12_adaptive_wp_gallery_fe380793-8035-414e-b000-09bfe5ece92a.png" class="img-fluid figure-img" alt="Adaptive gallery (SVD-ε × WP-α) — PID fe380793."></a></p>
<figcaption>Adaptive gallery (SVD-ε × WP-α) — PID fe380793.</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="figures/2026-06-12_adaptive_wp_gallery_fe380793-8035-414e-b000-09bfe5ece92a_residual.png" class="lightbox" data-gallery="quarto-lightbox-gallery-41" title="Adaptive residual gallery — PID fe380793."><img src="figures/2026-06-12_adaptive_wp_gallery_fe380793-8035-414e-b000-09bfe5ece92a_residual.png" class="img-fluid figure-img" alt="Adaptive residual gallery — PID fe380793."></a></p>
<figcaption>Adaptive residual gallery — PID fe380793.</figcaption>
</figure>
</div>
</div>
</div>
</div>
<div class="callout callout-style-simple callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-12-contents" aria-controls="callout-12" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>SVD-adapt-WP algorithm in detail
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-12" class="callout-12-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The two-stage algorithm operates on a snippet matrix <span class="math inline">\(X \in \mathbb{R}^{n_c \times n_s}\)</span> (channels × samples):</p>
<p><strong>Stage 1 — spatial compression (SVD)</strong></p>
<p><span class="math display">\[X \approx \hat{X}_1 = U_r \, \text{diag}(s_r) \, V_r^\top\]</span></p>
<p>where <span class="math inline">\(U_r \in \mathbb{R}^{n_c \times r}\)</span>, <span class="math inline">\(s_r \in \mathbb{R}^r\)</span>, <span class="math inline">\(V_r^\top \in \mathbb{R}^{r \times n_s}\)</span> are the top-<span class="math inline">\(r\)</span> singular triplets. The rank <span class="math inline">\(r\)</span> is chosen to achieve a target CR (e.g.&nbsp;CR=24 → <span class="math inline">\(r \approx 12\)</span>).</p>
<p><strong>Stage 2 — temporal compression (wavelet packets)</strong></p>
<p>Each of the <span class="math inline">\(r\)</span> rows of <span class="math inline">\(V_r^\top\)</span> is independently compressed using db4 wavelet packet decomposition (level 5). Only the top-<span class="math inline">\(f\)</span> fraction of coefficients by magnitude are retained, giving an overall:</p>
<p><span class="math display">\[\text{CR}_{\text{total}} = \frac{n_c \, n_s}{r(n_c + n_s)} \cdot \frac{1}{f}\]</span></p>
<p><strong>SVD-adapt (ε-sweep)</strong> selects rank automatically using:</p>
<p><span class="math display">\[\sigma_0 = \text{median}(s_{\lfloor r/2 \rfloor + 1}, \ldots, s_r), \qquad r^* = \max\{k : s_k &gt; \varepsilon \cdot \sigma_0\}\]</span></p>
<p>Here <span class="math inline">\(\sigma_0\)</span> is the noise-floor estimate (median of the lower half of the full singular value spectrum), and <span class="math inline">\(\varepsilon\)</span> is a dimensionless threshold — the minimum signal-to-noise-floor ratio <span class="math inline">\(s_k / \sigma_0\)</span> required to retain a component. Equivalently, <span class="math inline">\(\varepsilon(r) = s_r / \sigma_0\)</span> is the <span class="math inline">\(\varepsilon\)</span> that would select exactly rank <span class="math inline">\(r\)</span> (as shown in the calibration figure). Sweeping <span class="math inline">\(\varepsilon\)</span> from <span class="math inline">\(10^4\)</span> (keep only the dominant component) down to <span class="math inline">\(10^{-1}\)</span> (keep almost everything) traces out the full CR curve.</p>
<p><strong>Reconstruction</strong> reverses the two stages: reconstruct each wavelet-compressed row, then reassemble <span class="math inline">\(\hat{X} = U_r \, \text{diag}(s_r) \, \hat{V}_r^\top\)</span>.</p>
</div>
</div>
</div>
<div class="callout callout-style-simple callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-13-contents" aria-controls="callout-13" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>WP coefficient selection: per-coefficient error thresholding
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-13" class="callout-13-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Setup.</strong> After SVD truncation at rank <span class="math inline">\(r\)</span>, each retained temporal component is a row <span class="math inline">\(V_k \in \mathbb{R}^{n_s}\)</span> of <span class="math inline">\(V_r^\top\)</span> with unit <span class="math inline">\(\ell_2\)</span>-norm (<span class="math inline">\(\|V_k\|_2 = 1\)</span>, since <span class="math inline">\(V\)</span> is orthonormal). The full reconstruction contribution of component <span class="math inline">\(k\)</span> to <span class="math inline">\(X\)</span> is <span class="math inline">\(s_k U_k V_k^\top\)</span>, whose Frobenius norm is <span class="math inline">\(s_k\)</span>.</p>
<p><strong>Wavelet-packet decomposition.</strong> Each <span class="math inline">\(V_k\)</span> is decomposed into <span class="math inline">\(n_\text{WP}\)</span> coefficients <span class="math inline">\(\{w_{kj}\}\)</span> via a full db4 wavelet-packet tree at level 5 (for <span class="math inline">\(n_s = 750\)</span>, <span class="math inline">\(n_\text{WP} = 960\)</span>). Because the WP transform is orthogonal, <span class="math inline">\(\sum_j w_{kj}^2 = \|V_k\|_2^2 = 1\)</span>.</p>
<p><strong>Per-component hard threshold.</strong> For each component <span class="math inline">\(k\)</span>, a threshold is set as</p>
<p><span class="math display">\[\tau_k = \frac{\alpha \cdot \sigma_0}{s_k}\]</span></p>
<p>and coefficient <span class="math inline">\(w_{kj}\)</span> is retained only if <span class="math inline">\(|w_{kj}| \geq \tau_k\)</span>; otherwise it is set to zero:</p>
<p><span class="math display">\[\tilde{w}_{kj} = w_{kj} \cdot \mathbf{1}\!\left[|w_{kj}| \geq \tau_k\right]\]</span></p>
<p><strong>Per-coefficient error guarantee.</strong> Zeroing <span class="math inline">\(w_{kj}\)</span> changes the reconstruction by <span class="math inline">\(s_k \, U_k \cdot \delta v_{kj}^\top\)</span>, where <span class="math inline">\(\delta v_{kj}\)</span> is the inverse-WP basis vector for coefficient <span class="math inline">\(j\)</span> with unit norm. The resulting Frobenius error contribution is</p>
<p><span class="math display">\[s_k \cdot |w_{kj}| \;&lt;\; s_k \cdot \tau_k \;=\; \alpha \cdot \sigma_0\]</span></p>
<p><em>Every discarded coefficient, in every component, contributes less than <span class="math inline">\(\alpha \cdot \sigma_0\)</span> to the reconstruction error</em> — uniformly across all ranks. This is the same absolute noise-floor reference <span class="math inline">\(\sigma_0\)</span> used by the SVD stage, so the two thresholds speak the same language.</p>
<p><strong>Compression ratio.</strong> The WP stage CR is the ratio of total available coefficient slots to those retained:</p>
<p><span class="math display">\[\text{CR}_\text{WP} = \frac{r \cdot n_\text{WP}}{\#\{(k,j) : s_k |w_{kj}| \geq \alpha\sigma_0\}}\]</span></p>
<p><strong>Behaviour across the component spectrum.</strong></p>
<p>For a component with singular value <span class="math inline">\(s_k = q \cdot \varepsilon \cdot \sigma_0\)</span> (where <span class="math inline">\(q \geq 1\)</span>, since only components above the SVD threshold are retained), the WP threshold becomes</p>
<p><span class="math display">\[\tau_k = \frac{\alpha}{q \cdot \varepsilon}\]</span></p>
<ul>
<li><strong>Dominant components</strong> (<span class="math inline">\(q \gg 1\)</span>, <span class="math inline">\(s_k \gg \varepsilon\sigma_0\)</span>): <span class="math inline">\(\tau_k\)</span> is small, many WP coefficients survive — the component’s full temporal structure is preserved with only fine-scale details discarded.</li>
<li><strong>Marginal components</strong> (<span class="math inline">\(q \approx 1\)</span>, <span class="math inline">\(s_k \approx \varepsilon\sigma_0\)</span>): <span class="math inline">\(\tau_k \approx \alpha/\varepsilon\)</span>. If <span class="math inline">\(\alpha/\varepsilon\)</span> exceeds the largest WP coefficient magnitude of <span class="math inline">\(V_k\)</span> (empirically 0.05–0.2 for LFP), the entire component is zeroed. This is consistent behaviour: the component was weakly significant spatially <em>and</em> has no concentrated temporal structure, so it genuinely carries little information.</li>
</ul>
<p>This component-level zeroing is not a design flaw — it is the natural outcome of applying a uniform per-coefficient error threshold to components with flat (noise-like) temporal spectra. In practice, at the recommended operating point (<span class="math inline">\(\varepsilon \approx 150\)</span>, <span class="math inline">\(\alpha \approx 28\)</span>, <span class="math inline">\(\alpha/\varepsilon \approx 0.19\)</span>), components at ranks 7–13 are fully eliminated by WP, while the first 5–6 components retain 5–70% of their WP coefficients for genuine temporal compression.</p>
<p><strong>Relationship to the SVD threshold.</strong> The two parameters are not independent: when <span class="math inline">\(\alpha/\varepsilon &gt; \max_j |w_{r,j}|\)</span> (the largest WP coefficient of the weakest retained component), WP overrides the SVD rank selection. The curves in the aggregate figure converge at high <span class="math inline">\(\alpha\)</span> because all <span class="math inline">\(\varepsilon\)</span> settings end up keeping the same dominant components once <span class="math inline">\(\alpha\)</span> is large enough to purge the weaker ones. The non-redundant operating region is <span class="math inline">\(\alpha/\varepsilon \lesssim 0.1\)</span>, where WP compresses temporal structure within every kept component without discarding any of them entirely.</p>
<p><strong>Survival floor on the dominant component.</strong> Purging <em>weak</em> components (above) is benign. The pathological case is when the same mechanism zeroes the <em>dominant</em> component <span class="math inline">\(k=0\)</span>: this happens on low-SNR recordings where <span class="math inline">\(s_0/\sigma_0 \lesssim \alpha/\max_j|w_{0j}| \approx 140\)</span>, at which point <span class="math inline">\(\tau_0\)</span> exceeds every coefficient of <span class="math inline">\(V_0\)</span>, <span class="math inline">\(\hat V_r^\top = 0\)</span>, and the chunk reconstructs to exact zero — destroying genuine low-amplitude LFP. To bound this, the dominant component always retains its <span class="math inline">\(n_\text{min}=64\)</span> largest-magnitude WP coefficients regardless of <span class="math inline">\(\tau_0\)</span>: <span class="math display">\[\#\{j : \tilde w_{0j} \neq 0\} \geq \min(n_\text{min},\, n_\text{WP}).\]</span> The floor is applied only to <span class="math inline">\(k=0\)</span>, so weaker components still vanish (preserving CR), and it is a no-op on healthy recordings, whose dominant row already keeps <span class="math inline">\(\gg n_\text{min}\)</span> coefficients — leaving their reconstruction bit-for-bit identical. A genuinely silent input (e.g.&nbsp;a saturation-muted span) has <span class="math inline">\(s_0 = 0\)</span> hence <span class="math inline">\(U_r\,\text{diag}(s_r) = 0\)</span>, so it still reconstructs to zero and the floor cannot fabricate signal.</p>
</div>
</div>
</div>
<div class="callout callout-style-simple callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-14-contents" aria-controls="callout-14" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Cadzow denoising with adaptive rank and imputation
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-14" class="callout-14-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>F-X Cadzow: working frequency bin by frequency bin</strong> <em>(parameters used: nw=64, f_max=100 Hz, max rank r=5, gap_threshold=2.0, ppca_k=2.0)</em></p>
<p>This is the <em>F-X</em> (frequency–space) variant of Cadzow denoising, borrowed from seismic processing. Rather than applying SVD to the full time × channel matrix, the algorithm works one frequency bin at a time:</p>
<ol type="1">
<li><strong>rfft</strong> the snippet → complex array <span class="math inline">\(W \in \mathbb{C}^{n_c \times n_f}\)</span>.</li>
<li>For each frequency bin <span class="math inline">\(f \leq f_\text{max}\)</span>, extract the spatial vector <span class="math inline">\(w_f \in \mathbb{C}^{n_c}\)</span> (one complex amplitude per channel).</li>
<li>Build a <strong>block-Toeplitz trajectory matrix</strong> <span class="math inline">\(T_f\)</span> from <span class="math inline">\(w_f\)</span>.</li>
<li>Compute the rank-<span class="math inline">\(r\)</span> SVD of <span class="math inline">\(T_f\)</span>, zero the remaining singular values, and read off the denoised amplitudes.</li>
<li><strong>irfft</strong> back to the time domain.</li>
</ol>
<p><strong>Outlier imputation (<code>ppca_k</code>)</strong>: after the first rank-<span class="math inline">\(r\)</span> projection, channels deviating by more than <span class="math inline">\(\text{median} + k \cdot \text{MAD}\)</span> are replaced by their model prediction; the SVD is repeated on the cleaned data.</p>
</div>
</div>
</div>
<div class="callout callout-style-simple callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-15-contents" aria-controls="callout-15" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Prior context: transform methods
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-15" class="callout-15-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Before focusing on SVD variants, we benchmarked six approaches: SVD, Wavelet Packets (WP), DCT, DCT-δ, STFT, and SVD+WP. SVD consistently outperformed all transform-only methods at every compression ratio. The figure below shows the full comparison; the current analysis refines and extends only the SVD family.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="figures/2026-06-06_compression_aggregate.png" class="lightbox" data-gallery="quarto-lightbox-gallery-42" title="Initial aggregate benchmark (11 PIDs) including all transform methods. SVD and SVD+WP dominate at every CR. DCT-δ is worst throughout."><img src="figures/2026-06-06_compression_aggregate.png" class="img-fluid figure-img" alt="Initial aggregate benchmark (11 PIDs) including all transform methods. SVD and SVD+WP dominate at every CR. DCT-δ is worst throughout."></a></p>
<figcaption>Initial aggregate benchmark (11 PIDs) including all transform methods. SVD and SVD+WP dominate at every CR. DCT-δ is worst throughout.</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="figures/2026-06-06_compression_gallery_dab512bd-a02d-4c1f-8dbc-9155a163efc0.png" class="lightbox" data-gallery="quarto-lightbox-gallery-43" title="Reconstruction gallery from initial benchmark — PID dab512bd. SVD retains spatial structure to CR=100; transform methods show block/stripe artefacts from CR=30."><img src="figures/2026-06-06_compression_gallery_dab512bd-a02d-4c1f-8dbc-9155a163efc0.png" class="img-fluid figure-img" alt="Reconstruction gallery from initial benchmark — PID dab512bd. SVD retains spatial structure to CR=100; transform methods show block/stripe artefacts from CR=30."></a></p>
<figcaption>Reconstruction gallery from initial benchmark — PID dab512bd. SVD retains spatial structure to CR=100; transform methods show block/stripe artefacts from CR=30.</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="figures/2026-06-06_compression_gallery_dab512bd-a02d-4c1f-8dbc-9155a163efc0_residual.png" class="lightbox" data-gallery="quarto-lightbox-gallery-44" title="Residual gallery from initial benchmark. SVD/SVD+WP residuals are spatially incoherent; DCT and STFT residuals carry structured spectral artefacts at high CR."><img src="figures/2026-06-06_compression_gallery_dab512bd-a02d-4c1f-8dbc-9155a163efc0_residual.png" class="img-fluid figure-img" alt="Residual gallery from initial benchmark. SVD/SVD+WP residuals are spatially incoherent; DCT and STFT residuals carry structured spectral artefacts at high CR."></a></p>
<figcaption>Residual gallery from initial benchmark. SVD/SVD+WP residuals are spatially incoherent; DCT and STFT residuals carry structured spectral artefacts at high CR.</figcaption>
</figure>
</div>
</div>
</div>
</div>
<div class="callout callout-style-simple callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-16-contents" aria-controls="callout-16" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Prior-context: Gap-criterion rank selection (discarded)
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-16" class="callout-16-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>We investigated an alternative rank-selection criterion based on the largest relative drop in the singular value spectrum (the “gap”):</p>
<p><span class="math display">\[r_\text{gap} = \underset{i}{\arg\max}\; \frac{s_i}{s_{i+1}} + 1\]</span></p>
<p>We also swept a gap threshold <span class="math inline">\(g\)</span>, defining rank as the last position where <span class="math inline">\(s_k / s_{k+1} \geq g\)</span>.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="figures/2026-06-10_gap_vs_rank.png" class="lightbox" data-gallery="quarto-lightbox-gallery-45" title="Gap ratio sv[k]/sv[k+1] at each rank boundary for each of the 11 PIDs. Reference lines at g=2, 5, 10."><img src="figures/2026-06-10_gap_vs_rank.png" class="img-fluid figure-img" alt="Gap ratio sv[k]/sv[k+1] at each rank boundary for each of the 11 PIDs. Reference lines at g=2, 5, 10."></a></p>
<figcaption>Gap ratio sv[k]/sv[k+1] at each rank boundary for each of the 11 PIDs. Reference lines at g=2, 5, 10.</figcaption>
</figure>
</div>
<p>The figure reveals why this criterion was discarded: after Cadzow denoising, the SV ratio at rank 1 is only <strong>1.3–2.4</strong> across all 11 PIDs — the dominant “gap” is barely larger than the secondary gaps. There is no clean separation between signal and noise in the SV ratio spectrum, so the gap threshold has very little sensitivity to the compression ratio. The ε-threshold (noise-floor-relative) criterion is far better calibrated for this data.</p>
</div>
</div>
</div>


<!-- -->

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "LFP Compression Benchmark: SVD and Adaptive SVD+WP Methods"</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="an">description:</span><span class="co"> "Benchmarking SVD-based LFP compression methods on 11 Neuropixels insertions, evaluating RMSE and SNR across compression ratios up to 3000×."</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> "2026-06-09"</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> "Olivier Winter"</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="an">categories:</span><span class="co"> [electrophysiology, LFP, compression, Neuropixels]</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">## Overview</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>The IBL holds **936 hours** of Brainwide Map (BWM) recordings and **1472 hours** from the Ephys Atlas.</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>Raw LFP at 2500 Hz, 384 channels, float32 amounts to ~12 TB for the BWM alone.</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>After standard preprocessing (bad-channel rejection, 2–250 Hz bandpass, ×10 decimation to 250 Hz), the footprint shrinks to ~1.2 Tb — still too large for routine distribution or streaming.</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>The goal is to identify a lossy compression strategy that reduces this further.</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>**Practical recommendation: SVD + WP (ε≈150, α≈28) gives total CR≈125 (104-181) with RMSE≈15 µV and SNR≈10 dB.**</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>**This would shrink the 936-hour BWM dataset to ~9.6 Gb.**</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a><span class="fu">## Pre-processing pipeline</span></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>Raw LFP (NP1, 2500 Hz, <span class="in">`.cbin`</span>) was preprocessed before benchmarking:</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>**Bad-channel detection** — channels with anomalous variance flagged and excluded.</span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>**Bandpass + CAR + decimation** — 2–250 Hz FIR bandpass, common-average referencing, ×10 FIR decimation → 250 Hz float32.</span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>**Cadzow PPCA spatial denoising** — F-X Cadzow on 3 s snippets (nw=64, f_max=100 Hz, max rank r=5, adaptive rank via singular-value gap threshold=2.0, PPCA outlier k=2.0) to remove incoherent channel noise.</span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>All methods were benchmarked on the Cadzow-denoised snippets so residuals reflect compression loss, not pre-existing noise.</span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a><span class="al">![Cadzow denoising for PID e8f9fba4. Three 3 s snippets (rows): original / denoised (adaptive rank) / difference (same colour scale).](figures/2026-06-06_cadzow_e8f9fba4-d151-4b00-bee7-447f0f3e752c.png)</span></span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a><span class="fu">## Compression methods</span></span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Method <span class="pp">|</span> Principle <span class="pp">|</span> CR formula <span class="pp">|</span> Parameters <span class="pp">|</span></span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---|---|---|</span></span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **SVD-adapt** <span class="pp">|</span> First-stage: truncated SVD with adaptive rank: retain components where $s_k &gt; \varepsilon \cdot \sigma_0$, with $\sigma_0 = \text{median}(\text{lower half of } s)$ as the noise-floor estimate. $\varepsilon$ is swept to cover the full CR range. <span class="pp">|</span> $n_c n_s / (r_\varepsilon(n_c+n_s))$ <span class="pp">|</span> ε ∈ logspace(10⁴, 10⁻¹, 30) <span class="pp">|</span></span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **WP** <span class="pp">|</span> Second-stage: db4 wavelet-packet adaptive thresholding on the $r$ temporal rows of $V_r^\top$. Per-component threshold $\tau_k = \alpha \sigma_0 / \sigma_k$ ensures uniform error contribution across all ranks. <span class="pp">|</span> $\text{CR}_\text{SVD} \times \text{CR}_\text{WP}$ <span class="pp">|</span> ε (SVD stage), α (WP stage) <span class="pp">|</span></span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a><span class="fu">## Metrics</span></span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a>$$\text{RMSE}(c) = \left\langle \sqrt{\left\langle (x - \hat{x})^2 \right\rangle_t} \right\rangle_{\text{snippets}} \quad <span class="co">[</span><span class="ot">\mu\text{V}</span><span class="co">]</span> \qquad \text{SNR}(c) = 20 \cdot \log_{10} \left( \frac{\text{RMS}(c)}{\text{RMSE}(c)} \right) \quad <span class="co">[</span><span class="ot">\text{dB}</span><span class="co">]</span>$$</span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a>Aggregated as median over channels, then mean over 11 PIDs.</span>
<span id="cb1-44"><a href="#cb1-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-45"><a href="#cb1-45" aria-hidden="true" tabindex="-1"></a><span class="fu">## Results</span></span>
<span id="cb1-46"><a href="#cb1-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-47"><a href="#cb1-47" aria-hidden="true" tabindex="-1"></a><span class="fu">### Aggregate benchmark (11 PIDs)</span></span>
<span id="cb1-48"><a href="#cb1-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-49"><a href="#cb1-49" aria-hidden="true" tabindex="-1"></a><span class="al">![Adaptive SVD+WP aggregate quality. Left: median RMSE (µV, log–log) vs total CR; right: median SNR (dB) vs total CR. One curve per SVD-stage CR; α values labelled at each operating point.](figures/2026-06-12_adaptive_wp_aggregate.png)</span></span>
<span id="cb1-50"><a href="#cb1-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-51"><a href="#cb1-51" aria-hidden="true" tabindex="-1"></a>Each curve sweeps α from 0 (single stage SVD) through 64 (aggressive WP thresholding).</span>
<span id="cb1-52"><a href="#cb1-52" aria-hidden="true" tabindex="-1"></a>All curves eventually converge from CR≈100 (α≈24), meaning the wavepack is eventually catching up.</span>
<span id="cb1-53"><a href="#cb1-53" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-54"><a href="#cb1-54" aria-hidden="true" tabindex="-1"></a><span class="fu">### SVD spectrum and ε calibration</span></span>
<span id="cb1-55"><a href="#cb1-55" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-56"><a href="#cb1-56" aria-hidden="true" tabindex="-1"></a><span class="al">![Left: for each PID, $\varepsilon(r) = s_r / \sigma_0$ — the signal-to-noise-floor ratio of the $r$-th singular value — vs rank (bottom axis, 1–96). This is the $\varepsilon$ that would select exactly rank $r$. Right: singular value $s_r$ (µV) vs rank, with the per-PID noise floor $\sigma_0$ shown as a dashed horizontal line. The secondary top axis shows the **compression ratio** at each rank.](figures/2026-06-10_epsilon_vs_rank.png)</span></span>
<span id="cb1-57"><a href="#cb1-57" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-58"><a href="#cb1-58" aria-hidden="true" tabindex="-1"></a>Median ε values (and range across 11 PIDs) that select each evaluated rank:</span>
<span id="cb1-59"><a href="#cb1-59" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-60"><a href="#cb1-60" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Rank <span class="pp">|</span> ε median <span class="pp">|</span> ε range <span class="pp">|</span></span>
<span id="cb1-61"><a href="#cb1-61" aria-hidden="true" tabindex="-1"></a><span class="pp">|-----:|--------:|:--------|</span></span>
<span id="cb1-62"><a href="#cb1-62" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 1 <span class="pp">|</span> 4073 <span class="pp">|</span> 2772–4697 <span class="pp">|</span></span>
<span id="cb1-63"><a href="#cb1-63" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 2 <span class="pp">|</span> 2252 <span class="pp">|</span> 1540–2898 <span class="pp">|</span></span>
<span id="cb1-64"><a href="#cb1-64" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 4 <span class="pp">|</span> 909 <span class="pp">|</span> 574–1240 <span class="pp">|</span></span>
<span id="cb1-65"><a href="#cb1-65" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 8 <span class="pp">|</span> 461 <span class="pp">|</span> 255–584 <span class="pp">|</span></span>
<span id="cb1-66"><a href="#cb1-66" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 16 <span class="pp">|</span> 155 <span class="pp">|</span> 89–207 <span class="pp">|</span></span>
<span id="cb1-67"><a href="#cb1-67" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 32 <span class="pp">|</span> 47 <span class="pp">|</span> 22–73 <span class="pp">|</span></span>
<span id="cb1-68"><a href="#cb1-68" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 64 <span class="pp">|</span> 10 <span class="pp">|</span> 4–22 <span class="pp">|</span></span>
<span id="cb1-69"><a href="#cb1-69" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 96 <span class="pp">|</span> 4 <span class="pp">|</span> 1–10 <span class="pp">|</span></span>
<span id="cb1-70"><a href="#cb1-70" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-71"><a href="#cb1-71" aria-hidden="true" tabindex="-1"></a><span class="fu">### Adaptive WP threshold calibration</span></span>
<span id="cb1-72"><a href="#cb1-72" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-73"><a href="#cb1-73" aria-hidden="true" tabindex="-1"></a>After SVD truncation at rank $r$, each temporal component $V_k$ (a row of $V_r^\top$, unit-L2-norm) is wavelet-packet compressed with a per-component hard threshold:</span>
<span id="cb1-74"><a href="#cb1-74" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-75"><a href="#cb1-75" aria-hidden="true" tabindex="-1"></a>$$\tau_k = \frac{\alpha \cdot \sigma_0}{\sigma_k}$$</span>
<span id="cb1-76"><a href="#cb1-76" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-77"><a href="#cb1-77" aria-hidden="true" tabindex="-1"></a>where $\sigma_0$ is the same SVD noise floor used for ε-based rank selection, $\sigma_k$ is the singular value of component $k$, and $\alpha$ is a single global multiplier.</span>
<span id="cb1-78"><a href="#cb1-78" aria-hidden="true" tabindex="-1"></a>The threshold ensures every discarded coefficient contributes less than $\alpha \cdot \sigma_0$ — uniform across all components regardless of their amplitude.</span>
<span id="cb1-79"><a href="#cb1-79" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-80"><a href="#cb1-80" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Dominant components (large $\sigma_k$) receive a small threshold → many WP coefficients retained.</span>
<span id="cb1-81"><a href="#cb1-81" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Weak components (small $\sigma_k$) receive a large threshold → only the coarsest WP structure kept.</span>
<span id="cb1-82"><a href="#cb1-82" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-83"><a href="#cb1-83" aria-hidden="true" tabindex="-1"></a>**Choosing the operating point.** $\alpha$ and $\varepsilon$ are calibrated on the 11-PID benchmark (figure below): the recommended $\varepsilon \approx 150$, $\alpha \approx 28$ sits where CR is maximised while RMSE stays below ~25 µV, and the tight spread of the α-sweep curves across insertions confirms the pair generalises without per-recording tuning.</span>
<span id="cb1-84"><a href="#cb1-84" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-85"><a href="#cb1-85" aria-hidden="true" tabindex="-1"></a>**Minimum retained coefficients (survival floor).** Because each $V_k$ has unit norm, its WP coefficients have a fixed magnitude ceiling ($\max_j|w_{kj}| \approx 0.2\text{–}0.4$). When even the *dominant* component is weak relative to the noise floor — $s_0/\sigma_0 \lesssim \alpha/\max_j|w_{0j}| \approx 140$ — the threshold $\tau_0$ exceeds every coefficient and the entire snippet is zeroed, silently discarding real low-amplitude LFP. A **survival floor** removes this failure mode: the dominant component ($k=0$) always keeps its $n_\text{min}=64$ largest-magnitude coefficients, so a retained chunk can never reconstruct to exact zero. Higher-SNR recordings are bit-for-bit unchanged (their dominant row already keeps far more than $n_\text{min}$), and saturation-muted spans — which enter the codec as all-zero — still reconstruct to zero regardless of the floor.</span>
<span id="cb1-86"><a href="#cb1-86" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-87"><a href="#cb1-87" aria-hidden="true" tabindex="-1"></a>$$\text{CR}_\text{total} = \text{CR}_\text{SVD} \times \text{CR}_\text{WP}, \qquad \text{CR}_\text{WP} = \frac{r \cdot n_\text{WP\,slots}}{n_\text{kept}}$$</span>
<span id="cb1-88"><a href="#cb1-88" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-89"><a href="#cb1-89" aria-hidden="true" tabindex="-1"></a><span class="al">![α vs CR_WP for each SVD-stage CR (db4, level 5). Individual PIDs as thin lines; median as heavy line. Curves are tight across insertions, confirming α generalises across recordings.](figures/2026-06-12_svd_adaptive_wp_alpha_sweep.png)</span></span>
<span id="cb1-90"><a href="#cb1-90" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-91"><a href="#cb1-91" aria-hidden="true" tabindex="-1"></a><span class="fu">### Parameter sweep gallery (SVD-ε × WP-α)</span></span>
<span id="cb1-92"><a href="#cb1-92" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-93"><a href="#cb1-93" aria-hidden="true" tabindex="-1"></a>Each cell applies SVD-adapt at threshold ε (which selects rank $r$ from the snippet's own SV spectrum), then adaptive WP at threshold α.</span>
<span id="cb1-94"><a href="#cb1-94" aria-hidden="true" tabindex="-1"></a>Rows sweep ε ∈ {150, 300, 450, 750}; the resulting rank $r$ and CR_SVD are labelled per row and per cell.</span>
<span id="cb1-95"><a href="#cb1-95" aria-hidden="true" tabindex="-1"></a>Columns sweep α ∈ {0, 12, 24, 32, 48, 64, 96}; α=0 is pure-SVD reference.</span>
<span id="cb1-96"><a href="#cb1-96" aria-hidden="true" tabindex="-1"></a>Total CR cells show **median (min–max)** across the 11 benchmark insertions.</span>
<span id="cb1-97"><a href="#cb1-97" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-98"><a href="#cb1-98" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> ε   <span class="pp">|</span> r med <span class="pp">|</span> CR_SVD med <span class="pp">|</span> α=0 <span class="pp">|</span> α=12 <span class="pp">|</span> α=24 <span class="pp">|</span> α=32 <span class="pp">|</span> α=48 <span class="pp">|</span> α=64 <span class="pp">|</span> α=96 <span class="pp">|</span></span>
<span id="cb1-99"><a href="#cb1-99" aria-hidden="true" tabindex="-1"></a><span class="pp">|----:|------:|-----------:|----:|-----:|-----:|-----:|-----:|-----:|-----:|</span></span>
<span id="cb1-100"><a href="#cb1-100" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 150 <span class="pp">|</span> 16 <span class="pp">|</span> 16 <span class="pp">|</span> 16 (14–23) <span class="pp">|</span> 50 (41–71) <span class="pp">|</span> 94 (76–135) <span class="pp">|</span> 125 (104–183) <span class="pp">|</span> 204 (175–313) <span class="pp">|</span> 299 (235–486) <span class="pp">|</span> 538 (361–956) <span class="pp">|</span></span>
<span id="cb1-101"><a href="#cb1-101" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 300 <span class="pp">|</span> 10 <span class="pp">|</span> 25 <span class="pp">|</span> 25 (21–42) <span class="pp">|</span> 53 (45–87) <span class="pp">|</span> 98 (77–144) <span class="pp">|</span> 127 (106–188) <span class="pp">|</span> 205 (176–315) <span class="pp">|</span> 301 (236–488) <span class="pp">|</span> 538 (361–956) <span class="pp">|</span></span>
<span id="cb1-102"><a href="#cb1-102" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 450 <span class="pp">|</span>  8 <span class="pp">|</span> 32 <span class="pp">|</span> 32 (28–63) <span class="pp">|</span> 65 (53–107) <span class="pp">|</span> 105 (83–156) <span class="pp">|</span> 136 (110–197) <span class="pp">|</span> 212 (180–326) <span class="pp">|</span> 304 (239–495) <span class="pp">|</span> 538 (361–956) <span class="pp">|</span></span>
<span id="cb1-103"><a href="#cb1-103" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 750 <span class="pp">|</span>  5 <span class="pp">|</span> 51 <span class="pp">|</span> 51 (42–126) <span class="pp">|</span> 88 (70–184) <span class="pp">|</span> 126 (97–233) <span class="pp">|</span> 156 (126–275) <span class="pp">|</span> 231 (195–393) <span class="pp">|</span> 322 (259–556) <span class="pp">|</span> 550 (369–1003) <span class="pp">|</span></span>
<span id="cb1-104"><a href="#cb1-104" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-105"><a href="#cb1-105" aria-hidden="true" tabindex="-1"></a>*(Exact r, CR, RMSE and SNR for the gallery PID (dab512bd) are labelled in each cell.)*</span>
<span id="cb1-106"><a href="#cb1-106" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-107"><a href="#cb1-107" aria-hidden="true" tabindex="-1"></a><span class="al">![SVD-ε × WP-α reconstruction gallery for PID dab512bd (notable CSD). Rows: SVD-adapt ε ∈ {150, 300, 450, 750}; columns: WP α ∈ {0, 12, 24, 32, 48, 64, 96}. Each cell labels the selected rank r, achieved CRs, RMSE (µV), and SNR (dB).](figures/2026-06-12_adaptive_wp_gallery_dab512bd-a02d-4c1f-8dbc-9155a163efc0.png)</span></span>
<span id="cb1-108"><a href="#cb1-108" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-109"><a href="#cb1-109" aria-hidden="true" tabindex="-1"></a><span class="al">![Residual gallery (original − reconstruction). Same layout and colour scale. Residuals remain spatially incoherent up to the aggressive bottom-right corner (ε=750, α=96), where WP artefacts become visible.](figures/2026-06-12_adaptive_wp_gallery_dab512bd-a02d-4c1f-8dbc-9155a163efc0_residual.png)</span></span>
<span id="cb1-110"><a href="#cb1-110" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-111"><a href="#cb1-111" aria-hidden="true" tabindex="-1"></a><span class="fu">### CSD gallery (PID dab512bd)</span></span>
<span id="cb1-112"><a href="#cb1-112" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-113"><a href="#cb1-113" aria-hidden="true" tabindex="-1"></a>Same ε × α grid as above, but displaying the **current source density** (second spatial finite difference, scaled by tissue conductivity σ = 1/3 S m⁻¹) of the reconstructed LFP.</span>
<span id="cb1-114"><a href="#cb1-114" aria-hidden="true" tabindex="-1"></a>CSD emphasises the laminar sink/source structure and is more sensitive to spatial smearing than the raw LFP.</span>
<span id="cb1-115"><a href="#cb1-115" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-116"><a href="#cb1-116" aria-hidden="true" tabindex="-1"></a><span class="al">![CSD reconstruction gallery for PID dab512bd. Colour scale shared across all cells, set to the 99th percentile of the original CSD.](figures/2026-06-12_adaptive_wp_gallery_csd_dab512bd-a02d-4c1f-8dbc-9155a163efc0.png)</span></span>
<span id="cb1-117"><a href="#cb1-117" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-118"><a href="#cb1-118" aria-hidden="true" tabindex="-1"></a><span class="al">![CSD residual gallery — CSD(original) − CSD(reconstruction). Structured CSD residuals emerge at high ε and α, revealing where the spatial gradients are lost.](figures/2026-06-12_adaptive_wp_gallery_csd_dab512bd-a02d-4c1f-8dbc-9155a163efc0_residual.png)</span></span>
<span id="cb1-119"><a href="#cb1-119" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-120"><a href="#cb1-120" aria-hidden="true" tabindex="-1"></a><span class="fu">## Appendix: Per-insertion results</span></span>
<span id="cb1-121"><a href="#cb1-121" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-122"><a href="#cb1-122" aria-hidden="true" tabindex="-1"></a>Cadzow denoising and SVD-ε × WP-α adaptive gallery for each of the 11 benchmark insertions.</span>
<span id="cb1-123"><a href="#cb1-123" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-124"><a href="#cb1-124" aria-hidden="true" tabindex="-1"></a>::: {.callout-note collapse="true" appearance="minimal"}</span>
<span id="cb1-125"><a href="#cb1-125" aria-hidden="true" tabindex="-1"></a><span class="fu">## PID 1a276285</span></span>
<span id="cb1-126"><a href="#cb1-126" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-127"><a href="#cb1-127" aria-hidden="true" tabindex="-1"></a><span class="al">![Cadzow denoising — PID 1a276285.](figures/2026-06-06_cadzow_1a276285-8b0e-4cc9-9f0a-a3a002978724.png)</span></span>
<span id="cb1-128"><a href="#cb1-128" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-129"><a href="#cb1-129" aria-hidden="true" tabindex="-1"></a><span class="al">![Adaptive gallery (SVD-ε × WP-α) — PID 1a276285.](figures/2026-06-12_adaptive_wp_gallery_1a276285-8b0e-4cc9-9f0a-a3a002978724.png)</span></span>
<span id="cb1-130"><a href="#cb1-130" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-131"><a href="#cb1-131" aria-hidden="true" tabindex="-1"></a><span class="al">![Adaptive residual gallery — PID 1a276285.](figures/2026-06-12_adaptive_wp_gallery_1a276285-8b0e-4cc9-9f0a-a3a002978724_residual.png)</span></span>
<span id="cb1-132"><a href="#cb1-132" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-133"><a href="#cb1-133" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-134"><a href="#cb1-134" aria-hidden="true" tabindex="-1"></a>::: {.callout-note collapse="true" appearance="minimal"}</span>
<span id="cb1-135"><a href="#cb1-135" aria-hidden="true" tabindex="-1"></a><span class="fu">## PID 1e104bf4</span></span>
<span id="cb1-136"><a href="#cb1-136" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-137"><a href="#cb1-137" aria-hidden="true" tabindex="-1"></a><span class="al">![Cadzow denoising — PID 1e104bf4.](figures/2026-06-06_cadzow_1e104bf4-7a24-4624-a5b2-c2c8289c0de7.png)</span></span>
<span id="cb1-138"><a href="#cb1-138" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-139"><a href="#cb1-139" aria-hidden="true" tabindex="-1"></a><span class="al">![Adaptive gallery (SVD-ε × WP-α) — PID 1e104bf4.](figures/2026-06-12_adaptive_wp_gallery_1e104bf4-7a24-4624-a5b2-c2c8289c0de7.png)</span></span>
<span id="cb1-140"><a href="#cb1-140" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-141"><a href="#cb1-141" aria-hidden="true" tabindex="-1"></a><span class="al">![Adaptive residual gallery — PID 1e104bf4.](figures/2026-06-12_adaptive_wp_gallery_1e104bf4-7a24-4624-a5b2-c2c8289c0de7_residual.png)</span></span>
<span id="cb1-142"><a href="#cb1-142" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-143"><a href="#cb1-143" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-144"><a href="#cb1-144" aria-hidden="true" tabindex="-1"></a>::: {.callout-note collapse="true" appearance="minimal"}</span>
<span id="cb1-145"><a href="#cb1-145" aria-hidden="true" tabindex="-1"></a><span class="fu">## PID 6638cfb3</span></span>
<span id="cb1-146"><a href="#cb1-146" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-147"><a href="#cb1-147" aria-hidden="true" tabindex="-1"></a><span class="al">![Cadzow denoising — PID 6638cfb3.](figures/2026-06-06_cadzow_6638cfb3-3831-4fc2-9327-194b76cf22e1.png)</span></span>
<span id="cb1-148"><a href="#cb1-148" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-149"><a href="#cb1-149" aria-hidden="true" tabindex="-1"></a><span class="al">![Adaptive gallery (SVD-ε × WP-α) — PID 6638cfb3.](figures/2026-06-12_adaptive_wp_gallery_6638cfb3-3831-4fc2-9327-194b76cf22e1.png)</span></span>
<span id="cb1-150"><a href="#cb1-150" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-151"><a href="#cb1-151" aria-hidden="true" tabindex="-1"></a><span class="al">![Adaptive residual gallery — PID 6638cfb3.](figures/2026-06-12_adaptive_wp_gallery_6638cfb3-3831-4fc2-9327-194b76cf22e1_residual.png)</span></span>
<span id="cb1-152"><a href="#cb1-152" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-153"><a href="#cb1-153" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-154"><a href="#cb1-154" aria-hidden="true" tabindex="-1"></a>::: {.callout-note collapse="true" appearance="minimal"}</span>
<span id="cb1-155"><a href="#cb1-155" aria-hidden="true" tabindex="-1"></a><span class="fu">## PID 749cb2b7</span></span>
<span id="cb1-156"><a href="#cb1-156" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-157"><a href="#cb1-157" aria-hidden="true" tabindex="-1"></a><span class="al">![Cadzow denoising — PID 749cb2b7.](figures/2026-06-06_cadzow_749cb2b7-e57e-4453-a794-f6230e4d0226.png)</span></span>
<span id="cb1-158"><a href="#cb1-158" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-159"><a href="#cb1-159" aria-hidden="true" tabindex="-1"></a><span class="al">![Adaptive gallery (SVD-ε × WP-α) — PID 749cb2b7.](figures/2026-06-12_adaptive_wp_gallery_749cb2b7-e57e-4453-a794-f6230e4d0226.png)</span></span>
<span id="cb1-160"><a href="#cb1-160" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-161"><a href="#cb1-161" aria-hidden="true" tabindex="-1"></a><span class="al">![Adaptive residual gallery — PID 749cb2b7.](figures/2026-06-12_adaptive_wp_gallery_749cb2b7-e57e-4453-a794-f6230e4d0226_residual.png)</span></span>
<span id="cb1-162"><a href="#cb1-162" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-163"><a href="#cb1-163" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-164"><a href="#cb1-164" aria-hidden="true" tabindex="-1"></a>::: {.callout-note collapse="true" appearance="minimal"}</span>
<span id="cb1-165"><a href="#cb1-165" aria-hidden="true" tabindex="-1"></a><span class="fu">## PID d7ec0892</span></span>
<span id="cb1-166"><a href="#cb1-166" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-167"><a href="#cb1-167" aria-hidden="true" tabindex="-1"></a><span class="al">![Cadzow denoising — PID d7ec0892.](figures/2026-06-06_cadzow_d7ec0892-0a6c-4f4f-9d8f-72083692af5c.png)</span></span>
<span id="cb1-168"><a href="#cb1-168" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-169"><a href="#cb1-169" aria-hidden="true" tabindex="-1"></a><span class="al">![Adaptive gallery (SVD-ε × WP-α) — PID d7ec0892.](figures/2026-06-12_adaptive_wp_gallery_d7ec0892-0a6c-4f4f-9d8f-72083692af5c.png)</span></span>
<span id="cb1-170"><a href="#cb1-170" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-171"><a href="#cb1-171" aria-hidden="true" tabindex="-1"></a><span class="al">![Adaptive residual gallery — PID d7ec0892.](figures/2026-06-12_adaptive_wp_gallery_d7ec0892-0a6c-4f4f-9d8f-72083692af5c_residual.png)</span></span>
<span id="cb1-172"><a href="#cb1-172" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-173"><a href="#cb1-173" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-174"><a href="#cb1-174" aria-hidden="true" tabindex="-1"></a>::: {.callout-note collapse="true" appearance="minimal"}</span>
<span id="cb1-175"><a href="#cb1-175" aria-hidden="true" tabindex="-1"></a><span class="fu">## PID da8dfec1</span></span>
<span id="cb1-176"><a href="#cb1-176" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-177"><a href="#cb1-177" aria-hidden="true" tabindex="-1"></a><span class="al">![Cadzow denoising — PID da8dfec1.](figures/2026-06-06_cadzow_da8dfec1-d265-44e8-84ce-6ae9c109b8bd.png)</span></span>
<span id="cb1-178"><a href="#cb1-178" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-179"><a href="#cb1-179" aria-hidden="true" tabindex="-1"></a><span class="al">![Adaptive gallery (SVD-ε × WP-α) — PID da8dfec1.](figures/2026-06-12_adaptive_wp_gallery_da8dfec1-d265-44e8-84ce-6ae9c109b8bd.png)</span></span>
<span id="cb1-180"><a href="#cb1-180" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-181"><a href="#cb1-181" aria-hidden="true" tabindex="-1"></a><span class="al">![Adaptive residual gallery — PID da8dfec1.](figures/2026-06-12_adaptive_wp_gallery_da8dfec1-d265-44e8-84ce-6ae9c109b8bd_residual.png)</span></span>
<span id="cb1-182"><a href="#cb1-182" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-183"><a href="#cb1-183" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-184"><a href="#cb1-184" aria-hidden="true" tabindex="-1"></a>::: {.callout-note collapse="true" appearance="minimal"}</span>
<span id="cb1-185"><a href="#cb1-185" aria-hidden="true" tabindex="-1"></a><span class="fu">## PID dab512bd</span></span>
<span id="cb1-186"><a href="#cb1-186" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-187"><a href="#cb1-187" aria-hidden="true" tabindex="-1"></a><span class="al">![Cadzow denoising — PID dab512bd.](figures/2026-06-06_cadzow_dab512bd-a02d-4c1f-8dbc-9155a163efc0.png)</span></span>
<span id="cb1-188"><a href="#cb1-188" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-189"><a href="#cb1-189" aria-hidden="true" tabindex="-1"></a><span class="al">![Adaptive gallery (SVD-ε × WP-α) — PID dab512bd.](figures/2026-06-12_adaptive_wp_gallery_dab512bd-a02d-4c1f-8dbc-9155a163efc0.png)</span></span>
<span id="cb1-190"><a href="#cb1-190" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-191"><a href="#cb1-191" aria-hidden="true" tabindex="-1"></a><span class="al">![Adaptive residual gallery — PID dab512bd.](figures/2026-06-12_adaptive_wp_gallery_dab512bd-a02d-4c1f-8dbc-9155a163efc0_residual.png)</span></span>
<span id="cb1-192"><a href="#cb1-192" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-193"><a href="#cb1-193" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-194"><a href="#cb1-194" aria-hidden="true" tabindex="-1"></a>::: {.callout-note collapse="true" appearance="minimal"}</span>
<span id="cb1-195"><a href="#cb1-195" aria-hidden="true" tabindex="-1"></a><span class="fu">## PID dc7e9403</span></span>
<span id="cb1-196"><a href="#cb1-196" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-197"><a href="#cb1-197" aria-hidden="true" tabindex="-1"></a><span class="al">![Cadzow denoising — PID dc7e9403.](figures/2026-06-06_cadzow_dc7e9403-19f7-409f-9240-05ee57cb7aea.png)</span></span>
<span id="cb1-198"><a href="#cb1-198" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-199"><a href="#cb1-199" aria-hidden="true" tabindex="-1"></a><span class="al">![Adaptive gallery (SVD-ε × WP-α) — PID dc7e9403.](figures/2026-06-12_adaptive_wp_gallery_dc7e9403-19f7-409f-9240-05ee57cb7aea.png)</span></span>
<span id="cb1-200"><a href="#cb1-200" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-201"><a href="#cb1-201" aria-hidden="true" tabindex="-1"></a><span class="al">![Adaptive residual gallery — PID dc7e9403.](figures/2026-06-12_adaptive_wp_gallery_dc7e9403-19f7-409f-9240-05ee57cb7aea_residual.png)</span></span>
<span id="cb1-202"><a href="#cb1-202" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-203"><a href="#cb1-203" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-204"><a href="#cb1-204" aria-hidden="true" tabindex="-1"></a>::: {.callout-note collapse="true" appearance="minimal"}</span>
<span id="cb1-205"><a href="#cb1-205" aria-hidden="true" tabindex="-1"></a><span class="fu">## PID e8f9fba4</span></span>
<span id="cb1-206"><a href="#cb1-206" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-207"><a href="#cb1-207" aria-hidden="true" tabindex="-1"></a><span class="al">![Cadzow denoising — PID e8f9fba4.](figures/2026-06-06_cadzow_e8f9fba4-d151-4b00-bee7-447f0f3e752c.png)</span></span>
<span id="cb1-208"><a href="#cb1-208" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-209"><a href="#cb1-209" aria-hidden="true" tabindex="-1"></a><span class="al">![Adaptive gallery (SVD-ε × WP-α) — PID e8f9fba4.](figures/2026-06-12_adaptive_wp_gallery_e8f9fba4-d151-4b00-bee7-447f0f3e752c.png)</span></span>
<span id="cb1-210"><a href="#cb1-210" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-211"><a href="#cb1-211" aria-hidden="true" tabindex="-1"></a><span class="al">![Adaptive residual gallery — PID e8f9fba4.](figures/2026-06-12_adaptive_wp_gallery_e8f9fba4-d151-4b00-bee7-447f0f3e752c_residual.png)</span></span>
<span id="cb1-212"><a href="#cb1-212" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-213"><a href="#cb1-213" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-214"><a href="#cb1-214" aria-hidden="true" tabindex="-1"></a>::: {.callout-note collapse="true" appearance="minimal"}</span>
<span id="cb1-215"><a href="#cb1-215" aria-hidden="true" tabindex="-1"></a><span class="fu">## PID eebcaf65</span></span>
<span id="cb1-216"><a href="#cb1-216" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-217"><a href="#cb1-217" aria-hidden="true" tabindex="-1"></a><span class="al">![Cadzow denoising — PID eebcaf65.](figures/2026-06-06_cadzow_eebcaf65-7fa4-4118-869d-a084e84530e2.png)</span></span>
<span id="cb1-218"><a href="#cb1-218" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-219"><a href="#cb1-219" aria-hidden="true" tabindex="-1"></a><span class="al">![Adaptive gallery (SVD-ε × WP-α) — PID eebcaf65.](figures/2026-06-12_adaptive_wp_gallery_eebcaf65-7fa4-4118-869d-a084e84530e2.png)</span></span>
<span id="cb1-220"><a href="#cb1-220" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-221"><a href="#cb1-221" aria-hidden="true" tabindex="-1"></a><span class="al">![Adaptive residual gallery — PID eebcaf65.](figures/2026-06-12_adaptive_wp_gallery_eebcaf65-7fa4-4118-869d-a084e84530e2_residual.png)</span></span>
<span id="cb1-222"><a href="#cb1-222" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-223"><a href="#cb1-223" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-224"><a href="#cb1-224" aria-hidden="true" tabindex="-1"></a>::: {.callout-note collapse="true" appearance="minimal"}</span>
<span id="cb1-225"><a href="#cb1-225" aria-hidden="true" tabindex="-1"></a><span class="fu">## PID fe380793</span></span>
<span id="cb1-226"><a href="#cb1-226" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-227"><a href="#cb1-227" aria-hidden="true" tabindex="-1"></a><span class="al">![Cadzow denoising — PID fe380793.](figures/2026-06-06_cadzow_fe380793-8035-414e-b000-09bfe5ece92a.png)</span></span>
<span id="cb1-228"><a href="#cb1-228" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-229"><a href="#cb1-229" aria-hidden="true" tabindex="-1"></a><span class="al">![Adaptive gallery (SVD-ε × WP-α) — PID fe380793.](figures/2026-06-12_adaptive_wp_gallery_fe380793-8035-414e-b000-09bfe5ece92a.png)</span></span>
<span id="cb1-230"><a href="#cb1-230" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-231"><a href="#cb1-231" aria-hidden="true" tabindex="-1"></a><span class="al">![Adaptive residual gallery — PID fe380793.](figures/2026-06-12_adaptive_wp_gallery_fe380793-8035-414e-b000-09bfe5ece92a_residual.png)</span></span>
<span id="cb1-232"><a href="#cb1-232" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-233"><a href="#cb1-233" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-234"><a href="#cb1-234" aria-hidden="true" tabindex="-1"></a>::: {.callout-note collapse="true" appearance="minimal"}</span>
<span id="cb1-235"><a href="#cb1-235" aria-hidden="true" tabindex="-1"></a><span class="fu">## SVD-adapt-WP algorithm in detail</span></span>
<span id="cb1-236"><a href="#cb1-236" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-237"><a href="#cb1-237" aria-hidden="true" tabindex="-1"></a>The two-stage algorithm operates on a snippet matrix $X \in \mathbb{R}^{n_c \times n_s}$ (channels × samples):</span>
<span id="cb1-238"><a href="#cb1-238" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-239"><a href="#cb1-239" aria-hidden="true" tabindex="-1"></a>**Stage 1 — spatial compression (SVD)**</span>
<span id="cb1-240"><a href="#cb1-240" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-241"><a href="#cb1-241" aria-hidden="true" tabindex="-1"></a>$$X \approx \hat{X}_1 = U_r \, \text{diag}(s_r) \, V_r^\top$$</span>
<span id="cb1-242"><a href="#cb1-242" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-243"><a href="#cb1-243" aria-hidden="true" tabindex="-1"></a>where $U_r \in \mathbb{R}^{n_c \times r}$, $s_r \in \mathbb{R}^r$, $V_r^\top \in \mathbb{R}^{r \times n_s}$ are the top-$r$ singular triplets.</span>
<span id="cb1-244"><a href="#cb1-244" aria-hidden="true" tabindex="-1"></a>The rank $r$ is chosen to achieve a target CR (e.g. CR=24 → $r \approx 12$).</span>
<span id="cb1-245"><a href="#cb1-245" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-246"><a href="#cb1-246" aria-hidden="true" tabindex="-1"></a>**Stage 2 — temporal compression (wavelet packets)**</span>
<span id="cb1-247"><a href="#cb1-247" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-248"><a href="#cb1-248" aria-hidden="true" tabindex="-1"></a>Each of the $r$ rows of $V_r^\top$ is independently compressed using db4 wavelet packet decomposition (level 5).</span>
<span id="cb1-249"><a href="#cb1-249" aria-hidden="true" tabindex="-1"></a>Only the top-$f$ fraction of coefficients by magnitude are retained, giving an overall:</span>
<span id="cb1-250"><a href="#cb1-250" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-251"><a href="#cb1-251" aria-hidden="true" tabindex="-1"></a>$$\text{CR}_{\text{total}} = \frac{n_c \, n_s}{r(n_c + n_s)} \cdot \frac{1}{f}$$</span>
<span id="cb1-252"><a href="#cb1-252" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-253"><a href="#cb1-253" aria-hidden="true" tabindex="-1"></a>**SVD-adapt (ε-sweep)** selects rank automatically using:</span>
<span id="cb1-254"><a href="#cb1-254" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-255"><a href="#cb1-255" aria-hidden="true" tabindex="-1"></a>$$\sigma_0 = \text{median}(s_{\lfloor r/2 \rfloor + 1}, \ldots, s_r), \qquad r^* = \max<span class="sc">\{</span>k : s_k &gt; \varepsilon \cdot \sigma_0<span class="sc">\}</span>$$</span>
<span id="cb1-256"><a href="#cb1-256" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-257"><a href="#cb1-257" aria-hidden="true" tabindex="-1"></a>Here $\sigma_0$ is the noise-floor estimate (median of the lower half of the full singular value spectrum), and $\varepsilon$ is a dimensionless threshold — the minimum signal-to-noise-floor ratio $s_k / \sigma_0$ required to retain a component. Equivalently, $\varepsilon(r) = s_r / \sigma_0$ is the $\varepsilon$ that would select exactly rank $r$ (as shown in the calibration figure). Sweeping $\varepsilon$ from $10^4$ (keep only the dominant component) down to $10^{-1}$ (keep almost everything) traces out the full CR curve.</span>
<span id="cb1-258"><a href="#cb1-258" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-259"><a href="#cb1-259" aria-hidden="true" tabindex="-1"></a>**Reconstruction** reverses the two stages: reconstruct each wavelet-compressed row, then reassemble $\hat{X} = U_r \, \text{diag}(s_r) \, \hat{V}_r^\top$.</span>
<span id="cb1-260"><a href="#cb1-260" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-261"><a href="#cb1-261" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-262"><a href="#cb1-262" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-263"><a href="#cb1-263" aria-hidden="true" tabindex="-1"></a>::: {.callout-note collapse="true" appearance="minimal"}</span>
<span id="cb1-264"><a href="#cb1-264" aria-hidden="true" tabindex="-1"></a><span class="fu">## WP coefficient selection: per-coefficient error thresholding</span></span>
<span id="cb1-265"><a href="#cb1-265" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-266"><a href="#cb1-266" aria-hidden="true" tabindex="-1"></a>**Setup.**</span>
<span id="cb1-267"><a href="#cb1-267" aria-hidden="true" tabindex="-1"></a>After SVD truncation at rank $r$, each retained temporal component is a row $V_k \in \mathbb{R}^{n_s}$ of $V_r^\top$ with unit $\ell_2$-norm ($<span class="sc">\|</span>V_k<span class="sc">\|</span>_2 = 1$, since $V$ is orthonormal).</span>
<span id="cb1-268"><a href="#cb1-268" aria-hidden="true" tabindex="-1"></a>The full reconstruction contribution of component $k$ to $X$ is $s_k U_k V_k^\top$, whose Frobenius norm is $s_k$.</span>
<span id="cb1-269"><a href="#cb1-269" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-270"><a href="#cb1-270" aria-hidden="true" tabindex="-1"></a>**Wavelet-packet decomposition.**</span>
<span id="cb1-271"><a href="#cb1-271" aria-hidden="true" tabindex="-1"></a>Each $V_k$ is decomposed into $n_\text{WP}$ coefficients $<span class="sc">\{</span>w_{kj}<span class="sc">\}</span>$ via a full db4 wavelet-packet tree at level 5</span>
<span id="cb1-272"><a href="#cb1-272" aria-hidden="true" tabindex="-1"></a>(for $n_s = 750$, $n_\text{WP} = 960$).</span>
<span id="cb1-273"><a href="#cb1-273" aria-hidden="true" tabindex="-1"></a>Because the WP transform is orthogonal, $\sum_j w_{kj}^2 = <span class="sc">\|</span>V_k<span class="sc">\|</span>_2^2 = 1$.</span>
<span id="cb1-274"><a href="#cb1-274" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-275"><a href="#cb1-275" aria-hidden="true" tabindex="-1"></a>**Per-component hard threshold.**</span>
<span id="cb1-276"><a href="#cb1-276" aria-hidden="true" tabindex="-1"></a>For each component $k$, a threshold is set as</span>
<span id="cb1-277"><a href="#cb1-277" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-278"><a href="#cb1-278" aria-hidden="true" tabindex="-1"></a>$$\tau_k = \frac{\alpha \cdot \sigma_0}{s_k}$$</span>
<span id="cb1-279"><a href="#cb1-279" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-280"><a href="#cb1-280" aria-hidden="true" tabindex="-1"></a>and coefficient $w_{kj}$ is retained only if $|w_{kj}| \geq \tau_k$; otherwise it is set to zero:</span>
<span id="cb1-281"><a href="#cb1-281" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-282"><a href="#cb1-282" aria-hidden="true" tabindex="-1"></a>$$\tilde{w}_{kj} = w_{kj} \cdot \mathbf{1}\!\left[|w_{kj}| \geq \tau_k\right]$$</span>
<span id="cb1-283"><a href="#cb1-283" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-284"><a href="#cb1-284" aria-hidden="true" tabindex="-1"></a>**Per-coefficient error guarantee.**</span>
<span id="cb1-285"><a href="#cb1-285" aria-hidden="true" tabindex="-1"></a>Zeroing $w_{kj}$ changes the reconstruction by $s_k \, U_k \cdot \delta v_{kj}^\top$, where $\delta v_{kj}$ is the inverse-WP basis vector for coefficient $j$ with unit norm.</span>
<span id="cb1-286"><a href="#cb1-286" aria-hidden="true" tabindex="-1"></a>The resulting Frobenius error contribution is</span>
<span id="cb1-287"><a href="#cb1-287" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-288"><a href="#cb1-288" aria-hidden="true" tabindex="-1"></a>$$s_k \cdot |w_{kj}| \;&lt;\; s_k \cdot \tau_k \;=\; \alpha \cdot \sigma_0$$</span>
<span id="cb1-289"><a href="#cb1-289" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-290"><a href="#cb1-290" aria-hidden="true" tabindex="-1"></a>*Every discarded coefficient, in every component, contributes less than $\alpha \cdot \sigma_0$ to the reconstruction error* — uniformly across all ranks.</span>
<span id="cb1-291"><a href="#cb1-291" aria-hidden="true" tabindex="-1"></a>This is the same absolute noise-floor reference $\sigma_0$ used by the SVD stage, so the two thresholds speak the same language.</span>
<span id="cb1-292"><a href="#cb1-292" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-293"><a href="#cb1-293" aria-hidden="true" tabindex="-1"></a>**Compression ratio.**</span>
<span id="cb1-294"><a href="#cb1-294" aria-hidden="true" tabindex="-1"></a>The WP stage CR is the ratio of total available coefficient slots to those retained:</span>
<span id="cb1-295"><a href="#cb1-295" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-296"><a href="#cb1-296" aria-hidden="true" tabindex="-1"></a>$$\text{CR}_\text{WP} = \frac{r \cdot n_\text{WP}}{\#\{(k,j) : s_k |w_{kj}| \geq \alpha\sigma_0<span class="sc">\}</span>}$$</span>
<span id="cb1-297"><a href="#cb1-297" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-298"><a href="#cb1-298" aria-hidden="true" tabindex="-1"></a>**Behaviour across the component spectrum.**</span>
<span id="cb1-299"><a href="#cb1-299" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-300"><a href="#cb1-300" aria-hidden="true" tabindex="-1"></a>For a component with singular value $s_k = q \cdot \varepsilon \cdot \sigma_0$ (where $q \geq 1$, since only components above the SVD threshold are retained), the WP threshold becomes</span>
<span id="cb1-301"><a href="#cb1-301" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-302"><a href="#cb1-302" aria-hidden="true" tabindex="-1"></a>$$\tau_k = \frac{\alpha}{q \cdot \varepsilon}$$</span>
<span id="cb1-303"><a href="#cb1-303" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-304"><a href="#cb1-304" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Dominant components** ($q \gg 1$, $s_k \gg \varepsilon\sigma_0$): $\tau_k$ is small, many WP coefficients survive — the component's full temporal structure is preserved with only fine-scale details discarded.</span>
<span id="cb1-305"><a href="#cb1-305" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Marginal components** ($q \approx 1$, $s_k \approx \varepsilon\sigma_0$): $\tau_k \approx \alpha/\varepsilon$.  If $\alpha/\varepsilon$ exceeds the largest WP coefficient magnitude of $V_k$ (empirically 0.05–0.2 for LFP), the entire component is zeroed.  This is consistent behaviour: the component was weakly significant spatially *and* has no concentrated temporal structure, so it genuinely carries little information.</span>
<span id="cb1-306"><a href="#cb1-306" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-307"><a href="#cb1-307" aria-hidden="true" tabindex="-1"></a>This component-level zeroing is not a design flaw — it is the natural outcome of applying a uniform per-coefficient error threshold to components with flat (noise-like) temporal spectra.</span>
<span id="cb1-308"><a href="#cb1-308" aria-hidden="true" tabindex="-1"></a>In practice, at the recommended operating point ($\varepsilon \approx 150$, $\alpha \approx 28$, $\alpha/\varepsilon \approx 0.19$), components at ranks 7–13 are fully eliminated by WP, while the first 5–6 components retain 5–70% of their WP coefficients for genuine temporal compression.</span>
<span id="cb1-309"><a href="#cb1-309" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-310"><a href="#cb1-310" aria-hidden="true" tabindex="-1"></a>**Relationship to the SVD threshold.**</span>
<span id="cb1-311"><a href="#cb1-311" aria-hidden="true" tabindex="-1"></a>The two parameters are not independent: when $\alpha/\varepsilon &gt; \max_j |w_{r,j}|$ (the largest WP coefficient of the weakest retained component), WP overrides the SVD rank selection.</span>
<span id="cb1-312"><a href="#cb1-312" aria-hidden="true" tabindex="-1"></a>The curves in the aggregate figure converge at high $\alpha$ because all $\varepsilon$ settings end up keeping the same dominant components once $\alpha$ is large enough to purge the weaker ones.</span>
<span id="cb1-313"><a href="#cb1-313" aria-hidden="true" tabindex="-1"></a>The non-redundant operating region is $\alpha/\varepsilon \lesssim 0.1$, where WP compresses temporal structure within every kept component without discarding any of them entirely.</span>
<span id="cb1-314"><a href="#cb1-314" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-315"><a href="#cb1-315" aria-hidden="true" tabindex="-1"></a>**Survival floor on the dominant component.**</span>
<span id="cb1-316"><a href="#cb1-316" aria-hidden="true" tabindex="-1"></a>Purging *weak* components (above) is benign. The pathological case is when the same mechanism zeroes the *dominant* component $k=0$: this happens on low-SNR recordings where $s_0/\sigma_0 \lesssim \alpha/\max_j|w_{0j}| \approx 140$, at which point $\tau_0$ exceeds every coefficient of $V_0$, $\hat V_r^\top = 0$, and the chunk reconstructs to exact zero — destroying genuine low-amplitude LFP.</span>
<span id="cb1-317"><a href="#cb1-317" aria-hidden="true" tabindex="-1"></a>To bound this, the dominant component always retains its $n_\text{min}=64$ largest-magnitude WP coefficients regardless of $\tau_0$:</span>
<span id="cb1-318"><a href="#cb1-318" aria-hidden="true" tabindex="-1"></a>$$<span class="sc">\#\{</span>j : \tilde w_{0j} \neq 0<span class="sc">\}</span> \geq \min(n_\text{min},\, n_\text{WP}).$$</span>
<span id="cb1-319"><a href="#cb1-319" aria-hidden="true" tabindex="-1"></a>The floor is applied only to $k=0$, so weaker components still vanish (preserving CR), and it is a no-op on healthy recordings, whose dominant row already keeps $\gg n_\text{min}$ coefficients — leaving their reconstruction bit-for-bit identical. A genuinely silent input (e.g. a saturation-muted span) has $s_0 = 0$ hence $U_r\,\text{diag}(s_r) = 0$, so it still reconstructs to zero and the floor cannot fabricate signal.</span>
<span id="cb1-320"><a href="#cb1-320" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-321"><a href="#cb1-321" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-322"><a href="#cb1-322" aria-hidden="true" tabindex="-1"></a>::: {.callout-note collapse="true" appearance="minimal"}</span>
<span id="cb1-323"><a href="#cb1-323" aria-hidden="true" tabindex="-1"></a><span class="fu">## Cadzow denoising with adaptive rank and imputation</span></span>
<span id="cb1-324"><a href="#cb1-324" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-325"><a href="#cb1-325" aria-hidden="true" tabindex="-1"></a>**F-X Cadzow: working frequency bin by frequency bin** *(parameters used: nw=64, f_max=100 Hz, max rank r=5, gap_threshold=2.0, ppca_k=2.0)*</span>
<span id="cb1-326"><a href="#cb1-326" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-327"><a href="#cb1-327" aria-hidden="true" tabindex="-1"></a>This is the *F-X* (frequency–space) variant of Cadzow denoising, borrowed from seismic processing.</span>
<span id="cb1-328"><a href="#cb1-328" aria-hidden="true" tabindex="-1"></a>Rather than applying SVD to the full time × channel matrix, the algorithm works one frequency bin at a time:</span>
<span id="cb1-329"><a href="#cb1-329" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-330"><a href="#cb1-330" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>**rfft** the snippet → complex array $W \in \mathbb{C}^{n_c \times n_f}$.</span>
<span id="cb1-331"><a href="#cb1-331" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>For each frequency bin $f \leq f_\text{max}$, extract the spatial vector $w_f \in \mathbb{C}^{n_c}$ (one complex amplitude per channel).</span>
<span id="cb1-332"><a href="#cb1-332" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>Build a **block-Toeplitz trajectory matrix** $T_f$ from $w_f$.</span>
<span id="cb1-333"><a href="#cb1-333" aria-hidden="true" tabindex="-1"></a><span class="ss">4. </span>Compute the rank-$r$ SVD of $T_f$, zero the remaining singular values, and read off the denoised amplitudes.</span>
<span id="cb1-334"><a href="#cb1-334" aria-hidden="true" tabindex="-1"></a><span class="ss">5. </span>**irfft** back to the time domain.</span>
<span id="cb1-335"><a href="#cb1-335" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-336"><a href="#cb1-336" aria-hidden="true" tabindex="-1"></a>**Outlier imputation (`ppca_k`)**: after the first rank-$r$ projection, channels deviating by more than $\text{median} + k \cdot \text{MAD}$ are replaced by their model prediction; the SVD is repeated on the cleaned data.</span>
<span id="cb1-337"><a href="#cb1-337" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-338"><a href="#cb1-338" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-339"><a href="#cb1-339" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-340"><a href="#cb1-340" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-341"><a href="#cb1-341" aria-hidden="true" tabindex="-1"></a>::: {.callout-note collapse="true" appearance="minimal"}</span>
<span id="cb1-342"><a href="#cb1-342" aria-hidden="true" tabindex="-1"></a><span class="fu">## Prior context: transform methods</span></span>
<span id="cb1-343"><a href="#cb1-343" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-344"><a href="#cb1-344" aria-hidden="true" tabindex="-1"></a>Before focusing on SVD variants, we benchmarked six approaches: SVD, Wavelet Packets (WP), DCT, DCT-δ, STFT, and SVD+WP.</span>
<span id="cb1-345"><a href="#cb1-345" aria-hidden="true" tabindex="-1"></a>SVD consistently outperformed all transform-only methods at every compression ratio.</span>
<span id="cb1-346"><a href="#cb1-346" aria-hidden="true" tabindex="-1"></a>The figure below shows the full comparison; the current analysis refines and extends only the SVD family.</span>
<span id="cb1-347"><a href="#cb1-347" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-348"><a href="#cb1-348" aria-hidden="true" tabindex="-1"></a><span class="al">![Initial aggregate benchmark (11 PIDs) including all transform methods. SVD and SVD+WP dominate at every CR. DCT-δ is worst throughout.](figures/2026-06-06_compression_aggregate.png)</span></span>
<span id="cb1-349"><a href="#cb1-349" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-350"><a href="#cb1-350" aria-hidden="true" tabindex="-1"></a><span class="al">![Reconstruction gallery from initial benchmark — PID dab512bd. SVD retains spatial structure to CR=100; transform methods show block/stripe artefacts from CR=30.](figures/2026-06-06_compression_gallery_dab512bd-a02d-4c1f-8dbc-9155a163efc0.png)</span></span>
<span id="cb1-351"><a href="#cb1-351" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-352"><a href="#cb1-352" aria-hidden="true" tabindex="-1"></a><span class="al">![Residual gallery from initial benchmark. SVD/SVD+WP residuals are spatially incoherent; DCT and STFT residuals carry structured spectral artefacts at high CR.](figures/2026-06-06_compression_gallery_dab512bd-a02d-4c1f-8dbc-9155a163efc0_residual.png)</span></span>
<span id="cb1-353"><a href="#cb1-353" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-354"><a href="#cb1-354" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-355"><a href="#cb1-355" aria-hidden="true" tabindex="-1"></a>::: {.callout-note collapse="true" appearance="minimal"}</span>
<span id="cb1-356"><a href="#cb1-356" aria-hidden="true" tabindex="-1"></a><span class="fu">## Prior-context: Gap-criterion rank selection (discarded)</span></span>
<span id="cb1-357"><a href="#cb1-357" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-358"><a href="#cb1-358" aria-hidden="true" tabindex="-1"></a>We investigated an alternative rank-selection criterion based on the largest relative drop in the singular value spectrum (the "gap"):</span>
<span id="cb1-359"><a href="#cb1-359" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-360"><a href="#cb1-360" aria-hidden="true" tabindex="-1"></a>$$r_\text{gap} = \underset{i}{\arg\max}\; \frac{s_i}{s_{i+1}} + 1$$</span>
<span id="cb1-361"><a href="#cb1-361" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-362"><a href="#cb1-362" aria-hidden="true" tabindex="-1"></a>We also swept a gap threshold $g$, defining rank as the last position where $s_k / s_{k+1} \geq g$.</span>
<span id="cb1-363"><a href="#cb1-363" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-364"><a href="#cb1-364" aria-hidden="true" tabindex="-1"></a>!<span class="co">[</span><span class="ot">Gap ratio sv[k]/sv[k+1] at each rank boundary for each of the 11 PIDs. Reference lines at g=2, 5, 10.</span><span class="co">](figures/2026-06-10_gap_vs_rank.png)</span></span>
<span id="cb1-365"><a href="#cb1-365" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-366"><a href="#cb1-366" aria-hidden="true" tabindex="-1"></a>The figure reveals why this criterion was discarded: after Cadzow denoising, the SV ratio at rank 1 is only **1.3–2.4** across all 11 PIDs — the dominant "gap" is barely larger than the secondary gaps.</span>
<span id="cb1-367"><a href="#cb1-367" aria-hidden="true" tabindex="-1"></a>There is no clean separation between signal and noise in the SV ratio spectrum, so the gap threshold has very little sensitivity to the compression ratio.</span>
<span id="cb1-368"><a href="#cb1-368" aria-hidden="true" tabindex="-1"></a>The ε-threshold (noise-floor-relative) criterion is far better calibrated for this data.</span>
<span id="cb1-369"><a href="#cb1-369" aria-hidden="true" tabindex="-1"></a>:::</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>Olivier Winter</p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>
<script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","descPosition":"bottom","loop":false,"openEffect":"zoom","selector":".lightbox"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script>




</body></html>